### ISSUE TITLE
AppleWin fails to start - throws "Card: wrong slot" error message then quits

### ISSUE THREAD

**Issue by frankmilliron** [AppleWin/AppleWin#1015]
Latest AppleWin 1.30.7.0 refusing to start up. Throws an error stating "Card: wrong slot" and immediately quits without allowing me to change any preferences which might fix the error. I am on MacOS 10.14.6 using WINE 5.0, which was working previously using AppleWin 1.30.4.0.

**Comment by tomcw** [comment]
Hi @frankmilliron - this is either a problem with Registry config or loading a save-state.
(I assume it's the former, since you say it "immediately quits".)

Can you export the Registry keys for "Computer\HKEY_CURRENT_USER\SOFTWARE\AppleWin" including all child nodes?
EG:
- Press the "Windows" key, then type "RegEdit", hit return  (and click "Yes" to any 'User Access Control' message)
- File -> Export
- Selected branch = "HKEY_CURRENT_USER\SOFTWARE\AppleWin"
- Save it as (eg) "fm.txt"  (with "Save as type" set to .txt)
- Attach it to this issue

**Comment by audetto** [comment]
We should probably add a bit more information to the error message. Like which card in which slot.

**Comment by frankmilliron** [comment]
I had tried out the new Phasor entry for slot 4 and 5, so that may be what it doesn't like. Attached is my registry entry for AppleWin.
[fm.reg.zip](https://github.com/AppleWin/AppleWin/files/7808566/fm.reg.zip)

**Comment by tomcw** [comment]
This .reg file will fix your Registry and allow AppleWin to startup: [fm-fix.zip](https://github.com/AppleWin/AppleWin/files/7809225/fm-fix.zip)

You'll need to re-insert the HDD image though.

---

This is a bug in the legacy Registry support, which I will fix.

Also as @audetto says, all of these "Card: wrong slot" error messages should be improved (eg. in this specific case it's trying to insert a Disk II Interface card into slot 7).

**Comment by frankmilliron** [comment]
Thanks Tom! the new registry fixes it.

**Comment by audetto** [comment]
https://github.com/AppleWin/AppleWin/pull/1025

**Comment by tomcw** [comment]
Thanks @audetto for improving the error messages (when loading a save-state).
Closing.

**Comment by tomcw** [comment]
@frankmilliron: FYI, a new [AppleWin 1.30.8.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.8.0) that corrects this issue + includes @audetto's improved error messages when loading a save-state.

**Comment by frankmilliron** [comment]
@tomcw Thanks! I'll check it out.
