### ISSUE TITLE
Deprecate support for building with VS2008

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1050]
Since April 2021 (10 months ago) I've been building releases with VS2019 v141_xp, which has been fine.

@Michaelangel007 , @sicklittlemonkey , @audetto:
Is it time to retire VS2008 support?

Nick: in the past you've said: "I presume that means it will be ok to use modern C++ features."
Basically C++11 things like range-based for loops, std::shared_ptr, `nullptr` etc. seem fine.
But perhaps some initial limits on _gratuitous_ use of `auto` and lambdas?

EG, this PR seems to take C++11 Initializer Lists too far:
https://github.com/AppleWin/AppleWin/pull/634/files

Can someone suggest some sensible limits?

**Comment by sicklittlemonkey** [comment]
Whether it would be good to be able to use modern C++ is probably a matter of taste. ; - )
Since these days I don't get to use C++ at work much (or contribute to AppleWin!) I'm a bit out of touch.
I would be interested in the opinions of the more active recent contributors.

There are some established style guides we could adopt or copy from. E.g.
https://google.github.io/styleguide/cppguide.html

This one is more philosophical about being dragged kicking and screaming into the future.
https://isocpp.github.io/CppCoreGuidelines
This latter one appeals to me in terms of modernizing the codebase.
It might line up well with all the great refactoring you guys have been doing recently.

**Comment by audetto** [comment]
To me the reasons to move away from 2008 are

- hard to test. not easy to find the compiler any longer.
- allow to use a few good improvements to C++ (some of which are in https://github.com/AppleWin/AppleWin/pull/1051)

The good pattern for me include

1. unique_ptr
2. range based loop
3. static_assert
4. vector initialiser list
5. default value for member variables

**Comment by kiyolee** [comment]
I do this all for fun and deprecating VS2008 or not imposes different kinds of challenge and fun. However, as a software project moving forward, deprecating VS2008 makes more sense. With latest C++ features, a lot of code can be modernised and simplified. Ideally this should also reduce the barrier for new contributors. I would even suggest to make C++14 (default for VS2019) the minimum requirement.

**Comment by tomcw** [comment]
btw, the v141 toolset is used to build the AppleWin release.

This VC++ v14.1 is from Visual Studio 2017 (v15.0)... but is still shipped with VS2019.

It has some level of support for C++11/14/17 (but not complete) - I can't find a good description of what is / isn't supported.
I suppose these C++ features added at 15.3 ([here](https://devblogs.microsoft.com/cppblog/c17-features-and-stl-fixes-in-vs-2017-15-3/)) show what is *not* in 15.0.

As always we have AppleWin users still on old versions of Windows, so I'll stick with v141 toolset for now.

**Comment by kiyolee** [comment]
I think [here](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170) is a good doc about what various C/C++ features are supported in what various versions of VS.
Note that though the v141_xp toolkit for VS2017 has been deprecated since VS2019.
The toolkit is still available for VS2019 or VS2022 but marked as deprecated.
So in thoery the toolkit may be gone in some newer version of VS.
By that time, VS2017 would become the new VS2008 and I think that'd be fine, for at least another 10 years perhaps.

**Comment by tomcw** [comment]
Hi Nick - that [Google C++ style guide](https://google.github.io/styleguide/cppguide.html) is extensive, but there may be a few things worth just cherry-picking, eg:

[Type deduction (including auto)](https://google.github.io/styleguide/cppguide.html#Type_deduction):
- Use type deduction only if it makes the code clearer to readers who aren't familiar with the project, or if it makes the code safer. Do not use it merely to avoid the inconvenience of writing an explicit type.

@kiyolee - from your doc about VS version support for C++, it looks like VS2017(v15.0) supports up to and including some of the C++17 Core language features, which probably will be good enough.

**Comment by tomcw** [comment]
@kiyolee - I will add something to AppleWin's simple CodingConventions.doc to be explicit about not using `sprintf()`, `StringCbPrintf()`, `wsprinf()` - and instead use `StrFormat()`.

**Comment by Michaelangel007** [comment]
+1 for removing MSVC 2008. 

I'm using MSVC 2013 / 2019 so I won't complain for a few years. =P
 
As to what is reasonable C++ ... now that is a tricky thing to answer.  Every person you ask will provide a _different_ answer.  Some are diehard C fans, others C++ fan boys.  **Both languages suck.**

I personally hate modern Crap++ and how programmers tend to over-engineer and complicate the simplest of problems using language features just because they can such as that Boost garbage. I also especially `auto` (because it wastes my time trying to figure out what the hell the actual type is), along with the _hideous_ notation for lambdas.  My personal preference is to use C++ as minimally as possible. i.e. a `C+`, a balanced middle ground between C and C++.  I have better things to do with my time then to be constantly wasting my time being a C++ language lawyer because someone thinks the spaceship operator `<=>` is cool.

That said, I would be OK with standardizing on C++11 if we must use modern C++.

**Comment by sicklittlemonkey** [comment]
> My personal preference is to use C++ as minimally as possible. i.e. a `C+`, a balanced middle ground between C and C++. I have better things to do with my time then to be constantly wasting my time being a C++ language lawyer because someone thinks the spaceship operator `<=>` is cool.

Hah, well said. I pretty much agree. I sometimes describe it as as C++-.
Classes and exception handling are probably the most useful additions to C.
Some of the standard library features such as pointer management are useful.
Templates are great when necessary, but a compile-time nightmare.

**Comment by audetto** [comment]
IMHO the greatest feature of C++ over C is **resource management**.
Having spent half of my life coding (work and hobby), I yet have to see a project where **manual** memory management is done correctly.
There are few tools (actually just one and it does not work on Windows), people don't know how to use it and are anyway not interested.

So for me, things like `std::string`, `std::vector` and `std::unique_ptr` (or `std::shared_ptr` if not available) are a no-brainer: I would even go further and forbid explicit usage of `delete`.

The other features I mentioned at the top of this issue are syntactic sugar and nowhere near as important as this.

**Comment by sicklittlemonkey** [comment]
> IMHO the greatest feature of C++ over C is **resource management**.

Yes, again, well said. This is what I meant by the use of classes and "pointer management". Using classes for RAII means all resources should be managed by class lifetime. In the 90's I started using auto_ptr, which changed everything. (But had to fix bugs in the implementation we used - thanks to Scott Meyers' first books.)

Still, this ability to manage resources is just a side-effect of constructors and destructors, so classes are the big win, also for encapsulation and code reuse via inheritance etc. I mention exceptions specifically because returning an error code for every function - or especially doing setjmp and longjmp - are so obviously inferior.

Anyway, it seems we actually have some opposition to the "syntactic sugar" features of modern C++. Perhaps we should stick to vanilla C++ syntax unless something cannot be accomplished safely without a more recent C++ syntax.

**Comment by audetto** [comment]
> I mention exceptions specifically because returning an error code for every function - or especially doing setjmp and longjmp - are so obviously inferior.

definitely.
Add exceptions or different `return` paths and your memory management problem goes through the roof...

**Comment by Michaelangel007** [comment]
> Having spent half of my life coding (work and hobby), I yet have to see a project where **manual** memory management is done correctly.

In my ~30 years of shipping games I've **never** seen where _automatic_ memory management has worked long term.  Sooner or later you WILL fragment memory.  Garbage collection is for amateur programmers 1/ too lazy to understand HOW they use memory, and 2/ don't care about run-time performance.  With apologies to JWZ:

_Ignoring memory management doesn't make it go away. Now you have two problems._

One of the 4 [lies of programming](https://www.youtube.com/watch?v=zWGn3kMz3rU) we tell themselves is that "we have infinite memory."  I've fallen to that mistake myself in the debugger.  Who cares how big `std::vector<>` gets, right?  If we've exhausted it we have bigger problems, pass the buck -> not my problem.  For a "small" application like AppleWin it isn't a big deal but it still feels wrong to have sloppy coding without being more defensive such as `.reserve()` and/or validating `.size()` isn't getting to large.

> I mention exceptions specifically because returning an error code for every function - or especially doing setjmp and longjmp - are so obviously inferior.

Pardon the pun but I take exception to part of that.
 
`setjmp()` and `longjmp()` are obviously bad hacks. I'm glad they are banished.

Returning error codes with (synchronous) functions is perfectly fine, depending on context.  Yeah, for every function, that just isn't practical.  But "bigger" functions, sure.

The problem with exceptions is that they have [numerous](https://medium.com/codex/the-error-of-exceptions-3aed074c40dc) not just a single [problem](http://shanekirk.com/2015/06/c-exceptions-the-good-the-bad-and-the-ugly/).  In the best case an exception is just a `goto` but sadly that almost impossible in practice. The C++ committee is aware of the  HUGE [problems](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2544r0.html).  The big 3 problems are:

* overhead of exceptions is significant
* exception unwinding is single-threaded
* exceptions use dynamic memory which kills optimization

There is still no good long solution to the problems they raise (pardon the pun.)  Stack unwinding is a huge PITA for C++ compiler writers; the huge overhead at run-time for those that have near real-time requirements is why many of us old school coders said "_Just turn the damn things off."_

My first choice would be to banish exceptions completely.

However, the good news is that we don't need to obsess over _every_ last millisecond in AppleWin.  We're largely single-threaded anyways so whatever overhead exceptions are adding I highly doubt it matters much in practice.  This _doesn't_ mean we should become complacent but we should at least remain mindful of when/where/why we "need" exceptions.

So if there are people that feel strongly about using exceptions I will begrudgingly accept them.  We should be doing periodic profiling anyways so we understand where the overhead is coming from.  If exceptions show up on the profiler then we can rethink their usage.
