### ISSUE TITLE
debugger feature request: break on undefined instructions

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1063]
It would be great to have an option to trap on the 65C02 instructions in 6502 mode, for example.  That way I can find out quickly if I missed any when porting 65C02 titles to 6502.

**Comment by tomcw** [comment]
Maybe the existing feature to 'break on invalid opcodes' covers it...?

Setup:
- F7 (enter debugger)
- `300: 1A 60`  (setup some 65C02 specific test code - where: $1A = nop (6502) or INC A (65C02))
- `brk all on` (setup to enter debugger on BRK or Invalid opcode)
- `g`  (resume emulation, but in "STEPPING" mode)

To test it:

1. Select Enhanced Apple //e, and `CALL768` will _**not**_ trap to the debugger.
2. Select Apple II+ (or Original //e), and `CALL768` will trap to the debugger.

**Comment by audetto** [comment]
If I may, I would like to request something similar.
If it possible to break into AppleWin debugger via C++?

Le't say I am in a IOHandler in Visual Studio debugger and I would like to trigger the AppleWin debugger asap, as soon as this 6502 instruction returns?

What I have done so far is to keep a not of the instruction address and try to generate a break point, but it is very tedious and error prone.

```
if (some_condition)
{
    g_SoftwareBreakpoint = true;
}
```

**Comment by tomcw** [comment]
@audetto - yes this is possible...

- Run the emulator in STEPPING mode (ie. F7, `g`)
  - NB. this now runs 1 opcode on each call to `ContinueEmulation()` before it drops back to AppleWin's message pump.
- Position the AppleWin window and the Visual Studio window so that they are not overlapping (ie. put them side-by-side).
- Set a Visual Studio breakpoint and let it trigger.
  - EG, In Disk.cpp: Disk2InterfaceCard::IORead(), set a breakpoint on `case 0x9`, which is a read from $C0E9 (Disk II motor off).
  - On the Apple II, `CALL-151`, then `C0E9`... and the Visual Studio BP will trigger.
- Now on the AppleWin window, use the mouse to click the "Magnifying Glass" icon **once**.
  - NB. Nothing happens which is correct, but internally the message queue now has a mouse click event.
- And then click back on Visual Studio, and click the "Continue" icon.
- AppleWin will now enter the debugger at the point of the next opcode.

NB. This doesn't work in normal RUNNING mode, as that executes ~1000 cycles (so ~400 opcodes?) on each call to `ContinueEmulation()`, so it's not very precise - but maybe OK sometimes.

**Comment by peterferrie** [comment]
@tomcw Thank you.  Yes, my request is supported already.  I just had to read the help file.
