### ISSUE TITLE
WOZ: Trying to crack with Passport using an empty WOZ results in "T22 Fatal write error"

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1086]
Repro:
- Using Passport 2022-02-04
- Drive 1 = Run For It.woz (or even just the passport.dsk)
- Drive 2 = a blank WOZ
- (C)rack disk

```
Passport by 4am               2022-02-04
                                        
 ______________________________________ 
   ___________________________________  
                                        
                                        
Reading from S6,D1                      
T00,S00 Found ProDOS bootloader         
T00,S0B Volume name is PASSPORT         
Using built-in RWTS                     
Writing to S6,D2                        
                                        
T22 Fatal write error                   
                                        
Possible reasons:                       
                                        
- There is no disk in S6,D2.            
- The disk has bad sectors.             
- The disk is unformatted.              
                                        
Press any key `                         
```

**Comment by mr-stivo** [comment]
The target needs to be formatted. Using a truly blank WOZ (all track data set to 0's) I get the same error on my emulator. Using the same WOZ but formatting it beforehand it completes the cracking process.

But... here's where it gets weird...

On AppleWin:

- Using a write protected Run For It source disk, the resulting cracked version doesn't get past the K/J screen (write protected or not).
- Using a non-write protected Run For It source disk, the resulting cracked version works (write protected or not).

I guess the problems from #1078 are apparent even through Passport since it's using the source's RWTS.

**Comment by tomcw** [comment]
For empty (non-existent) woz tracks the data should be random, not all 0's.
But from what you are saying, Passport requires the target disk to have some address/data prologues written(?)
It seems odd that Passport can't copy to an unformatted disk.
So I suspect a bug in AppleWin.

**Comment by mr-stivo** [comment]
On my emulator and OpenEmulator, the all 0's ends up being random data when read since it exceeds to two zero bits in a row rule. (maybe not the best example of a blank disk, I wasn't sure of the best way to repressent it).

As far as I know, passport requires a formatted target disk.

Can you post your blank woz image?  I'll try it with Passport on OpenEmulator and my emulator.

**Comment by tomcw** [comment]
To create an empty woz: click the icon to open a disk image, then type the name of a file that doesn't exist (eg. Blank1.woz). This will tell AppleWin to create an empty WOZ.

Btw, you can do the same with DSK & NIB too.

**Comment by mr-stivo** [comment]
I asked 4am about it and he said the target disk needs to be formatted beforehand. Also, using a blank woz created with AppleWin and my own blank woz, I had the same results you did with MAME and VII.

**Comment by tomcw** [comment]
OK, with commit cb37dd3, I can now copy a _write protected_ Run For It disk with Passport.
