### ISSUE TITLE
What's wrong with RGB?

### ISSUE THREAD

**Issue by DocDoom99** [AppleWin/AppleWin#1087]
AppleWin 1.30.9.0

Can you please find an explanation for this behavior?
With RGB after losing a life the screen looks like this
![RGB](https://user-images.githubusercontent.com/84972398/162588894-40afa011-17b9-4013-a237-f0314242f7ee.png)

With Composite Idealized everything appears normal.
![CI](https://user-images.githubusercontent.com/84972398/162588897-b32f6db3-4f17-4b22-a3cb-4edb68058020.png)

Thanks

Marco

**Comment by tomcw** [comment]
What's the game? Looks like it's accidently putting the RGB card into 160-pixel mode.

**Comment by DocDoom99** [comment]
The game is d\generation, but something similar also happens with DazzleDraw.

**Comment by tomcw** [comment]
Dazzle Draw works correctly with an RGB card, but perhaps this game wasn't tested with it when being developed. I will take a look...

**Comment by DocDoom99** [comment]
I understand, I'm sorry but I really didn't think DazzleDraw was meant to be seen in black and white.
![DD](https://user-images.githubusercontent.com/84972398/163334488-6bf836fb-5fc2-4d47-bdc3-ce80cd6e0c5a.png)

**Comment by tomcw** [comment]
You are right, DD should not be in B&W like this for the RGB Card/Monitor video mode. It should be in colour, except IIRC the dialog/message boxes.

Which version of DD are you running?

**Comment by DocDoom99** [comment]
Version 1.2, downloaded here:
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/graphics/dazzle_draw/Dazzle%20Draw%201.2.dsk

**Comment by tomcw** [comment]
AppleWin 1.30.8.0 with DD v1.2 (July 17,1988):

![DD-1 2](https://user-images.githubusercontent.com/6696896/163711544-856b8bda-b9fc-4940-b815-c377b19d82e3.png)

Note that some parts of the screen are B&W, and other parts are colour.
(Same for the version dated 9/16/85)

**This is correct when using an RGB card/display.**

I guess the Beagle Bros picture you have loaded has the picture bytes all with bit7=0 (in MIX mode, bit7=0 is B&W, bit7=1 is colour).

Hmm, actually if I load pictures from "DD.FLIPSIDE" (version 9/16/85) then they appear in B&W too. EG, MONARCH
Then if I pick a fine black brush, I can go round the edge and change bit7 from 0 to 1, introducing colour... (!)

![DD-Monarch](https://user-images.githubusercontent.com/6696896/163711900-dcdfc57f-176b-41f3-a0b4-771db9bd93ad.png)

Even using the 800K .po image for v1.2, the MONARCH picture is still B&W (and all others pictures in the slideshow too).
Ref: https://archive.org/details/e2gs_1652_Dazzle_Draw_v1.2_Apple_IIe

NB. for both versions (1985 and v1.2), the DD title screen is correctly showing B&W and colour - ie. this is an RGB MIX mode picture:

![DD-title](https://user-images.githubusercontent.com/6696896/163712550-cb26d26c-e23a-41da-a1db-114805d66f9d.png)

Conclusion: the original slideshow pictures were created with bit7=0 and were never updated to be compatible with RGB cards. This seems very odd, since this means in the 3 years from 1985 (v1.0?) to 1988 (v1.2) no one ever tested the slideshow with an RGB card!

**Comment by tomcw** [comment]
## D-Generation:

This game (which is a preliminary version) doesn't support RGB card modes.

---

Details:

When you die:

```
1195:
  BIT C056 ; HIRES OFF
  BIT C050 ; TEXT OFF
  BIT C05F ; DHIRES OFF
```

Flash GR1 screen with magenta (0x11)
```
11E8:AE 90 0D             LDX $0D90      0D90:01
11EB:9D 0C C0             STA SW_SLOT+1,XC00D:00
11EE:AE 92 0D             LDX $0D92      0D92:00
11F1:9D 54 C0             STA PAGE2OFF,X C055:00
11F4:AE 93 0D             LDX $0D93      0D93:00
11F7:9D 50 C0             STA TEXTOFF,X  C051:00
11FA:AE 95 0D             LDX $0D95      0D95:01
11FD:9D 56 C0             STA HIRESOFF,X C057:00
1200:8D 7E C0             STA $C07E      C07E:00  ; //c IOUDIS=On, ie. enable access to DHIRES switch
1203:2C 5E C0             BIT DHIRESON   C05E:00
1206:60                   RTS
```

Every time the RGB card detects a $C05E -> $C05F "edge", then it clocks in the inverted state of "80COL" into a 2-bit RGB-mode register.

So at game start, initially RGB-mode = 00 (140 pixel colour mode, ie. standard RGB colour mode)
1st death: RGB-mode = 01 (160 pixel colour mode, which uses all 8 bits per byte - ie. the weird screen in your first screenshot above)
2nd death: RGB-mode = 11 (560 pixel B&W mode)

**Comment by DocDoom99** [comment]
Thanks for the detailed analysis.
