### ISSUE TITLE
BPM(W) not triggering if disk is what wrote to targeted memory

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1103]
I ran Skyfox from TR.
Run to 8005 (i.e., start a mission, pass the tactical view, and start take-off)
BP 8008
BPMW 7FB5
7FB5 current holds $9E
G
8008 is reached, 7FB5 holds $85.

**Comment by tomcw** [comment]
Thanks Peter.

This regressed at AppleWin 1.30.7, when I changed the HDD firmware to do a DMA of the block to RAM, instead of using the 6502 to copy it byte by byte.

I'll get this fixed.

**Comment by peterferrie** [comment]
Thanks Tom.  Would it better to keep both paths and choose according to the presence of BPM?

**Comment by sicklittlemonkey** [comment]
In sure it can be special-cased for debug. I think Tom cares about
performance even more than I do, if that's possible! ; - )

**Comment by tomcw** [comment]
Hi Peter - how about this as a solution...

- when the debugger is active (eg. breakpoints enabled) then trap on HDD r/w's that match the BPM[R|W]
- the breakpoint will fire *after* the whole HDD r/w operation has completed
- eg. if you read 4 blocks to $2000: all memory [$2000-27FF] will be updated, then it will trap & break in the debugger
- you'll get a suitable message saying BP#, which address (range) caused the trap and if it was a read or write

This is not consistent with regular memory write breakpoints (BPMW), which will trap _before_ the write is done.

If it is important to trap before the memory is updated, then let me know.

**Comment by peterferrie** [comment]
Hi Tom,

> - when the debugger is active (eg. breakpoints enabled) then trap on HDD
> r/w's that match the BPM[R|W]
> - the breakpoint will fire *after* the whole HDD r/w operation has
> completed

Yes, that works.

> This is not consistent with regular memory write breakpoints (BPMW), which
> will trap _before_ the write is done.
>
> If it is important to trap before the memory is updated, then let me know.

"When" is not important for me.  I just need to know "how", so this is
a great solution.

**Comment by tomcw** [comment]
@peterferrie - here's the 1.30.11.0 [release](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.11.0) with this now supported.

For your Skyfox case, here's the breakpoint firing, with the "Stop reason" message giving some information about the memory written to, and which breakpoint (BP) caused the trap.

![GH1103-HDD-BP](https://user-images.githubusercontent.com/6696896/175398430-15658eb2-87d2-439b-acd8-203acd39ee76.png)

NB. It fires in the HDD Interface card's firmware.
You can't just use the debugger command `rts` to get out of the firmware, since there's a value pushed to the stack. So you'll need to single-step about 6 times to return to your calling code.
