### ISSUE TITLE
Graphical glitches in A2D in RGB and Idealized Composite modes

### ISSUE THREAD

**Issue by inexorabletash** [AppleWin/AppleWin#1143]
With Apple II Desktop (eg 1.2 beta 2 build from https://github.com/a2stuff/a2d/releases/tag/v1.2-beta2 - grab the EN build and unzip to get a 2MG out), AppleWin 1.30.11.0 has graphical glitches in the lower left corner of the screen when in RGB or Composite (Idealized) mode, but not the others. 

![4C4D683F-E3A3-4D7F-824F-E84CA13A8382](https://user-images.githubusercontent.com/771547/202879304-9a14a72e-941b-471b-b793-6917d3b20bd5.jpeg)

It's a half-pixel tall black line, flickering and/or varying in width. If I enter the debugger with F7 then resume with g it disappears, and doesn't appear until a restart of AppleWin.

**Comment by tomcw** [comment]
Hi @inexorabletash - I have had a quick go at trying to repro this bug, but I can't get it to trigger.

I'm using AppleWin 1.30.11.0, A2DeskTop-1.2-beta2-en_800k.2mg and either "RGB" or "Color (Composite Idealized)" video modes, as you have specified.

I can see from your screenshot, that "50% Scan lines" is off (but either on or off, it doesn't trigger).
Also I assume you are running with the default 60Hz (not 50Hz) - but again it doesn't trigger for either setting.

Perhaps attach a save-state when the bug is occurring?
Or describe some more details repro steps from within A2D to trigger this issue.

Thanks.

**Comment by inexorabletash** [comment]
I'll see what other AppleWin settings I may have tweaked. No further steps required A2D itself - it happens immediately on launch, and doesn't seem coupled to anything you do.

**Comment by tomcw** [comment]
OK, I can get it to happen now:
1) After a boot, there is a **very short** initial black line that flickers (just before the A2.Desktop & Trash icons are shown).
2) If I press PAUSE, then the black line is visible

NB. If I enable "VidHD in slot 3", then I can't get it to happen.

**Comment by tomcw** [comment]
Bug introduced at 1.30.11.0, and present in 1.30.12.0.

**Comment by inexorabletash** [comment]
Awesome - glad it was too hard to diagnose.

**Comment by tomcw** [comment]
Yeah - thanks for reporting this (I don't tend to run in non-"50% Scan lines" mode).
I'll try to put out a new release very soon.

**Comment by tomcw** [comment]
NB. Fixed in release [AppleWin 1.30.13.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.13.0).
