### ISSUE TITLE
loading save-state in A2osX actives wrong stack page

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#1262]
Repro: requires Enhanced IIe CPU
- boot A2osX 2642 from https://github.com/A2osX/A2osX/tree/master/.Floppies
- enter debugger, note stack-page contents
- save state
- restore state
- stack page is zeroed
It doesn't seem to be filled from the save-state file at all.

**Comment by tomcw** [comment]
Hi Peter - I'll take a look.

btw, is it the 800K or 32MB image?

**Comment by peterferrie** [comment]
Thanks Tom. I used the 32MB image, and Mockingboard in slot 4 (used for
timer).

**Comment by tomcw** [comment]
Hmm... I can't reproduce this.

My steps:
- Enhanced //e with Mockingboard in slot 4 (and HDD Controller in slot 7)
- boot STABLE.32MB.po, and wait until the prompt ("/FULL32/root/$") and flashing cursor
  - ![STABLE 32MB-0-just-booted](https://github.com/AppleWin/AppleWin/assets/6696896/d931c16b-4dee-458d-bdce-eab2d1d4b2a2)
- F7 to enter debugger (and note that ALTZP switch has been selected)
- `m1 100` to show stack page (page 1)
- `data` to show entire page
- save state
  -  ![STABLE 32MB-0-debugger-page1](https://github.com/AppleWin/AppleWin/assets/6696896/eeb2831f-31d7-4e65-8519-df0085769ce2)
- restore state
  - ![STABLE 32MB-0-debugger-page1-after-restore](https://github.com/AppleWin/AppleWin/assets/6696896/45134c9b-459b-41aa-8425-3cab6228102b)
  - Note the only difference is "cycles:00000000"
- there's no change to the stack page

Can you attach your save-state file? (You'll need to zip it)

**Comment by burniouf** [comment]
btw, would love to see 
IO.RDALTZP=$C016
displayed with other switch states :-)

**Comment by tomcw** [comment]
> btw, would love to see IO.RDALTZP=$C016 displayed with other switch states :-)

It is (but it's a little obscure)... when ALTZP is enabled then there's a red "x" on the penultimate row ("80:B2..."), between "M" and "R". See the screenshots above.

**Comment by burniouf** [comment]
yes, agree..... it is somewhat present....but would be better displaying it a bit more explicit :-)
....and....(would save my life in actual debugging session ! ) is there a way to know which RamWorks bank is active ?

**Comment by tomcw** [comment]
>is there a way to know which RamWorks bank is active ?

Yes... the end of the last line ("88:B1...") : 'rNN' will appear if a RamWorks 64K bank is active.

**Comment by peterferrie** [comment]
[b1.aws.zip](https://github.com/AppleWin/AppleWin/files/13790181/b1.aws.zip)
save-state file.

**Comment by tomcw** [comment]
Thanks, I can repro with this save-state file.
(The problem occurs when there are _more than one_ aux 64K banks (eg. a RAMWorks card with 2 or more aux 64K banks).
I'll take a proper look at fixing this later.

**Comment by tomcw** [comment]
Hi Peter - there's a pre-release of 1.30.17 [here](https://github.com/AppleWin/AppleWin/releases/download/v1.30.17.0/AppleWin1.30.17.0.zip) - can you give it a go?

**Comment by audetto** [comment]
I was curious to understand the fix (and the problem).

This comment

https://github.com/AppleWin/AppleWin/blob/fea4173b437976e2e7c30eca94fa7b806937455c/source/Memory.cpp#L1443

is not crystal clear to me.

*pointless* seems to imply that there is a performance penalty if it is done all the times (in particular when not needed)
but
*corrupt* is totally different.

I imagine that at *worse* it is a waste of time since it is either already consistent or not needed.
When can it make things worse?

Is `load` the real special case?

**Comment by peterferrie** [comment]
Hi Tom, it's working for me.

**Comment by tomcw** [comment]
Great, thanks Peter for confirming.
(I'll switch to this a full release)

Andrea, I'll reply to you next...

**Comment by tomcw** [comment]
Hi @audetto:
> This comment [...] is not crystal clear to me.

When loading a state file, the function `BackMainImage()` never needs to be called - which is why I wrote it's "pointless". Maybe a better word is redundant. But worse is the corruption it does to pages 0 and 1, so probably my wording would be better to instead say "must be avoided" (and include some explanation).

FYI, `BackMainImage()` copies dirty pages from `mem` (*) to the 64K "physical" RAM bank. Once these dirty pages have been copied, then the 64K RAM bank is correct (or consistent), and so it can be saved or used by the debugger. There's no point in making it consistent for save-state _loads_, since the state file already contains the consistent 64K RAM banks.

(*) `mem` is the 64K bank that's consistent for CPU reads.
btw, there's some good discussion & description of `mem` etc. in #795.

TBH, there are still questions in the code as to why `UpdatePaging()` is needing to be called earlier in the save-state loading process, eg:
https://github.com/AppleWin/AppleWin/blob/fea4173b437976e2e7c30eca94fa7b806937455c/source/Memory.cpp#L2366

I'll spin off a new dev-issue to track that.

**Comment by audetto** [comment]
Thank you.
So `true` is the *normal* case when I want to (just) read the memory, while `false` is better left to the people who understand what they are doing.

**Comment by tomcw** [comment]
Yes, that's a good summary.

But I understand your point. Perhaps (whilst checking #1267) I can get rid of this new `bool isSaveSnapshotOrDebugging` parameter, eg. if I were to invalidate all the `memshadow[]` pointers. Then there's no need to remember which is the normal vs special case.

**Comment by tomcw** [comment]
Add regression test for this issue: https://github.com/AppleWin/AppleWin-Test/commit/16a30a1aab93df94e2e7d6662ded236951158897

**Comment by sh95014** [comment]
@tomcw Or perhaps giving `isSaveSnapshotOrDebugging` a default parameter value of `true`?

**Comment by tomcw** [comment]
Yes, that's another option. Ideally I can remove this 2nd bool parameter completely.
