### ISSUE TITLE
QUESTION: How do I convert UTF-8 encoding to something apple recognizes

### ISSUE THREAD

**Issue by Degamisu** [AppleWin/AppleWin#1307]
I might be stupid, but i cant figure out how to convert the text from a bas file into something the IIe can read. The first line is always a jumbled up mess which breaks the code.

_Originally posted by @Degamisu in https://github.com/AppleWin/AppleWin/issues/1306#issuecomment-2132222555_

**Comment by inexorabletash** [comment]
Sounds like the file might contain a Byte Order Mark (BOM), which is a Unicode signature at the start of the file. For UTF-8 files, this is three non-ASCII bytes. 

If you're using Notepad, try saving as either UTF-8 without the BOM, or as plain ASCII, ANSI, ISO-8859-1, or ISO-Latin-1 which for a valid AppleSoft file would all be the same.

**Comment by Degamisu** [comment]
alright! any encoding settings i need to do in cider press? besides the whole applesoft basic filetype and stuff.

**Comment by Degamisu** [comment]
any updates?

**Comment by tomcw** [comment]
Can you attach the bas file here?
(You'll have to zip it up, as you can only attach certain file types to GitHub issues)

**Comment by tomcw** [comment]
btw, you can just copy ASCII text from (eg) Notepad to the Windows clipboard (CTRL+A, CTRL+C), then if you select AppleWin, from AppleSoft (BASIC prompt) you can paste this by using SHIFT+INSERT. At this point you assuming you've booted with DOS 3.3, then just `SAVE MYCODE` to save it to the disk.

**Comment by Degamisu** [comment]
@tomcw 
[MANDEL.zip](https://github.com/AppleWin/AppleWin/files/15491316/MANDEL.zip)

**Comment by sicklittlemonkey** [comment]
Hello.

The BAS file in the ZIP archive is the same program in your other AppleWin issue #1306. It's from another dialect of BASIC, so it won't work as is on the Apple II, even with the changes you've made. (For instance COLOR= is an Applesoft command for setting the LORES colour, and the apostrophe won't work - you need to use REM for a comment. Actually even the algorithm will need changes because it causes an overflow in Applesoft. Here's [an Applesoft Mandrelbrot program](https://pastebin.com/ucfMKgw8) that works better.)

I don't want to discourage you, so please take this as friendly advice. You've opened issues against the AppleWin project, which is an emulator. The problems you're having are not related to AppleWin, but are because you don't yet have enough knowledge about the Apple II to solve your problems.

Probably the best thing for you to to do would be to get in involved in an Apple II community online, ask questions, read books, and then you'll be able to solve the problems you're trying to solve.

There's a friendly [Apple II Enthusiast Facebook group](https://www.facebook.com/groups/5251478676), a [subreddit](https://www.reddit.com/r/apple2/), a [Slack Channel](https://prodos8.com/apple2infinitum/), and various forums like [AppleFritter](https://www.applefritter.com/forum/84) and an [Apple II forum](https://forums.atariage.com/forum/158-apple-ii-computers/) at AtariAge. I'm sure you can find more.

There are many books you could read, e.g. [here](https://vintageapple.org/apple_ii/), or on [Archive.org](https://archive.org/search?query=apple+ii+books). For Applesoft there's this classic official [tutorial](https://archive.org/details/the-applesoft-tutorial-1979/mode/2up) and this official [reference](https://archive.org/details/applesoft-basic-programmers-reference-manual-vol-1-iie-only/), but there are many other user guides and programming books to choose from.

Cheers,
Nick.

**Comment by Degamisu** [comment]
> Hello.
> 
> The BAS file in the ZIP archive is the same program in your other AppleWin issue #1306. It's from another dialect of BASIC, so it won't work as is on the Apple II, even with the changes you've made. (For instance COLOR= is an Applesoft command for setting the LORES colour, and the apostrophe won't work - you need to use REM for a comment. Actually even the algorithm will need changes because it causes an overflow in Applesoft. Here's [an Applesoft Mandrelbrot program](https://pastebin.com/ucfMKgw8) that works better.)
> 
> I don't want to discourage you, so please take this as friendly advice. You've opened issues against the AppleWin project, which is an emulator. The problems you're having are not related to AppleWin, but are because you don't yet have enough knowledge about the Apple II to solve your problems.
> 
> Probably the best thing for you to to do would be to get in involved in an Apple II community online, ask questions, read books, and then you'll be able to solve the problems you're trying to solve.
> 
> There's a friendly [Apple II Enthusiast Facebook group](https://www.facebook.com/groups/5251478676), a [subreddit](https://www.reddit.com/r/apple2/), a [Slack Channel](https://prodos8.com/apple2infinitum/), and various forums like [AppleFritter](https://www.applefritter.com/forum/84) and an [Apple II forum](https://forums.atariage.com/forum/158-apple-ii-computers/) at AtariAge. I'm sure you can find more.
> 
> There are many books you could read, e.g. [here](https://vintageapple.org/apple_ii/), or on [Archive.org](https://archive.org/search?query=apple+ii+books). For Applesoft there's this classic official [tutorial](https://archive.org/details/the-applesoft-tutorial-1979/mode/2up) and this official [reference](https://archive.org/details/applesoft-basic-programmers-reference-manual-vol-1-iie-only/), but there are many other user guides and programming books to choose from.
> 
> Cheers, Nick.

Hello!

I haven't done apple programming in years, mostly c/cpp. The `COLOR=` command I entered was a mistake, I meant to use `COL=`. I don't really use comments, so I am not familiar with the REM command. My mistake! Since the apple IIe is very old, (and part of my horrible searching skills 😆) I couldn't really find too many books on applesoft. Anyways. Thanks for the resources! Ill check them out later. I'll close this now.
