### ISSUE TITLE
Lower case 't' needs an extra pixel

### ISSUE THREAD

**Issue by sicklittlemonkey** [AppleWin/AppleWin#1308]
User "Cosmos Soup" has found a little bug that I completely missed when trying to help him with a hires font.

The following image from AppleWin is mixed hires/text. The top text is at the bottom of the hires screen, drawn by the Applesoft (or DOS) Toolkit's HRCG. The bottom text is AppleWin's text at the top of the 4-line text window. Notice that the 't' characters differ by one pixel, and according to Sather (and MAME etc) the HRCG text is correct. (I don't have running hardware to verify on.)

![image](https://github.com/AppleWin/AppleWin/assets/4393005/5cddf128-47a8-4d0f-a65b-91ce168bc8c2)

I looked at the commit history for CHARSET4.BMP, and it looks the same back to 2006. Maybe even further?

Anyway, it's never to late to dot your i's and cross your t's. Or in this case, dot your t's!

Cheers,
Nick.

**Comment by xotmatrix** [comment]
Whoa! I cannot believe I never noticed this. I build my glyphs from video ROM and can confirm the "t" ascender is one pixel short in AppleWin going back to at least 2004 (the earliest version I have installed). Affects the inverse version too. 
See: 
[CHARSET4.BMP](https://github.com/AppleWin/AppleWin/blob/master/resource/CHARSET4.BMP)
[Debug_Font.bmp](https://github.com/AppleWin/AppleWin/blob/master/resource/Debug_Font.bmp)

![AppleWin-charset-vs-ROM-annotated](https://github.com/AppleWin/AppleWin/assets/14209329/b29209cf-8cc2-46a5-b398-dae4e40213a9)

**Comment by xotmatrix** [comment]
PR submitted:
https://github.com/AppleWin/AppleWin/pull/1309

**Comment by tomcw** [comment]
Thanks both - as you (@xotmatrix) say, we should use the original video rom, and not rely on a bitmap.
I will accept your PR, since the `Debug_Font.bmp` contains extra chars that don't exist in the video rom.

**Comment by tomcw** [comment]
I've created a new PR #1311 to use the actual video ROMs (and have removed CHARSET4.BMP).

**Comment by tomcw** [comment]
Thanks all - this'll be in the next release (soon, I hope!)

**Comment by Michaelangel007** [comment]
Thanks for fixing this in `Debug_Font.bmp`.  I can't believe I didn't spot that sooner!  

Thankfully my other texture atlas from my [Apple \]\[ //e HGR Font 6502 Assembly Language Tutorial](https://github.com/Michaelangel007/apple2_hgr_font_tutorial) is correct since I went right to Jim Sather's _Understanding the Apple //e_ so I never ran into that issue.

i.e.
![apple2e_font](https://github.com/user-attachments/assets/496e8fe5-444a-4b84-89cc-97ae547fd46a) 

 @sicklittlemonkey Thank-you for your advice years ago! _Check Sather first!_ :-)
