### ISSUE TITLE
Chessmaster 2000 crashes to Monitor on boot

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#133]
**BerliOS Bug #18109**

**Date:** 2011-May-10 21:07
**Submitted By:** tomch
**Category:** 1.20.0
**Bug Group:** none
**Assigned To:** nick_westgate
**Priority:** 5

====

[Email from Karl-Stephan Werkmeister]

I've realised that Chessmaster 2000 (at least the images I've got from http://www.virtualapple.org/) are not booting correctly on AppleWin newer than 1.13.1.0. They *do* boot on 1.13.1.0 or even *older* versions.

**Comment by sicklittlemonkey** [comment]
Time to update this before it gets closed. First, DataWiz replied to Peter on comp.sys.apple2:
https://groups.google.com/forum/#!topic/comp.sys.apple2/xHrW45igYY8/discussion

DataWiz cracked Chessmaster 2000 (which had a check for some kind of clone) and used an old ('97?) version of AppleWin to debug it. It didn't work so he patched it (EA EA) to work on AppleWin.

Years later, my stepping code update in AppleWin fixed Mabel's Mansion, but broke the CM 2000 version which had been patched to work with the old AppleWin! I've since fixed the stepping code in GSport too, so here's the updated test table:

    Platform        Original (F0 12) Patched (EA EA) 
    AppleWin (old)  Fails            Works 
    AppleWin (now)  Works            Fails 
    GSport (old)    Fails            Works 
    GSport (now)    Works            Fails 
    ROM 3 GS        Works            Fails 
    ROM 4 //c       Works            Fails 

CM 2000 should definitely be left in its original state (F0 12) and all's well.

Cheers,
Nick.
