### ISSUE TITLE
Bank Street Music Writer - playback in jukebox starts with lower volume

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#1333]
From @roughana via Slack:
>I just tried bank street music writer from Asimov on applewin and noticed that playback in jukebox for the first bar was lower volume than the rest. Not sure if that is deliberate for every piece with its playback or if Applewin needs to “warm up”
>
>https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/sound/Bank_Street_Music_Writer_A.DSK & _B
>
>Use jukebox option and songs are on side B.

**Comment by tomcw** [comment]
In trying to repro this (using a debug build of AppleWin), I get an ASSERT when exiting the Jukebox in `SY6522::GetOpcodeCyclesForWrite(BYTE reg)`.

**Internal:**
The 6502 byte sequence at $5083 is: 8e 91 d2, and AppleWin is detecting the 8e (STX ABS16) as the 6522 access, instead of 91 (STA (zp),Y). This doesn't match a sanity check at the end of the function so it ASSERTs.

---

Here's the code to clean-up the 6522's on Jukebox exit:

```
5076:78         SEI                               
5077:A0 0E      LDY #$0E
5079:A9 00      LDA #$00                          
507B:91 D2      STA (HGR.DY),Y C483:00
507D:88         DEY                               
507E:C0 04      CPY #$04
5080:B0 F9      BCS $507B
                ;
5082:A0 8E      LDY #$8E
5084:91 D2      STA (HGR.DY),Y C483:00
5086:88         DEY                               
5087:C0 84      CPY #$84
5089:B0 F9      BCS $5084
                ;
508B:AD E0 4E   LDA $4EE0      4EE0:00
508E:AE E1 4E   LDX $4EE1      4EE1:00
5091:8D FE 03   STA IRQL       03FE:6C
5094:8E FF 03   STX IRQH       03FF:59
5097:58         CLI                               
```

Loop: Y = {$E,...$4}
- $E: C40E (IER) = 0x40 (ie. T1 Int Enabled), but writing 0x00 doesn't clear this (to clear bits, you need to write with b7=1).
-  :
- $5: Writing to C405 (T1H_COUNTER) will arm the counter (with 0x0000), and then it'll assert IRQ (IFR.b6=1) on the next opcode when T1 underflows.
- $4: Writing to C404 (T1L_COUNTER) will clear the IRQ (IFR.b6=0), due to the false read of STA (zp),Y!

But basically this function does its job:
- On entry: T1_COUNTER.w=$2095 and ACR=$40 (T1 free-running mode)
- This loop:
   - Y=$B: sets ACR=$00 (T1 one-shot mode)
   - Y=$5: sets T1_COUNTER.w=$0000
     - which immediately underflows, de-activating the T1 counter, but asserting T1 interrupt.
   - Y=$4: clears the T1 interrupt

**Comment by roughana** [comment]
I just retried it to confirm my first impression. Johncat, Turkey, Smokey, Polka & Solace also start softly for me.On 14 Oct 2024, at 1:20 am, TomCh ***@***.***> wrote:﻿
In trying to repro this (using a debug build of AppleWin), I get an ASSERT when exiting the Jukebox in SY6522::GetOpcodeCyclesForWrite(BYTE reg).
Internal:
The 6502 byte sequence at $5083 is: 8e 91 d2, and AppleWin is detecting the 8e (STX ABS16) as the 6522 access, instead of 91 (STA (zp),Y). This doesn't match a sanity check at the end of the function so it ASSERTs.

Here's the code to clean-up the 6522's on Jukebox exit:
5076:78         SEI                               
5077:A0 0E      LDY #$0E
5079:A9 00      LDA #$00                          
507B:91 D2      STA (HGR.DY),Y C483:00
507D:88         DEY                               
507E:C0 04      CPY #$04
5080:B0 F9      BCS $507B
                ;
5082:A0 8E      LDY #$8E
5084:91 D2      STA (HGR.DY),Y C483:00
5086:88         DEY                               
5087:C0 84      CPY #$84
5089:B0 F9      BCS $5084
                ;
508B:AD E0 4E   LDA $4EE0      4EE0:00
508E:AE E1 4E   LDX $4EE1      4EE1:00
5091:8D FE 03   STA IRQL       03FE:6C
5094:8E FF 03   STX IRQH       03FF:59
5097:58         CLI                               

Loop: Y = {$E,...$4}

$E: C40E (IER) = 0x40 (ie. T1 Int Enabled), but writing 0x00 doesn't clear this (to clear bits, you need to write with b7=1).
:
$5: Writing to C405 (T1H_COUNTER) will arm the counter (with 0x0000), and then it'll assert IRQ (IFR.b6=1) on the next opcode when T1 underflows.
$4: Writing to C404 (T1L_COUNTER) will clear the IRQ (IFR.b6=0), due to the false read of STA (zp),Y!

But basically this function does its job:

On entry: T1_COUNTER.w=$2095 and ACR=$40 (T1 free-running mode)
This loop:

Y=$B: sets ACR=$00 (T1 one-shot mode)
Y=$5: sets T1_COUNTER.w=$0000

which immediately underflows, de-activating the T1 counter, but asserting T1 interrupt.


Y=$4: clears the T1 interrupt

**Comment by tomcw** [comment]
@roughana - In terms of the issue you reported (first bar has low volume) I think this is just a characteristic of that 1st song "SAMBAMAN". Those first few notes have a distinct envelope (volume shape) that starts low, and quick drops to 0.

I ran AppleWin with a cmd line option to output the Mockingboard audio to a .wav file, eg:
```
> AppleWin.exe -wav-mockingboard bsmw.wav
```

And I used Bank Street Music Writer's "Album" mode to play through all the tunes (but I hit RETURN after ~5s to skip to the next tune). Here's the resulting output (I used Audacity to export to .mp3, then renamed to .mp4 so I could attach to this issue)...

https://github.com/user-attachments/assets/8b094d25-08e1-4487-93d3-581f4e8eaa4d

This is how all the tunes sound for me... ie. none start softly except "SAMBAMAN" which is because those initial notes (on the left speaker) are intentionally soft (low volume) and quickly drop to zero volume.

**Comment by roughana** [comment]
Thanks for capturing your experience. This is definitely not exhibiting the problem I am hearing. I will see if I can capture similarly.

**Comment by tomcw** [comment]
>I will see if I can capture similarly.

Yes, if you can try the above command line to capture the Mockingboard audio output and attach it here (btw, you can just zip up the .wav file and attach directly).

**Comment by roughana** [comment]
I captured the first two bars of most of the songs from the jukebox.
[bsmw.zip](https://github.com/user-attachments/files/17445237/bsmw.zip)

**Comment by tomcw** [comment]
Your .wav output sounds the same as mine.

And I compared my .wav output for the "Smokey" tune against yours, and the 16-bit audio (.wav) values are near enough identical (only the odd byte difference every ~280 bytes - probably due to clock aliasing effects for the AY emulation).

One thought I had was perhaps your Mockingboard volume isn't set to the highest value in AppleWin's "Sound" tab, eg. move the slider up to the top, like this:

![image](https://github.com/user-attachments/assets/316b8316-7ef9-437a-a7d9-4734d7d9c6f5)

(NB. This volume setting has no affect on the output with the command line switch `-wav-mockingboard bsmw.wav`.)

**Comment by roughana** [comment]
Hmmm, I have played back the WAV on another machine and agree that the level is the same.
However, the WAV definitely sounds different on my Laptop. Not sure what is going on. I will check the volume setting, but I doubt this would impact the experience.

**Comment by tomcw** [comment]
>Hmmm, I have played back the WAV on another machine and agree that the level is the same.

OK - that's good that we have a common baseline.

>However, the WAV definitely sounds different on my Laptop.

What are the specs? Especially the type of audio/sound device?
(I doubt I can do anything about it, but good to know for future reference)
Also you could try updating your device drivers.

**Comment by tomcw** [comment]
@roughana - OK to close this?

**Comment by roughana** [comment]
Yes, ok to close.
