### ISSUE TITLE
Pooyan Freezes After "Player 1" Prompt

### ISSUE THREAD

**Issue by trebor68** [AppleWin/AppleWin#206]
After starting a game of Pooyan, once "Player 1" displays on the screen, the game freezes.  Tested on AppleWin 1.18.0 thru 1.24.0 with the same results.

Disk images utilize:
1. "VOL 254" - Mapple - Spectre  - Pandora's Box - Pooyan - Pooyan Cheat
2. "Beautiful Boot" - Dung Beetles - Ms. Pac-Man - Pooyan - Star Cruiser - Star Thief - Invasion Force

Both yield same results with Pooyan.

**Comment by sicklittlemonkey** [comment]
Just a note that this topic came up again in the Facebook Apple II Enthusiasts group, and there are more screenshots. Scott Eliot even swapped one RAM chip and part of the pattern changed. https://www.facebook.com/groups/5251478676/posts/10163661737933677/

**Comment by tomcw** [comment]
Thanks Nick, but I can only see the original post and 3 comments (even though it says there are 28 comments)... obivously the limitation of not having a FB account :-/  If anything else interesting pops up then feel free to copy it in here (or insist I get an account... which I'm unlikely to do! : - )

**Comment by sicklittlemonkey** [comment]
Here are the interesting 7M LORES examples posted by [Scott Elliott](https://www.facebook.com/groups/5251478676/user/1381181185/) about this behaviour.

1. Here's how it appears on an Apple //e with TMS4164-20NL (Texas Instruments), seven dated 8237 and one dated 8723. Odd addresses are 1s, even addresses are 0s. (Those 7MHz lo-res artifacts occurred because RESET was held continuously.)
![image](https://github.com/AppleWin/AppleWin/assets/4393005/739d294d-e3af-4bd2-b792-6dc1f7cf59f6)

2. [...] you inspired me to swap the RAM chip at F13 (D7 bit) with a Motorola MCM6664-20, dated 8224. The Motorola chip is divided into blocks of 256 consecutive 1-bits and 256 consecutive 0-bits, and the pattern flips every 4096 bits. When paired with TI chips in the other seven sockets, the Motorola chip adds weird horizontal patterns to the vertical stripes.
![image](https://github.com/AppleWin/AppleWin/assets/4393005/403af531-d3f1-4617-8bc7-c714296266e2)

**Comment by tomcw** [comment]
Thanks for re-posting this info/images here. Good to keep all these images together here.
