### ISSUE TITLE
Support FDI and EDD image formats

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#281]
On 20th April 2015, Steve Nickolas on cea2 asked:

Is there any possibility that disk formats more advanced than NIB could be supported in AppleWin? 

A lot of stuff's going up in formats like EDD and FDI, and if anything at all can use them it's usually only stuff for Macintosh.

**Comment by tomcw** [comment]
On 25th April 2015, P Hagstrom on cea2 commented:

I took a quick look at the AppleWin source, not enough to understand it deeply, but it appears that nibbles are the basic representation of disk data within the program.  What the EDD files are representing are the bits that are coming into the sequencer, so in particular they represent the leading zeros that get ignored (that is, 10101011 00 10101011 just gets read as the nibbles AB AB, because the two zeros in between are ignored, but this kind of timing can be important for copy protection schemes).  The EDD file would contain 101010110010101011 and a nib file would just contain ABAB.  (The relevant type of FDI file has the same information, FDI is just an alternative container format.)   So, to get this into AppleWin, there'd need to be a representation of how many leading zeros there are before each nibble, and then polling $C08C would need to wait the appropriate number of cycles before returning a valid nibble (and should also be getting the incoming bits shifted into it). 

There are a couple of other current points of frustration in the domain, I think I posted about it here not long ago, but in brief: the EDD files are generally created with Brutal Deluxe's I'm fEDD Up program, which records about 2.5 revolutions of data per track.  Due to idiosyncracies of the Disk II controller, it is not guaranteed that each read provides exactly the same bits, making it hard to determine with certainty where in the data stream a single revolution has completed.  Related to that, there's no indication of where the head is relative to the index hole, making it impossible to reliably synchronize tracks.  MESS has implemented .EDD reading, but at present it just guesses at a revolution's-worth of bits and then chops the data down just to one revolution, and the success rate is not stellar.

OpenEmulator can use the .FDI files and doesn't try to locate the track, but just blindly reads until the track runs out of bits, and that tends to satisfy more copy protection schemes (since if the first revolution recorded the bits incorrectly somehow, the second pass might have them in the configuration the protection scheme wants).  These EDD files also usually contain a read of every quarter track at least between tracks 0 and 34, and sometimes up to track 35. 

Apart from that, though, the format is very straightforward, it's just bits that get read into the sequencer.  So, you can just slurp up the bits until the high bit is set, and that's a nibble, then wait around until another 1 appears, and start collecting the next nibble with that as the bit that will eventually be the high bit.  Any zeros that occur after a nibble has arrived would cause a delay before the next nibble registers its high bit in the read switch. 

My guess from the very quick skimming of the code, though, is that this would require adding a data structure alongside the nibble stream that records how many leading zeros each nibble has, and then using that information to delay the appearance of the nibble in $C08C by an appropriate number of cycles.  Anyway, those are the off-the-top-of-my-head comments I had.

**Comment by sicklittlemonkey** [comment]
I agree the track data needs some processing. Ideally this would be done
outside the emulator!

The other way to slurp the bits is to actually emulate the sequencer. Isn't
this what MESS has done? (Not sure about OE.)

Cheers,
Nick.

**Comment by buricco** [comment]
You can blame me for broaching the topic over on cea2. >:P

I don't know if current GIT versions of MESS are supporting EDDs properly but some of the weird ones, like ones with half tracks or ghed forbid spiral tracking, will lock up the emulator when you try to insert them, so at this point I have *no* emulator I can use for the weird stuff.  (I prefer AppleWin anyway because of its debugger.)

**Comment by JohnMBrooks** [comment]
Hi guys. I'm a longtime Apple II dev who has done custom disk formats for my A2 games and am currently working with Brutal Deluxe on fEDD-Up v2. I think v2 track data should be a bit array for each track, sync'd with neighbor tracks. Each virtual disk should include drive rotation speed since it affects track length needed for nibble counting prot schemes. -JB

**Comment by sicklittlemonkey** [comment]
Hi John.
​
Thanks for commenting here. That's great news, and I look forward to seeing
what you come up with. AppleWin will definitely support the next generation
disk format - when it's fully evolved. ; - )

A bit array probably makes the most sense since it simplifies emulation,
though a nibble format with separate timing bytes makes it easier to
manually inspect and modify the image. Obviously only specialized hardware
(like Cryoflux) is going to be able to image disks with long sequences of
zero though.

BTW, I enjoyed your interview with Matt Ownby. He didn't seem to know much
about disk protection. Maybe that makes for a better interview. ; - )

Cheers,
Nick.

**Comment by JohnMBrooks** [comment]
Yes bit array is appropriate for track image since mag flux changes on disk are binary and static. The problem with nibble format is that is a parsed/interpreted version of flux bits, so its not a good representation.

For example, my disk protection schemes on Tomahawk IIe, IIGS, & Rastan GS all wrote several $00 bytes into the large sync gap. The IWM would interpret those $00 bytes as random 0/1 bits with the high bit set on every returned byte even though there were no bits set on the disk.

Also the IWM can return values like $80, and $FF with 3 or 4 hidden zero bytes after. So it's messy trying to represent mag flux changes as IWM nibbles.

HTH,
-JB

**Comment by cbeust** [comment]
Has there been any progress on this issue? It would be great to support FDI or even EDD...

**Comment by Michaelangel007** [comment]
Not that I'm aware. :-/  We _really_ should support imfEDDup at some point.

* http://www.brutaldeluxe.fr/products/apple2/imfEDDup/

*[ ] EDD format
	       The most precise format. It contains data read from the 5.25" disk controller card
                before the Logic State Sequencer performs its magic.
                That means that data are read at a bit-level, it is a "simple" set of 1s and 0s.
	       Each phase contains $4000 (16384) bytes.
	       A standard $22 diskette (step 1 track) is 573,440 bytes long.

**Comment by sicklittlemonkey** [comment]
Well, the problems earlier in this thread still apply.

Mainly that you can't tell where a track starts and ends.

The only way to do that so far is to use a Kyroflux.
http://webstore.kryoflux.com/catalog/product_info.php?cPath=1&products_id=29

I haven't kept up to date with whether they've opened up their proprietary
data format yet.

Cheers,
Nick.

**Comment by rb6502** [comment]
MAME/MESS reverse-engineered the Kryoflux/SPS .IPF format after SPS repeatedly stalled on opening it up.  If I remember correctly they did grudgingly publish a spec after that, and then changed to a new closed format.

I hope to support EDD more comprehensively soonish, but that's @galibert 's domain.

@burlcco MESS (now MAME) has a very powerful debugger; if you knew that but miss some feature, please open an issue on our Github page.  We support per-system custom debugger commands, so Apple II-specific functions are not a problem.

**Comment by Michaelangel007** [comment]
AppleWin mentioned here as not support bit-streams:

In Search of the Most Amazing Thing; or Towards a Universal Method to Defeat E7 Protection on the Apple ][ Platform, Page 17, section "Apple for the Win, or Not."
http://pferrie.host22.com/papers/apple2_e7.pdf

**Comment by tomcw** [comment]
A could of updates on the .edd format (on Slack, applesauce channel) from John Morris & Antoine Vignau when asked:
>"Other than index-hole synchronization and smaller file sizes, what other benefits does the .woz format offer over the .edd format.  Also, why is .edd so large compared to .woz?"

John M:
>.woz is a “solved” format. Each track contains only the actual number of nibbles. Areas of the disk for weak bit protections and such are cleaned up so that they can be emulated properly. And it contains no data that doesn’t belong. An .edd files contains all quarter tracks if it was imager as such. Each track also contains 16384 bytes worth of data, it doesn’t try to make a track that is the correct length and therefore has a time jump and often a corrupted sector on each track. It was designed for imaging, not running under emulation.

Antoine:
> edd files are copies of the flux as seen by an Apple II with an edd card. It reads a phase more than 2 times. Reads are not synced because there is no sensor. There is no research in determining what 0s and 1s mean, whereas Applesauce reads a track more times, at a faster rate, so it grabs more variations of the flux. More over, phases are synced thanks to the sensor. Then comes the intelligence to transform the a2r into a woz image.
>edd is dumb and is discontinued due to its poor quality and reliability compared to Applesauce, and the author is [v]ery happy with that situation.
>edd is, by essence, closer to a2r than woz.

Given this point: _"It was designed for imaging, not running under emulation."_ and given the prevalence of woz images now, I'm considering closing this issue as "won't fix".

**Comment by sicklittlemonkey** [comment]
Seconded.

**Comment by tomcw** [comment]
Closing as "Won't fix".
