### ISSUE TITLE
Silent Service hangs during Mockingboard use

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#309]
During gameplay, after a report about destroyers firing on the submarine, the game sends data to the board and then waits for an interrupt to occur, but the interrupt never occurs, resulting in a hang.

**Comment by tomcw** [comment]
Hi, if possible, can you create a save-state file (.aws), verify that the bug is reproducible when restoring the save-state; and then upload it to somewhere that I can get it from (sadly you can't attach general binary files to these github issues).

**Comment by peterferrie** [comment]
> Hi, if possible, can you create a save-state file (.aws), verify that the
> bug is reproducible when restoring the save-state; and then upload it to
> somewhere that I can get it from (sadly you can't attach general binary
> files to these github issues).

http://pferrie.host22.com/misc/Silentservice.zip

This state has PC at the start of the polling routine.  That routine
will never return.
Further investigation suggests that the problem might be caused by the
polling routine being called recursively from within the IRQ routine.
So, the IRQ routine is requiring that a second interrupt occurs before
the IRQ routine exits for the first time.

**Comment by tomcw** [comment]
Thanks for the save-state file.

It's an emulation problem: the Mockingboard emulation was restricted to only allow timer interrupts from the 6522 mapped to $Cs00, and to ignore those from the 6522 at $Cs80.

The fix is simply to comment out the `SY6522_DEVICE_A` check in `StartTimer()` - which I will do for the next release.

A potential immediate workaround could be to select a Mockingboard type (eg. Mockingboard A or C) so that Silent Service uses the 6522 at $Cs00. But I don't know if this is possible or will have the desired effect.

**Comment by peterferrie** [comment]
> It's an emulation problem: the Mockingboard emulation was restricted to only
> allow timer interrupts from the 6522 mapped to $Cs00, and to ignore those
> from the 6522 at $Cs80.
>
> The fix is simply to comment out the `SY6522_DEVICE_A` check in
> `StartTimer()` - which I will do for the next release.
>
> A potential immediate workaround could be to select a Mockingboard type (eg.
> Mockingboard A or C) so that Silent Service uses the 6522 at $Cs00. But I
> don't know if this is possible or will have the desired effect.

Thank you.  Silent Service won't offer Mockingboard support at all if
$Cs84 doesn't respond, so we don't have a workaround except to not
select the Mockingboard when it asks.
