### ISSUE TITLE
6502 I/O access occurs early - on the cycle of the opcode

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#321]
I've been debugging an issue with the French Touch's "Ansi Story" demo where the NTSC/PAL detection routine(*) would fail about half the time. The knock-on effect is that right at the end (of side-2), the wrongly detected PAL mode will cause the video sync to wait another 50 scanlines, causing the DGR/TEXT80 to flicker.

The problem occurs when it reads (with the CMP opcode) from address $C019 (VBL) at vpos=261, hpos=64 (ie. the very last cycle of the NTSC frame!). The CMP abs opcode, 0xCD takes 4 cycles, with the read occurring on this 4th cycle, but the AppleWin code doesn't update the cycle count until the end of the emulated opcode, ie. **after** the call to `VideoGetVbl()`. So the read from $C019 indicates VBL is still active when it's not.

I've mentioned this before in #241, but I'm raising this new bug to specifically highlight this problem (which could be different to #241, as that appears fixed).

(*)  At AppleWin launch, set a BP at $F15F. The NTSC/PAL detection routine occurs very early on so only takes a few secs to run to.

**Comment by tomcw** [comment]
I've isolated the problem to this unit-test in 4b1341c.
In fact, there's a 1-in-7 chance (not "about half") of the NTSC detection routine failing, and the code wrongly detecting a PAL system.
Having played around with the 65C02 opcode for `CMP abs`, and on which cycle it actually does the I/O access, I can see that it doesn't really matter, and doing the I/O access on a different cycle just shifts the problem:
```
// The different variants of 65C02's CMP abs opcode:
//   CMP; CYC(4)         : Fails every 7th cycle, ie: 6, 13, 20, ...
//   CYC(4); CMP         : Fails every 7th cycle, ie: 2,  9, 16, ...
//   CYC(3); CMP; CYC(1) : Fails every 7th cycle, ie: 3, 10, 17, ...
//   CYC(2); CMP; CYC(2) : Fails every 7th cycle, ie: 4, 11, 18, ...
//   CYC(1); CMP; CYC(3) : Fails every 7th cycle, ie: 5, 12, 19, ...
```
I'll speak to the French Touch guys to see if there's a bug in their code, or I'm wrong. . .

**Comment by sicklittlemonkey** [comment]
Nice work.

I've always wanted to "microcode" an emulated 6502, so each cycle does the
appropriate thing.

The other way to fix this is to have a table with a value for th read cycle
for each opcode and use that where needed.

Anyway. I look forward to your update after discussing with FT! ; - )

Cheers,
Nick.

**Comment by Archange427** [comment]
Tom: on wich "CMP $ C019" are you talking about?

Here is the code from Ansi Story Source (for this part):
(note: nothing was modified, I just translated/added some comments)

```
; detection refresh rate (PAL/NTSC)
		LDA	 bMachine 	
.lp1	CMP VERTBLANK 
		Bpl   .lp1		; waiting end of current VBL

        LDA  bMachine	; (not needed but was here at this time ;)
.lp2	CMP VERTBLANK	; 
		Bmi   .lp2	 	;waiting end of current display

 ; => HERE BEGINNING of the VBL 
 ; (not always the first cycle of VBL but close enough for the use)

.BP		INC COUNT		; 6 ; increment "VBL counter"
		LDX #$09		; 							
.WL1 	DEX				; 					
		BNE .WL1 		; = 46 cycles
						; + 6 + 3 + 3 + 4 + 3 = 65 !		
		LDA bMachine	; 3
		LDA bMachine	; 3
		CMP VERTBLANK	; 4
		Bpl   .BP	 	; 3 ; loop if still VBL
		
		LDA COUNT
		CMP #71			; >= 71 so 50 HZ (VBL = 120*65 cycles)
		BCS .GO3
		
		LDA #01			; 60HZ (VBL = 70x65 cycles)
		STA bRefresh		
		JMP .GO4

.GO3	LDA #00
		STA bRefresh	; 50HZ (VBL = 120x65 cycles)
.GO4        ...
```
Both first loops (.lp1/.lp2) ensure that we are at the **beginning** of the VBL when going after.
Code can not be accurate to detect the **exact** moment of entry into the VBL because of the problem that you describe (loop/CMP cycles) but this is not necessary here (and that's why I use other method when I  need more precision).

And that's why I check the counter by 71 (not 70) because sometime, one more loop of .BP is taken...

Finally that's how I understand this routine and I wrote it ;). 
And there may be something am I missing :)
But I do not understand how it can fail half the time.
Moreover in my tests, this was not the case. I struggled enough with credits part's routine in ANSI Story to test and test again so this detection routine was launched hundreds of times I think :)

Important note: I don't have a real NTSC Apple IIe (only PAL). So all my tests on NTSC machine were done with an Apple IIGS (in 60Hz mode of course). 

Second important note: I just noticed that since Crazy Cycles I, I use CMP #72 (no more #71) to check the counter... I do not remember exactly why but I probably realized that sometimes 71 was not enough (empirical observation probably).

=> Third important note: I just tested Ansi Story with AppleWin 1.26 NTSC Alpha v17 (modified for accurate cycles for some instructions) and you'r right, detection routine fails half of the time!
I think I use CMP#72 as a work around about this problem for CC and CC2...

But on a real machine, I'm pretty sure Ansi Story detects refresh rate correctly.
Especially at that time, I did a lot of tests on real machine (NTSC/PAL) as there were no emulators that emulating correctly VBL/display timing...
The routine can not screw up half the time on a real machine, I'll notice it.

Last important note: My english is not very good. I apologize in advance if the turn of phrases and words used may seem "aggressive" or condescending. It is not my intention. I am very far from being able to program myself an emulator. So I do not give lessons to anyone!
And for informations, all of my releases/demos are probably full of bugs ;)

**Comment by tomcw** [comment]
Thanks for the great detail.

I assumed you hadn't done much NTSC testing because (like me) you are based in Europe... but I was wrong.

Could there be a subtle difference between a real IIGS (60Hz) and real //e (60Hz)?

I wonder how Ansi Story's NTSC/PAL detection routine works on other emulators?

Sorry for the short reply. I won't be able to give a proper full reply for a few weeks now. But given the level of testing you've done on both NTSC and PAL machines, I'm now suspicious that AppleWin has the problem (but I don't  know what yet!).

Btw. Your English is perfectly fine & understandable. I appreciate it may be more time consuming to write in English, so thanks again for the long comment and no need to worry :)

**Comment by Archange427** [comment]
OK I just did some tests with AIPC (in 50 and 60Hz mode), AppleWin 1.26 NTSC Alpha 17 (modified) and MAME (last prebuild version).
I didn't use Ansi Story for the tests but another disk with the same detection routine of the refresh rate (much more convenient because this program displays refresh rate result so no need to check variable in memory, easy with AppleWin but a little trickier with others).

I tested with CMP 71 and CMP 72 code in the routine (as explained in my previous post)

So, I launched the disk a dozen times for each emulator.
Here the result:

- AppleWin : 
* CMP72 - ALL OK (60 Hz detected)
* CMP71 -1 out of 2 failed (as Ansi Story)

- MAME:
* CMP72 - ALL OK  (60Hz detected)
* CMP71 - ALL FAILED !!! (50 Hz detected)

- AIPC:
* CMP72 - ALL OK
* CMP71 - 1 out of 3 failed to detect 60Hz

Conclusion: 
- AppleWin seems not to be the guilty! (Or maybe not more than others ;)
- my tests on real hardware (IIGS/60hz mode)  were biased for some reasons (probably by myself).
- I don't understand why 72 is OK and not 71! I used this value by empirical deduction but honestly, I don't know why 71 is not working. In fact, I think that 70 would be working too!

I hope that these tests will have helped you. And I'm sorry that my previous message could imply that AppleWin was the "guilty" ... It's clearly not the case.

We can be satisfied with a result that works (like the 72 value) but I confess that if I really like the Apple II, it is because we have the possibility (and the feeling) of controlling all the parts of the machine "at the bit and cycle level" (disk II, display, cycles counting, etc).
But that's not the case here!

**Comment by sicklittlemonkey** [comment]
Can you supply a disk image? I can test on PAL & NTSC //e's (and //c, IIgs).

And I wrote the original MAME and AppleWin video scanner/floating bus
emulation code. ; - )

Cheers,
Nick.

**Comment by Archange427** [comment]
Nick (and Tom), you can download two versions here:

http://www.ctrl-pomme-reset.fr/test/CMP71.dsk
http://www.ctrl-pomme-reset.fr/test/CMP72.dsk

As their name suggests, one use CMP#71 to check the counter and the other 72.

Oh (as you will see), AppleWin fails to detect correctly ZipChip (false positive).
This has nothing to do with our problem here but I included this routine at the request of a friend and I realized that under AppleWin, it was not working properly. 
I mention this because it will be displayed on the screen...

**Comment by sosaria7** [comment]
The last loop of .lp2 consumes 6 clock not 7 clock.
If VBL starts at the exact .lp2 position, there is one more clock to VBL end at comparing VBL end.
So, loop occurs one more.
I think this is the reason the emulators sometimes loop one more time.

**Comment by Archange427** [comment]
sosaria7: in fact, I don't count any cycles from lp2. 

I count cycles only from .BP to  get exactly 65 cycles (1 line).
If VBL begin exactly at the CMP VERTBLANK (in lp2) or if one more loop is taken because VBL begins immediately after this CMP doesn't matter.... 
When .BP begins, if we are during VBL since 6 cycles (min) ou 12 cycles (max) doesn't matter....
Only counts the number of times you will have covered 65 full cycles (=1 line). 

And that why I don't understand why CMP#70 does not work at all because at the end of the 70th loop, when CMP VERTBLANK occurs, we are  necessarily during display, not VBL...So loop would not be taken...

I obviously feel that I am not clear at all ;)

**Comment by sosaria7** [comment]
At the CMP VERTBLANK in .BP, 58 cycles in loop is used but 7 cycle is not used yet.
but 6 cycles to 12 cycles are used in .lp2 before .BP.
if 6 cycles is used after VBL in .lp2,
At the position of CMP VERTBLANK in BP,
  before .BP : 6
  at CMP BP : 58
  after CMP in BP : 7
so, 6 + 58 + 7 + 58 + 7 + 58 + 7 + .... 58 (70th CMP) + 7
= 6 + 58 + (7 + 58) * 69 + 7 = 4549 + 7
4549  is less than 4550

**Comment by Archange427** [comment]
sosaria7: you are absolutely right! So mystery for 70 value solved.
In fact, I never used 70 in my code because it was not reliable (and you explained why).

And the real issue now concerns 71.
CMP70 should work sometimes. Not if .BP begins after 6 and 7 cycles in VBL but should work for others values from 8 to 12.
But CMP71 should always work, right ?! So emulators (all ?!) issue ?
or there is still something else that comes into play...

**Comment by sosaria7** [comment]
Archange427:
        LDA COUNT
        CMP #71         ; >= 71 so 50 HZ (VBL = 120*65 cycles)
        BCS .GO3
0~70 (CF=0): NTSC
71~ (CF=1): PAL
But sometimes the count is 71 in NTSC for the reason I mentioned.
Isnt' it right?

**Comment by Archange427** [comment]
sosaria7: got it! 
Sorry not very awake this morning ;)
I was focused on the main loop...
Thank you :)

**Comment by Archange427** [comment]
And also forget that comment "_AppleWin fails to detect Correctly ZipChip (false positive)._".
-> issue with my code!
Hey! ... when I said that there were bugs everywhere ;)

**Comment by tomcw** [comment]
Thanks everyone (@sosaria7, @Archange427) for your help in getting to the bottom of this issue.

NB. [Ansi Story](http://www.ctrl-pomme-reset.fr/wp-content/uploads/french_touch/AS-S1.dsk) has now been updated to do `CMP #72`.
