### ISSUE TITLE
no screen updating in 1.26.0.6 + debugger

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#363]
Using Color Monitor enabled in enh IIe mode, and trying to run code from within the debugger (e.g. g 801).
The screen freezes after the Apple II logo, even though activity is really happening behind the scenes.  Upon entering and leaving the debugger, the screen is updated to the current view but is then frozen again.

**Comment by tomcw** [comment]
Hi, thanks for reporting this.

NB. With AppleWin 1.26, the video is updated after every debug single-step operation. This gives a cycle accurate video display, but means that the debugger's `g` command runs much slower than in 1.25. We should probably offer a way for the debugger to ena/disable the cycle-accurate video when debugging (NB. debug single-step is used by more than just `g` command, eg. `tf` too).

As an internal note, this broken code (now fixed by 7f3cc09) existed in 1.25, but this issue #363 was masked because when a video soft-switch was changed, then `VideoSetMode()` also called `VideoRedrawScreen()`.

**Comment by tomcw** [comment]
Fixed in release 1.26.1.0.
