### ISSUE TITLE
Cannot select Pravets 82

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#415]
A colleague of mine actually used a Pravets 82 so I wanted to show him AppleWin emulating the Pravets 82, but it cannot be selected, giving this error

"A specific clone wasn't selected from the Advanced tab"

The other clones work.

The reason is in this commit https://github.com/AppleWin/AppleWin/commit/749e1514bde23fd025cc5cf7d60a7767e5f4cc22 for Common.h

This is the enum eApple2Type

				// Clones start here:
					A2TYPE_CLONE=APPLECLONE_MASK,
					A2TYPE_PRAVETS=APPLECLONE_MASK,
					A2TYPE_PRAVETS82=A2TYPE_PRAVETS,	// Apple ][ clone
					A2TYPE_PRAVETS8M,			// Apple ][ clone

You can see that the value of Pravets82 is eventually the same as A2TYPE_CLONE which is forbidden in CPropertySheetHelper::PostMsgAfterClose.

The correct code should look like (I think)

				// Clones start here:
					A2TYPE_CLONE=APPLECLONE_MASK,
					A2TYPE_PRAVETS=APPLECLONE_MASK,
					A2TYPE_PRAVETS82,		// Apple ][ clone
					A2TYPE_PRAVETS8M,		// Apple ][ clone

Unless you are worried that these values are persisted and should not be changed, in which case the Pravets82 should go at the end and get a new number.

**Comment by tomcw** [comment]
Thanks for the report & triage.

The enum `A2TYPE_PRAVETS82=A2TYPE_PRAVETS` (=A2TYPE_CLONE) was added on Apr 12 2016 in 749e1514bde23fd025cc5cf7d60a7767e5f4cc22 (as you point out above), so in release v1.26.0.3 (19 Sept 2016).

And the check for `A2TYPE_CLONE ` in `CPropertySheetHelper::PostMsgAfterClose()` was added on Oct 22 2016 in 2d61c75bb0b8349b61e1b2a224064ef71408cc0a, so first got released in v1.26.1.1 (17 Feb 2017).

>Unless you are worried that these values are persisted and should not be changed, in which case the Pravets82 should go at the end and get a new number.

Yes, this sounds like a reasonable solution.

NB1. A Registry key "Apple2 Type" with value of 256 (A2TYPE_CLONE) is allowed to be read on startup in  `LoadConfiguration()`. With AppleWin 1.26.1.1+ there's no way that this could have been generated, since the UI forbids this. So could only have been generated by AppleWin v1.26.0.3 - 1.26.1.0 (inclusive).

If we change the enum, then we must trap this 256 (A2TYPE_CLONE) at start-up, and convert it to the correct (new) value of A2TYPE_PRAVETS82.

NB2. The save-state persists the "Model" using a string, eg. "Pravets82", so it is not affected. But when (a model=Pravets82) is loaded then currently will write 256 to the Registry. If we change the enum, then it will write out the correct value.

So given these points, it still seems reasonable to just move Pravet82 to the end of the enum definition.

**Comment by tomcw** [comment]
Actually there is a gap in the eApple2Type enums after A2TYPE_PRAVETS8M where it then jumps to the //e clones, so I'll just put A2TYPE_PRAVETS82 immediately after A2TYPE_PRAVETS8M.

Possible compatibility scenarios:

1.  New AppleWin loads "Apple2 Type" of 256 from Registry:
  - Gets automatically converted to the new A2TYPE_PRAVETS82 value (258)
  - Update Registry with this new value
2. Old AppleWin loads "Apple2 Type" of 258 from Registry:
  - `LoadConfiguration()` lets this through as a valid value (since it's less than A2TYPE_MAX... the validation isn't perfect!)
  - But in `MemInitializeROM()` the `g_Apple2Type` doesn't match, so a dialog will pop up saying:
  - `Unable to open the required firmware ROM data file.
File: Unknown type!`
  - AppleWin will exit, but will have reset the Registry value to A2TYPE_APPLE2EENHANCED, so on the next launch of AppleWin it'll work fine, but using the default Enhanced //e.

**Comment by tomcw** [comment]
Tested by selecting all Apple2 types (regular & clones), exiting and then restarting AppleWin.

**Comment by tomcw** [comment]
I've pre-released a new AppleWin 1.26.2.4 version [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.2.4) that fixes this.
