### ISSUE TITLE
F2 to reset emulator from debugger and what to do with spinning disk drives

### ISSUE THREAD

**Issue by TommyGH** [AppleWin/AppleWin#460]
Note:  Originally I posted this in the closed issue #450, thinking it would "re-open" that issue.  Perhaps it is better to start another issue, so here we are.

Emulator: 1.26.3.0
Debugger: 2.9.0.8

Using F2 to "reset" the emulator does not reset the disk drives to inactive state.

If the intention for using F2 to "reset" the emulator is to make it more convenient than closing and restarting AppleWin, then what should happen with disk drives that are "spinning" when you press F2 while in the debugger?

Start AppleWin in AppleII+ mode
 Place a bootable disk in drive 1.
 F7
 bpr pc=801
 F7
 breakpoint hits
 drive 1 disk light is on
 F2 to reset emulation
 F5 to "swap" disks
 See a dire warning message about not swapping disks while the drive is still spinning.

Note, I think I opened an issue (#250) a long time ago about the disk drive light being on when it sometimes should not be on. I'm not sure if that complicates this issue or not.

**Comment by tomcw** [comment]
>bpr pc=801

btw. you can just use this shorthand: `bp 801`

**Comment by tomcw** [comment]
NB. Behaviour is ___the same___ for normal emulation or debugging (stepping):
- **F2**: Turns off drive motor, immediately stops drive spinning and turns off the drive activity LED.
- **Ctrl+F2**: Turn off drive motor, but drive continues to spin for ~1sec until it comes to a standstill.
  - this is now possible in debugging mode because #250 is fixed.

**Comment by tomcw** [comment]
FYI, new experimental release build 1.26.3.1 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.1), which includes this fix.
