### ISSUE TITLE
LDA $C500 freeze the debugger

### ISSUE THREAD

**Issue by MarcoVerpelli** [AppleWin/AppleWin#474]
Hello!
download:
https://archive.org/details/Ankh4amCrack
place a breakpoint @ B600, boot and look at the self modifing code.
LDA $C500 freeze the debugger and the emulator "go wild" without the breakpoint
(version 1.26.3.0)

Marco

P.S. the game don't work also with GSport. Mal comune mezzo gaudio. I left the translation to you :)

**Comment by tomcw** [comment]
Marco-

What card have you got in in slot 5?
The Z80 card definitely causes the emulator to "go wild", but others (empty, Mockingboard, SAM) should all be OK.

**Comment by MarcoVerpelli** [comment]
You are right, I forgot to have selected the Z80 card in slot #5.
I apologize,
Thank you

**Comment by tomcw** [comment]
Sadly the Z80 (CP/M) card switches from 6502 to Z80 when you write to $C5xx. I checked the 6502 code that does this (from the CP/M disks) and it's done with a write to $C500.

I did step through the code at $B600 and cross-referenced this with 4am's info about this in "Ankh (4am crack).txt". I noticed (as presumably 4am did too - see below) that even though I didn't have a card in slot-7 the floating bus was consistently returning $00.

Note from"Ankh (4am crack).txt":
```
(Fun fact: this check fails in some
modern emulators, because they emulate
non-existent cards by filling the slot
ROM with #$00 bytes which triggers a
false positive here.)
```

When the code at $B600 is running, the drive motor is on. For AppleWin this puts the emulator into "Full Speed" (unthrottled) mode. When in this mode, then the video emulation is not accurate. In fact the scan position just remains static. Since the scan-out is for HGR page1 and this is mainly zero bytes, then the floating bus will (be more statistically likely to) just return a fixed value of $00.

Anyway this "inaccurate video when at full-speed" limitation is harmless in this Ankh case, as 4am has patched this routine at $B611 to do a harmless BIT $B6D5 instead of JMP $B6D5.

**Comment by tomcw** [comment]
This "inaccurate video when at full-speed" limitation isn't documented, so I raised #477 for this.

I'm closing this issue as invalid.

**Comment by tomcw** [comment]
>When the code at $B600 is running, the drive motor is on. For AppleWin this puts the emulator into "Full Speed" (unthrottled) mode.

FYI: If you select Configuration->Disk, "Disk Access Speed = Authentic Speed", then this prevents the emulator _implicitly_ switching to full-speed mode when the drive on.

Now when you step the code at $B600, then you'll see non-zero values for the I/O reads.

Again, there's no need to do this, since 4am has patched the JMP with a harmless BIT.

**Comment by tomcw** [comment]
(closing)
