### ISSUE TITLE
Does it support IIgs?

### ISSUE THREAD

**Issue by pluto439** [AppleWin/AppleWin#491]
I'm trying to get The Immortal to work.

**Comment by sicklittlemonkey** [comment]
No. AppleWin is an Apple II, II+ and //e emulator.

For the IIgs you should try GSport or GSplus.
http://gsport.sourceforge.net/

Cheers,
Nick.

**Comment by pluto439** [comment]
Can I ask a bit of your time and see if you can manage to get this game running? I'm not sure where else I can contact people who even know what //gs is. It's a good game btw, but quite hard.

I downloaded game from here http://www.whatisthe2gs.apple2.org.za/immortal-the , it's in .2mg files. I managed to get this game somewhat running in the ActiveGS emulator, but character kept going in one direction for some reason. I loaded first disk into the s5d1 and restarted, after a while the "insert graphics disk" appeared, and I just kept changing disk and everything worked, almost.

I just tried GSport, it says "you must select a valid rom file" when I mounted it into s5d1.

I also tried compiling kegs 0.91 on windows, it threw a bunch of "overflow_sz:" errors on me when I tried to mount an .2mg . These errors are from src/iwm.c/disk_nib_out, maybe kegs doesn't understand 2mg format? There is no mention of it in README.kegs.txt. I modified a few things just to compile it, I'll tell them if required (if you'll try to compile it too).

I have a few questions, like is any os required to run this game, or just firmware (ROM.03 file) is enough?

Also, how to completely unmount an image from kegs? Pressing "e" results in rom name changing to start with "#" symbol, this is supposed to symbolise that floppy disk was removed it seems. But how to completely remove it, and if it's even necessary?

**Comment by pluto439** [comment]
Okay, nevermind, got this game running. Took me years, lol.

**Comment by sicklittlemonkey** [comment]
Sorry, I had a quick look, and saw the same joystick problem with GSport.

What did you do to fix the joystick?

BTW, the best places for general Apple II support are the Facebook groups
(Apple II Enthusiasts, Apple IIGS Enthusiasts) and Usenet groups
(comp.sys.apple2 etc and comp.emulators.apple2).

ROMs for machines and games are at ftp://ftp.apple.asimov.net/pub/apple_II/

Cheers,
Nick.

**Comment by pluto439** [comment]
F4 to open options -> Joystick Configuration
Joystick Emulation = Keypad Joystick
Joystick Trim X = -6
Joystick Trim Y = -6

Other people fixed it by simply calibrating their joystick, which I haven't figured out how to do.

This probably has something to do with how original hardware worked. I wonder if I'll have to change those for every game I'll try.

Also carefully reading main page of whatisthe2gs and watching this video https://www.youtube.com/watch?v=KtxNu3V1jgw helped greatly. Used GSport, used ROM01 (renamed as ROM or ROM.01), disk with os mounted to s7d1, disk with "board games and rpg" to s7d2, both .2mg mounted to s5d1. I wonder why that game still asks for .2mg if it's already on that big disk.

I probably should try out mess emulator too, but it's pretty confusiing in itself.

Strange that you can't get those F4 options to open in ActiveGS, it's also kegs based.

**Comment by sicklittlemonkey** [comment]
Ok, yeah that's not right, the joystick should work out of the box without
trim.
I've done a bit of dev on GSport, so I'll have a look when I have time.
It looks like a GSport (Windows) bug rather than anything to with the
original hardware.

The game can be booted in slot 5 directly without another OS.
"PR#5" from "]" prompt or "C500G" from "*" prompt.

BTW, if you haven't built GSport, here's a recent build:
https://drive.google.com/open?id=0B3JBd-TShLlLLWpsT0dRSU5ZSzg

The old build on SF doesn't have the nicer (depending how you like it)
full-screen fix that I implemented years ago, and some other stuff.

The Immortal was a great game. I remember pulling an all-nighter to finish
it back in the day. ; - )
Enjoy!

Cheers,
Nick.

**Comment by pluto439** [comment]
I'll be curious to hear details. I'll try to compile GSport soon, and will look at svn from time to time.

Search for `g_joystick_trim_amount_x` and `g_paddle_val` in code, maybe it'll save some time. I haven't got further than that.

Where can I learn more about "PR#5" like commands? Also what's the difference between GSport and GSplus?

This review http://forbidden-siren.ru/index/immortal/0-64 is the main reason I want to play this game btw. It said that IIgs version is very different from others, and music in levels highlights what you will meet there. This review is in russian though, but maybe I could translate it. Not sure if my english is good enough though.

**Comment by sicklittlemonkey** [comment]
GSport pretty much compiles out of the box on Windows if you install Perl
and VS.

(And I wrote an Android app to emulate the paddles/joystick over IP a few
years back, so I used to be fairly familiar with the code.
I'm hoping to get that feature released in AppleWin this year. Mostly it's
for using a tablet to emulate a Koala Pad.)

GSplus is a fork of GSport (by Dagen Brock) that uses SDL. He has other
plans too - search YouTube.

Offhand I don't know a good summary of all the different command
environments. This site has a few summaries:
http://www.landsnail.com/a2ref.htm

All the old Apple II Reference, DOS 3.3 etc manuals are on archive.org or
here:
https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/

There is also a new user guide for sale by a member of the community:
http://macgui.com/newa2guide/

Again the groups I mentioned before are the best place to ask general
questions.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment]
> I'll be curious to hear details. I'll try to compile GSport soon, and
will look at svn from time to time.

Fixed in SVN, joystick_driver.c line 208.

You _need_ to play The Immortal with joystick, not numpad. ; - )

BTW, GSport should be moving to GitHub soon.

Cheers,
Nick.

**Comment by pluto439** [comment]
Did it really solve it? Because it still requires "Joystick Trim" for me. Can you send the compiled file to me, maybe I compiled it wrong.

Those "__CYGWIN__" and "_MSC_VER" in the source code are such a mess, I had to replace them with "_WIN32" to get it to compile, at random. I'm using mingw.

**Comment by sicklittlemonkey** [comment]
Sorry, I should clarify.​

What you're experiencing is likely some timing inaccuracy of GSport
affecting a custom paddle reading routine in The Immortal. Fixing the
accuracy of cycle timing in GSport is a task beyond the time (and knowledge
- slow RAM, fast RAM and ROM timing is different) that I have to
contribute, so trim is still needed for The Immortal.

However I'm assuming you haven't yet tested with a physical joystick, right?

Because the Windows joystick reading code was broken, and _that's_ what
I've fixed, since that's what I was testing with. So you can now use a real
joystick, but you'll still have to use trim for The Immortal - sorry for
the confusion.

It's a shame Will Harvey & co didn't use the firmware joystick routine,
because that works perfectly at even 8MHz etc, whereas their custom routine
would require different trim settings if you played the game at a different
speed.

BTW, GSport has now been rehomed at GitHub:
https://github.com/david-schmidt/gsport

Cheers,
Nick.
