### ISSUE TITLE
MockingBoard 6522 timer

### ISSUE THREAD

**Issue by dschmenk** [AppleWin/AppleWin#496]
In writing the MockingBoard sound driver for Lawless Legends, I've found that AppleWin's 6522 emulation fails to start Timer1 unless interrupts are enabled. I'm polling the IFR's Timer1 which fails to get set because of this code:

```
static void StartTimer(SY6522_AY8910* pMB)
{
//	if((pMB->nAY8910Number & 1) != SY6522_DEVICE_A)
//		return;

>> Why this?
>>
>>	if((pMB->sy6522.IER & IxR_TIMER1) == 0x00)
>>		return;
>>

	USHORT nPeriod = pMB->sy6522.TIMER1_LATCH.w;

//	if(nPeriod <= 0xff)		// Timer1L value has been written (but TIMER1H hasn't)
//		return;

	pMB->nTimerStatus = 1;

	// 6522 CLK runs at same speed as 6502 CLK
	g_n6522TimerPeriod = nPeriod;

	g_bMBTimerIrqActive = true;
	g_nMBTimerDevice = pMB->nAY8910Number;
}

```
Of course polling the IFR works fine on a real 6522.

**Comment by tomcw** [comment]
Hi - can you share the specific snippet of 6522 code for doing this polling?

I guess that this should work..?
```
LDA #0<<6	; t1 one-shot
STA $C40B	; ACR
LDA #0
STA $C404	; t1 counter.l
LDA #1
STA $C405	; t1 counter.h, clear IFR.t1 & start (countdown from 0x100)

LDX #0
loop:
  LDA $C40D	; IFR
  AND #1<<6	; t1?
  BNE t1_set
  INX
  BNE loop

error:
  BRK

t1_set:
  RTS
```

**Comment by tomcw** [comment]
Added test: https://github.com/AppleWin/AppleWin-Test/commit/549e0ffd844a951a0ef45d090abd3597ebd6b0d5

**Comment by tomcw** [comment]
Try this experimental build: [v1.26.3.2](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.2).

**Comment by dschmenk** [comment]
Hi Tom-

I’m running the 6522 Timer1 in continuous countdown mode, just as you would when generating interrupts with the MockingBoard. However, instead of interrupts, my code waits for the IFR bit for Timer1 to be set. It then resets it, does some processing, and repeats. Using your test above, it would like this:

t1_init:
LDA #1<<6	; t1 continuous
STA $C40B	; ACR
LDA #0
STA $C404	; t1 counter.l
LDA #1
STA $C405	; t1 counter.h, clear IFR.t1 & start (countdown from 0x100)

t1_wait:
LDX #0
loop:
  LDA $C40D	; IFR
  AND #1<<6	; t1?
  BNE t1_set
  INX
  BNE loop

error:
  BRK

t1_set:
  STA $C40D	; Clear IFR Timer1
  RTS


Unfortunately, the Experimental build doesn’t seem to work any better than the last release. I believe the code I pointed to in the issue seems to be the culprit, keeping the timer for starting if interrupts aren’t enabled. Thanks again for looking into this,

Dave…

**Comment by tomcw** [comment]
Hi Dave,

Yes, the MB emulation is really only sufficient for what existing games, etc are doing. Currently the last 6522 timer1 that's setup is the only one that generates interrupts and sets the IFR.TIMER1 bit. 

Other limitations:
- 6522 timer2 doesn't work (no interrupt, no IFR.TIMER2 gets set on underflow)
- 6522 timer1: only the last one setup from **both** MBs (in slot4 & slot5) will generate an interrupt and set the IFR.TIMER1 bit

I'll keep this issue open to fix things so that in non-interrupt mode, all timers can run simultaneously and set IFR.TIMERx on underflow.

**Comment by dschmenk** [comment]
Hi Tom-

So I'm now getting the interrupt flag for Timer1, however the timing is off a great deal. I'm guessing the culprit might be:

```
double MB_GetFramePeriod()
{
	return (g_bMBTimerIrqActive||(g_MB[0].sy6522.IFR & IxR_TIMER1)) ? (double)g_n6522TimerPeriod : g_f6522TimerPeriod_NoIRQ;
}
```
would something like:

```
double MB_GetFramePeriod()
{
	return g_bMB_Active ? (double)g_n6522TimerPeriod : g_f6522TimerPeriod_NoIRQ;
}
```
be a better test for MB activity? I'm not positive this is the problem, but it is one of the few places where timing gets affected by whether IRQ is enabled or not.

**Comment by tomcw** [comment]
Hi Dave,

IIRC, Music Construction Set (MCS) is the only Mockingboard playback routine not to use an interrupt.
I think MB_GetFramePeriod() is written to support MCS by using this constant value of `g_f6522TimerPeriod_NoIRQ` (= 1.023MHz / 60Hz).

I don't understand your comment: "timing is off a great deal", as the this should be happening:
- At 60Hz, main loop calls MB_EndOfVideoFrame()
- No timer IRQ being used, so call MB_Update(), which fills part of the sound ring-buffer
- So roughly this update will occur at ~4x the rate of your Timer1 countdown

Hmmm... because this 1/60s update is not in sync with your 1/16s update of the Mockingboard registers, then this could explain when you say "timing is off a great deal" - there will be long and short sections of sound as the two 60Hz and 16Hz acoustically beat.

Can I just check that you are only using one of the 6522 timers? (This just helps me come up with a solution.)

If you only use one timer, then I can probably just mimic the way the timer IRQ works, ie. update the sound buffer when the timer counter underflows. This gives a fixed-period update to the sound buffer (with the Mockingboard registers from the prior update, 1/16s ago).

**Comment by tomcw** [comment]
BTW. I checked MCS and that _does_ use an interrupt.
So I think the non-interrupt support is just for playback of continuous tones, eg. poking the MB registers directly from the monitor!

**Comment by dschmenk** [comment]
Cursory review of the 6522 emulation looks pretty straightforward and not obvious what the discrepancy could be. I've put together my sample code and test disk image. I can also make a video of what it sounds like on real hardware, if that would be of any benefit. Its in PLASMA, but it really doesn't do anything quirky, except for emulating 9 voices per PSG by time slicing the note table every 16th of a second.

https://github.com/dschmenk/PLASMA/tree/master/src/mockingboard

Even the difference between the 60Hz emulation update and my 16 Hz timer count wouldn't account for the wacky sounds. I might try a test case of just timing a few seconds with the 6522 without playing anything to see if that makes a difference. Thanks again for all your help.

**Comment by tomcw** [comment]
Here's a new build. Can you try this... [AppleWin1.26.3.3.zip](https://github.com/AppleWin/AppleWin/files/1408817/AppleWin1.26.3.3.zip)

**Comment by tomcw** [comment]
FYI, code changes are in a different branch for now (GH496-MB).
Main changes are:
- Add a new variable (g_nMBTimerDeviceForPolling) for when timer1 is started but:
  - IER.TIMER1==0 && ACR.RUNMODE==CONTINUOUS
- When Timer1 underflows then call MB_Update() - ie. update the sound buffer
- MB_GetFramePeriod() will return the correct period (0xF9C2 in your case)

So the MB emulation (when polling Timer1) now only calls MB_Update() on Timer1 underflow... which mirrors the regular interrupt case.

**Comment by dschmenk** [comment]
That's it! Working just like hardware.

Of course I just realized last night that I could have disabled interrupts on the 6502 and enabled them on the MockingBoard and perhaps skipped all this work. But, I really know a lot more about MockingBoard emulation than I did before...

Thanks for all your help and support,

Dave...

**Comment by tomcw** [comment]
Great - good to hear!

>Of course I just realized last night that I could have disabled interrupts on the 6502 and enabled them on the MockingBoard and perhaps skipped all this work.

Yes, but I wouldn't want you making design / implementation decisions based on poor emulation. Target the real hardware and get the emulators to keep up!

Is it OK to add your mbtest.po disk image to the [AppleWin-Test](https://github.com/AppleWin/AppleWin-Test) repo?
I need a regression test for this, otherwise emulation support may break in the future.

**Comment by dschmenk** [comment]
Tom - you can now find both a polled and an IRQ based disk image here:

https://github.com/dschmenk/PLASMA/tree/master/src/mockingboard

I had overwritten the previous mbtest.po with the IRQ version so I broke them out into separate images.

Lawless Legends thanks you!

**Comment by tomcw** [comment]
>Tom - you can now find both a polled and an IRQ based disk image here:

Actually both these disk images are binary identical - both using IRQs.
If you have time, could you build & resubmit the polling version.

Thanks.

**Comment by dschmenk** [comment]
Sorry about that. I've made sure the polled version is checked in: https://github.com/dschmenk/PLASMA/blob/master/src/mockingboard/mbtest-poll.po

**Comment by tomcw** [comment]
Thanks Dave.

Added test for mbtest-poll.po: https://github.com/AppleWin/AppleWin-Test/commit/476236bb7f2a7c3f7eb697f5ef7f79ad4564d8b4

**Comment by tomcw** [comment]
btw. I've built a slightly updated 1.26.3.4 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.26.3.4), just so that there's a proper release build with this fix in it.
