### ISSUE TITLE
CpuGetEmulationTime_ms and emulator speed

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#540]
Hi
I was trying to work out the emulator speed and found this function.
It is only used for debug purposes in Video.cpp DebugRefresh().

The problem is that this function does not agree with the rest of the emulator speed, as it truncates the clock frequency.

	const DWORD CLKS_PER_MS = (DWORD)g_fCurrentCLK6502 / 1000;

(line 513 of Cpu.cpp)

rounds the number of clocks per ms, so that the time returned by  CpuGetEmulationTime_ms() drifts away from g_nCumulativeCycles / g_fCurrentCLK6502.

But again, the function is not used.

Andrea

**Comment by tomcw** [comment]
I added that debug function a long time ago (probably many years ago). Thanks for highlighting it - but it should be removed, along with the dependent functions too.

For emulation speed, eg. to answer: _when running at full-speed, what is the effective machine speed?_

**Comment by tomcw** [comment]
... I'd use the `VideoBenchmark()` function, but change calls to `CpuExecute(const DWORD uCycles, const bool bVideoUpdate)` so that bVideoUpdate is passed as **false**.

This is more representative, since in full-speed mode, the video is only periodically updated.

**Comment by audetto** [comment]
Thank you 
I was adding Audio support to my project and realised the audio was drifting ahead of the emulator. I was using g_nCumulativeCycles / g_fCurrentCLK6502 in one place and CpuGetEmulationTime_ms() in the other.

**Comment by tomcw** [comment]
@audetto: can I close this issue now? (the old debug code has been removed)

**Comment by audetto** [comment]
Sure, but before I had a question about g_nCumulativeCycles.

What I seem to understand is that this variable is only accurate if one calls CpuCalcCycles() first.
So the pattern is 

1) CpuCalcCycles(nCyclesLeft);
2) use g_nCumulativeCycles

My questions are
1) why is the variable always called nCyclesLeft? It feels more like a nCyclesExecuted.
2) why this double layer to update g_nCumulativeCycles? Would it not be easier to update it directly in Cpu65C02() rather than updating the local uExecutedCycles? and then g_nCumulativeCycles is always accurate.

But I guess I am missing something.

Thank you.

**Comment by tomcw** [comment]
>why is the variable always called nCyclesLeft? It feels more like a nCyclesExecuted.

This is a hang over from a previous, much older version of AppleWin. This needs refactoring so that it's `nCyclesExecuted` for all cases.

>why this double layer to update g_nCumulativeCycles?

It's a "just in time" calculation of `g_nCumulativeCycles`, so that it's only calculated when it's actually needed. So when you need cycle-accuracy then you call `CpuCalcCycles()`. NB. Calling `CpuCalcCycles()` twice is fine, as for the 2nd call the cycle delta is zero.

>Would it not be easier to update it directly in Cpu65C02() rather than updating the local uExecutedCycles? and then g_nCumulativeCycles is always accurate.

Well after every opcode there's a `CYC()` where `ULONG uExecutedCycles` gets a few cycles added to each it opcode. ULONG is a 32-bit unsigned int, so it's 32-bit maths. AppleWin.exe is a 32-bit app, so replacing this 32-bit add with a 64-bit add will affect performance. If/when we switch to building as a 64-bit app, then this is worth testing.

**Comment by tomcw** [comment]
TODO:
- [ ] Change calls to `CpuExecute(const DWORD uCycles, const bool bVideoUpdate)` so that bVideoUpdate is passed as **false**.
- [ ] `nCyclesLeft` needs refactoring so that it's `nCyclesExecuted` for all cases.

**Comment by audetto** [comment]
Understood. Thank you

**Comment by tomcw** [comment]
Closing, since all todo items are done.
