### ISSUE TITLE
Support WOZ disk image format

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#544]
WOZ format v1.0 officially released on 17th Jan 2018:
http://evolutioninteractive.com/applesauce/woz_reference.pdf

>The WOZ format, the mainstay of the Applesauce project by John Morris, has been officially released. This new format for reading and writing Apple II floppy disks allows emulators to more accurately reflect the actual data on an Apple II floppy disk and disk image.

Ref: http://www.callapple.org/vintage-apple-computers/apple-ii/woz-format-updated-to-version-1-0-and-officially-released/

**Comment by tomcw** [comment]
Here's a short program that demonstrates my understanding of the .woz file format:
- It consumes the first 2048 bits (ie. 256*8 bits) from a .woz file
- It ignores the extra sync zero-bits (or generates random bits)
- And dumps the resulting hex nibbles

[main.txt](https://github.com/AppleWin/AppleWin/files/1939958/main.txt)

If I get some time, I may have a stab at supporting (initially read-only) .woz files.
(I'm just stating this upfront in case @sicklittlemonkey or @Michaelangel007 want to take this instead.)

**Comment by sicklittlemonkey** [comment]
We're still looking for a place to live, so I'm not biting off anything big
for the next month at least.

But you've been doing a lot recently Tom - great stuff!

Cheers,
Nick.

**Comment by tomcw** [comment]
Just a though on .woz testing...

In 4am's notes on cracking "Gertrude's Puzzles" ([here](https://ia800507.us.archive.org/18/items/GertrudesPuzzles124amCrack/Gertrude%27s%20Puzzles%201.2%20%284am%20crack%29.txt)), it might be worthwhile to write a short bit of disk][ code to replicate this "E7 bitstream" (+ a dedicated .woz image).

**Comment by sicklittlemonkey** [comment]
Yes, there will be a few interesting cases to test.

BTW, your program sums up the basic logic of the sequencer and transition
detection amplifier well. Shift bits, and generate spurious ones if there
are too many zeroes.

But the real-time specifics get a bit tricky eg:
- When the high bit is set then the sequencer loops while the latch holds
its value for seven cycles ... and longer if 0's come along (this is how
bit copy programs detect "sync bytes/nibbles")
- C08D resets the sequencer - used in the bit-slip (E7) protection
- Some of the sequencer code is redundant - namely that to detect zeroes,
since the bitstream is provided for us.

Anyway, the real question is how to shove bit-stream disk access into
AppleWin. ; - )

The existing disk code is, to use the made-up buzzword, performant, and it
would be a shame to lose that.

A simple way forward would be to convert all disk access to a bitstream
model, which IIRC is what MAME and OE have done.
So when writing nibbles from DSK etc or NIB to the buffer we can just
insert 0's after each nibble ... That should work.

One advantage would be that non-standard formatting can be written at any
time and then saved to WOZ images if necessary.
Perhaps this is the best way, since I think WOZ images will become the new
standard - closer to the behaviour of real hardware.

That said, DO, PO and NIB images are very convenient to inspect and edit,
though I suppose tools both in emulation and out could fill the gap for WOZ.

The problem with keeping both byte and bit-stream disk access is that
there's currently no convenient abstraction point in the code to switch
this.
As you can see with my points above, the soft-switch accesses change the
reading behaviour, so bit-stream changes are needed in the soft-switch code
(in the bit-stream case).

What are your thoughts?

Cheers,
Nick.

**Comment by tomcw** [comment]
>But the real-time specifics get a bit tricky eg:

I wasn't really aware of these things (I've not read Sather's explanation in detail yet).

>The existing disk code is, to use the made-up buzzword, performant, and it would be a shame to lose that.

Yes, I agree with that - we should strive not to lose any performance.

>A simple way forward would be to convert all disk access to a bitstream model ...

I was thinking the same. Currently all disk access is done at the nibble level (ie. .dsk/po etc are converted to nibbles tracks; and .nib images already exist in nibble track format). So the next step might be to "lower" (ie. convert) the nibble-format to the .woz bitstream model.

Specifically for converting from a .nib image file to an internal bitstream representation:
- ie. reading, (I think) AppleWin wouldn't need to insert any extra (zero/sync) bits, as all nibbles are already in sync.

And when writing (or formatting) using an internal bitstream representation, but using a .nib (or .dsk) file:
- ie. writing, AppleWin would now get a bitstream with extra zero-sync bits. These would just be lost when converting back to .nib format (and further lost when converting .nib back to .dsk format).

The advantage of just dealing with the bitstream model is it's just a single format that AppleWin deals with, instead of having to support both nibble & bitstream.

**Comment by sicklittlemonkey** [comment]
> I wasn't really aware of these things (I've not read Sather's explanation
in detail yet).

As I've mentioned to Michael, it's the "Theory of Relativity" (and perhaps
dry, but not _that_ difficult!) for the Apple II, so it's worth setting
aside a weekend to read. ; - )

> Yes, I agree with that - we should strive not to lose any performance.

Sorry for my half-formed thoughts, little time to think these days. What I
meant was that if we move everything internally to a bit-stream model, we
_will_ lose performance - unless we sprinkle the current code with
if/elses, or we introduce some polymorphic abstraction to maintain (fast)
byte and (slower) bit-stream internals.

Then again, the current disk access is almost instantaneous in fast mode.
Perhaps bit-stream won't be so bad after all.

> Specifically for converting from a .nib image file to an internal
bitstream representation:
> ie. reading, (I think) AppleWin wouldn't need to insert any extra
(zero/sync) bits, as all nibbles are already in sync.

This is unlikely to work, since sync nibbles exist for a reason. ; - ) If
we track position in the stream to the bit level, we could start reading at
any random (bit) location. The surest way would be to insert at least one
zero after every NIB nibble. You can be smart and insert zeros only after
FF's (and perhaps another case or two) for DSKs, but NIBs might be using
other sync values. This has always been the problem with trying to write
NIBs back to disk.

> And when writing (or formatting) using an internal bitstream
representation, but using a .nib (or .dsk) file:
> ie. writing, AppleWin would now get a bitstream with extra zero-sync
bits. These would just be lost when converting back to .nib format (and
further lost when converting .nib back to .dsk format).

Just so. One consideration - and another reason to put at least one zero
after each NIB nibble - is that that timing tricks (e.g. writing a sync
byte as part of the data field) takes extra space (only bits, but still) so
extra zero spacing prevents subsequent data from being overwritten.

Cheers,
Nick.

**Comment by tomcw** [comment]
>This is unlikely to work, since sync nibbles exist for a reason. ; - ) If
we track position in the stream to the bit level, we could start reading at
any random (bit) location.

Yes, I agree.
(I was thinking for the read-only case for .nib images we could always start the bit-stream at a nibble boundary, but there could be some code - like the E7 bitstream - where it skips a few bits. Anyway, th read-only case is no good either, so it's pointless exploring this further.)

>The surest way would be to insert at least one zero after every NIB nibble.

I see... using 9-bit sync (0-1111-1111) will sync on the 8th nibble (worst case), whereas 10-bit sync (00-1111-1111) will sync on 5th (worst case).

>What I meant was that if we move everything internally to a bit-stream model, we _will_ lose performance

Yes: 9 bits = 9x4us = 36 cycles
The nibble read loop is 7 cycles:
```
.loop LDA $C08C,X ; 4 cycles
      BPL .loop   ; 3 cycles (branch taken, no page cross)
```

Currently it takes: 4+2 = 6 cycles (or 2 opcodes) to read a nibble
With bit-stream it'll take: 36 cycles (on average) (or ~11 opcodes) to read a nibble.
- On average, as each nibble read won't take a constant number of cycles (from the 6502's POV), as the 1st will take 7+7+7+7+7+6=41cy (so 5 cycles into the next 9-bit nibble), the 2nd will take 7+7+7+7+6=34cy, as it the 1st nibble was 5cy over, etc.)

So time spent reading nibbles is 6 times longer (both in cycles and opcodes).
But how much of a % is spent reading nibbles vs. denibblizing, changing track and other house-keeping?

This should be easy to figure out (eg. using the AZTEC loading as a benchmark): just measure number of cycles to boot, and number of nibbles read.

But there's also the emulation cost: reading a nibble vs reading from the bit-stream + sequencer emulation. The % time spent reading nibbles should indicate whether this emulation cost _difference_ is that important (eg. if the % time reading nibbles is very low, then emulation cost _difference_ can be assumed to negligible).

**Comment by sicklittlemonkey** [comment]
Yes, a good summary. We can suck it and see: if the bit-stream performance
is noticeably worse, we can think about how to maintain a byte mode too.

We've found a place to live, so I can perhaps start to look into this in a
couple of weeks. If no-one beats me to it. ; - )

The likeliest starting point is struct Disk_t becomes a class ...

Cheers,
Nick.

**Comment by tomcw** [comment]
>We've found a place to live

Congratulations!

>so I can perhaps start to look into this in a couple of weeks. If no-one beats me to it. ; - )

Don't worry... it's interesting work, but I doubt I'll have time to commit to doing this soon.

>The likeliest starting point is struct Disk_t becomes a class ...

Yes. Ideally encapsulating the whole DiskII into a class, so that it's simple to instantiate into another slot.
btw. Recently I did split out some variables into a new struct Drive_t, so now Drive_t _has a_ Disk_t.

**Comment by tomcw** [comment]
Also, my comment above where I said:
>So time spent reading nibbles is 6 times longer (both in cycles and opcodes).

...isn't correct, since 6502 nibble reading code isn't in a tight loop just doing "loop: LDA $C08C,X / BPL loop", there's all the interleaved decode & store code too, eg:

```
C6A6:A0 56      LDY #$56
C6A8:84 3C      STY MON.A1L      ; 3 cy
C6AA:BC 8C C0   LDY DATASTROB,X  ; 4 cy
C6AD:10 FB      BPL $C6AA        ; 2 cy (+1 branch taken)
C6AF:59 D6 02   EOR $02D6,Y      ; 4 cy
C6B2:A4 3C      LDY MON.A1L      ; 3 cy
C6B4:88         DEY              ; 2 cy
C6B5:99 00 03   STA $0300,Y      ; 5 cy
C6B8:D0 EE      BNE $C6A8        ; 2 cy (+1 branch taken)

Total for loop = 26 cy (BPL not taken, BNE taken)
```

So probably the bitstream version is only an extra "LDY C08C,X; BPL loop", ie. an extra 7 cycles / 2 opcodes.

**Comment by tomcw** [comment]
One more thought (for the read nibble case) is AppleWin could just provide the latch with the complete nibble immediately.

Eg. for a bitstream at position: 00-1111-1111, then for a read of $C0EC, just return 0xFF immediately.

We could certainly do this if the source image file was .nib or .dsk.
Maybe only enable this for `enhancedisk=1` mode.
Maybe snoop the 6502 code and only do this for a `READ $C0EC; BPL -5` code sequence.

This means that there'd be no performance penalty for bitstreams (from existing .nib/.dsk images).

But for .woz images (certainly those which rely on the zero sync bits) then you wouldn't want to do this.

**Comment by Michaelangel007** [comment]
/Oblg. _"Why not both?"_ 

Could we extend the `Disk access speed` drop down list to include a 3rd option?

* Bit-stream Speed (slowest)
* Authentic Speed
* Enhanced Speed (fastest)

**Comment by sicklittlemonkey** [comment]
I think handling WOZ images is an orthogonal concern from the disk access
speed option.

The only way I can see "both" working is to abstract at the disk/controller
class level.

Cheers,
Nick.

**Comment by kerthunk** [comment]
I think that it all depends on what you are looking to get out of AppleWin. The bitstream speed is the "authentic" one. All Apple II software sits in that loop polling (LDA $C08C,X; BPL). When feeding bits every 4us, you are simulating the rotation of the floppy disk. Yes, you can just feed the next nibble every time there is a (LDA $C08C,X), but this speeds up the disk access while also not working even remotely how the actual hardware functions and will fail quite a few copy protection checks. Bits should be passing through the disk latch regardless of whether they are being accessed by the software.

**Comment by sicklittlemonkey** [comment]
Indeed, John. We've already tabled the idea of converting all disk access
to bitstream.

Then the disk access speed option would (like now) just select whether
emulation jumps to full speed during disk access. This is why I say (IMO)
it's an orthogonal concern.

Cheers,
Nick.

**Comment by kerthunk** [comment]
Having it in its own thread is going to give you sync headaches. The bitstream in the woz should be considered as being normalized to 4us each bit. You are best off to tie this to your cpu clock in order to prevent any drift and potentially lost bits. Then you can also tie your logic state sequencer to this clock as well (runs at 2MHz). Or even just tie the LSS to your CPU and have the LSS control the advancing the bitstream.

**Comment by sicklittlemonkey** [comment]
Yeah, this is not an issue. Just advance the bitstream position according
to (last_clock_cycle - current_clock_cycle). And really, if it's larger
than some arbitrary value (a revolutions worth of bits, say), then it can
just be reset if needed.

Cheers,
Nick.

**Comment by tomcw** [comment]
btw. WOZ Disk Image Reference v1.0.1 (May 20th, 2018) was released - there's no history, so it's hard to see what changed.

**Comment by kerthunk** [comment]
I have never come across a 41 track floppy disk. Even when it comes to 40 track disks, there are only handfuls of those. Personally, I wouldn't bother to support it as the initial reasoning for the request "Given the fact that all disk drive can access one more track than the suggested" is incorrect. Building support for 41 tracks would be on the table for me if there was some piece of software that actually came like that, but doing it just because it is theoretically possible is waste of time IMO.

But, if you wanted to support it, you could point to the TRKS data from TMAP position 40.75 (offset 159). Then just hack the emulator to allow tracks 41+, but it just caps the TMAP lookup to 159.

**Comment by tomcw** [comment]
Thanks for your feedback. If AppleWin were to support 41+ tracks, then I'd probably do it just for .dsk images - so not for .woz.

**Comment by tomcw** [comment]
Assigning to Nick, so that it's clear that he has taken this task.
NB. There's no expectation that he'll start anytime soon, just that he has shown some interest in this : - )

**Comment by tomcw** [comment]
Just saw this on reddit, [here](https://www.reddit.com/r/emulation/comments/acb002/2018_best_most_compatible_emulator_for/ed7alx1/)

> arbee37 - MAME Developer - 7 points - 8 days ago
>
>AppleWin's kinda getting left behind because it can't support WOZ/WOZ2 copy-protected originals without a significant rewrite. MAME supports them, as does OpenEmulator (Mac only) and microM8 (closed source but can do 3DNES type effects on Apple II games).
>
>MAME supports the largest number of Apple II expansion cards, including the TransWarp to run IIe stuff faster.

I didn't know about WOZ2 (Version 2.0 – December 16, 2018):
https://applesaucefdc.com/woz/reference2/

I don't know how valid this "left behind" statement is, but I just checked asimov, and there are only 32 .woz images there and 24 of these are for the Apple /// (which AppleWin doesn't support and we have no plans to support).

Anyway, .woz support is important (eg. to stay relevant & current), so one to bear in mind when any of us get a chunk of time to dedicate to this!

**Comment by sicklittlemonkey** [comment]
There are actually lots of Applesauce units out there, and lots of images.

From here:
https://wiki.reactivemicro.com/Applesauce#Preserved_Software
"March 10th, 2018 John Morris let ReActiveMicro know that close to 3000 disk sides have been imaged"

4am has been doing a WOZ a day series here - 175 so far:
https://archive.org/details/wozaday

Cheers,
Nick.

**Comment by kerthunk** [comment]
There are currently over 20,000 Applesauce imaged disks that I personally know of. There are currently a few hundred WOZ files out there, but I'm finishing up some new WOZ 2.0 exporting code that will opening up the gates for many more to be created.

**Comment by H82lose** [comment]
I think it’s great that Mame & Mess support Woz files. I was wondering how things are going with AppleWin in regards to supporting Woz disks ?

I hope it will available soon.

**Comment by tomcw** [comment]
Although we don't have a prioritised backlog, support for the WOZ format is probably the top item to work on next.

**Comment by tomcw** [comment]
I've built AppleWin 1.29.0.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.0.0), which supports WOZ images.

See #661 for images with known issues.

**Comment by MarcoVerpelli** [comment]
Now that there's support wouldn't it be possible to register the .woz extension with AppleWin?
I did it by hand but maybe others would prefer an automatic thing

Thank you
