### ISSUE TITLE
ProSel (Program Selector) 2.2 Mouse Text not flashing

### ISSUE THREAD

**Issue by phed001** [AppleWin/AppleWin#565]
On the home screen of PROSEL at the bottom, there are two mouse text apple at both end. These two apples suppose will change from open apple to close apple then to open apple then...
Attached a test disk image.
Tried this on Apple II Oasis http://apple2.emuunlim.com/DOWNLOAD.HTM
Also the online emulator https://www.scullinsteel.com/apple//e
[TEST.zip](https://github.com/AppleWin/AppleWin/files/2091544/TEST.zip)

**Comment by sicklittlemonkey** [comment]
Notice the other difference on this screen between emulators: the time is
not shown in AppleWin.
This is because the other two emulators you tried emulate a slot-based
clock like Thunderclock.
AppleWin emulates the No Slot Clock, not a slot-based clock card.

PROSEL is using the clock (if present) to time the changing of the apple
characters.
Specifically at $0F7C it does LDA $0210, which only changes when a
slot-based clock is activated.
(It has some code around that which checks a machine ID byte and ESC codes
for inverse etc.)

Cheers,
Nick.

**Comment by tomcw** [comment]
Nicely triaged, Nick!

NB. There is no issue/request for Thunderclock card support (although Michael(?) did put a ThunderClockPlus.rom in the resource folder).

I'm going to close this as invalid.
