### ISSUE TITLE
1.27.9.0 stops early while booting Ultima V .do image with the Authentic Speed disk access setting

### ISSUE THREAD

**Issue by rbrtck** [AppleWin/AppleWin#599]
Version 1.27.9.0 stops early while booting Ultima V .do image with the Authentic Speed disk access setting--before the second drive is checked.  Seems to work OK with the Enhanced Speed setting.  Previous versions including 1.27.8.0 work fine with either setting.

**Comment by tomcw** [comment]
Thanks for reporting this.
I've confirm this (and also that 1.27.12.0 fails in the same way).

**Comment by tomcw** [comment]
@sicklittlemonkey / Hi Nick,

The boot-strap code in Ultima V is waiting until reading the Disk II's data latch's returns the same value, ie. motor off, then wait until the drive has stopped spinning.

AppleWin ignores the spinning state.

For enhanced speed mode:
- if the number of cycles since the last latch read is <= 6 cycles then it returns a partial nibble.
- else it returns the next nibble, then moves the nibble pointer on by 1

For authentic speed mode:
- if the number of cycles since the last latch read is <= 31 cycles then it returns a partial nibble.
- else it returns the next nibble, then moves the nibble pointer on by 1

For the Ultima V case, the cycles between latch reads is 7,39,7,39,...
(So enhanced always returns full nibbles, but authentic alternates between partial and full nibbles.)

**Since the drive has stopped spinning, then shouldn't the latch read value be constant?**

But you also have a comment in the AppleWin's latch r/w code about Sherwood Forest:
```
// Should really test for drive off - after 1 second drive off delay (UTAIIe page 9-13)
// but Sherwood Forest sets shift mode and reads with the drive off, so don't check for now
```
So I want to ensure that any fix also takes this comment into account.

**Comment by sicklittlemonkey** [comment]
Hi Tom.

Wow, the corpus of Apple II software really does seem to test every edge
case of the machine! ; - )

Sherwood Forest turns the drive off & on again frequently. I don't remember
determining how often, but certainly not for longer than 1 second. (Most
likely it does it for every sector.) I put the comment there and didn't
check for drive off (and by that I meant the drive no longer spinning -
because of that one second delay) out of an overabundance of caution WRT
changing too much, and also perhaps not quite trusting the spinning
counter. But you use it in the code just above, and it just counts down to
zero, right? As you say, the latch value should be constant.

So the fix for Ultima while keeping Sherwood Forest in mind should simply
be:

// Should really test for drive off - after 1 second drive off delay
(UTAIIe page 9-13)
// but Sherwood Forest sets shift mode and reads with the drive off, so
don't check for now
if (!floppywritemode)
{

.. becomes:

// Don't change latch if drive off after 1 second drive-off delay (UTAIIe
page 9-13)
// Note: Sherwood Forest sets shift mode and reads with the drive off.
if (!floppywritemode && pDrive->spinning)
{

A similar change could also be made after the comment:
// . Should really test for drive off - after 1 second drive off delay
(UTAIIe page 9-13)
// but Gemstone Warrior sets load mode with the drive off, so don't check
for now

Cheers,
Nick.

**Comment by tomcw** [comment]
Thanks Nick - I (more or less) made the changes you suggested.

And found + added the Sather reference for drive off relating to the data latch:
"DRIVES OFF forces the data register to hold its present state." (UTAIIe page 9-12)

**Comment by sicklittlemonkey** [comment]
Thanks Tom. The DRIVES OFF references are a bit nebulous - there is no
DRIVES OFF signal, only DRIVE ON. DRIVES OFF refers to the softswitch, and
at other points DRIVES OFF is DRIVE ON' - the effect of the signal (low)
after the 1s propagation delay.

BTW, I don't think the latch will hold it's current value if in load mode
when the drives are off. It would be interesting to check.

Looking at the schematic (UTAIIe page 9-11) DRIVE ON' forces the 174
flip-flops to clear, which puts the sequencer "program counter" at 0. This
is NOP for shift mode, but Shift Right for load.

**Comment by tomcw** [comment]
Hi Nick,

>BTW, I don't think the latch will hold it's current value if in load mode when the drives are off. It would be interesting to check.

Yes, it'd be good to check that.

For reference the Ultima V boot code (that waits for the drive to stop spinning) is:
```
2194:
 LDA DATASTROBE,X ; $C0EC
 NOP
 JSR 2184
2184:
   JSR 2187
   RTS
   RTS ; execute RTS twice
219B:
 CMP DATASTROBE,X ; $C0EC
 BNE 2194
```

And I also checked "Sherwood Forest.nib" (from Asimov) which still works.
For completeness I temporarily re-instated the floppy motor off check (*) to see it failing to load too...
```
	if (!floppywritemode)
	{
		if (!floppymotoron) // (*)
			return;
```

**Comment by tomcw** [comment]
@rbrtck : there's a new build 1.27.13, [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.27.13) which fixes this issue.

**Comment by tomcw** [comment]
Added regression tests for Ultima 5 booting & Sherwood Forest here: https://github.com/AppleWin/AppleWin-Test/commit/843412f2922f4753417a4d86624df697bfbe9b1a.
