### ISSUE TITLE
What is the performance cost of checking 6522 underflow each opcode?

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#612]
In #608, Broadside's Mockingboard detection routine needed finer grain 6522 counter underflow detection than 128 cycles.

A more robust fix would be to check after each opcode, but what impact does this have on Full-speed emulation?

A more intelligent way to check underflow would be to determine when the next 6522 counter will underflow, and use this as the cycle check interval. NB. Each 6522 has 2 timers, and each Mockingboard has 2 6522's, and AppleWin currently supports 2 Mockingboards; so that's 8x 6522 timers.

**Comment by sicklittlemonkey** [comment]
I've meant to bring the following topic up before ... if I'm reading the
problem correctly.

This issue is a reminder of the overly simple architecture of AppleWin with
respect to timed events.
Multiple device update functions checking the current clock against
separate counters isn't flexible.

OpenEmulator and the recent CLK (and JACE I think) have a low-level
clock-based architecture which helps handle this.
Virtu which a friend and I worked on over 20 years (in assembly, then C++,
then C#) used an efficient event queue.
Presumably the above emulators (and perhaps JACE) might also have this. The
core loop counts down to the next event.
Events are scheduled into the queue by devices with a callback - e.g.
Joysticks can schedule strobe events etc.

Such an event queue might be the most efficient and easiest thing to
"retro-fit" (bonus pun!) into the CPU.
The deprecated device update functions might not improve performance much,
but you'd get the accuracy you need.

Cheers,
Nick.

**Comment by tomcw** [comment]
Yep - sounds like we're both describing the same thing, eg. an OS's kernel will have an ordered queue of hi-resolution timer events and only a single h/w timer for all of them. The h/w timer is just set to the value of the next one (ie. the next in the queue is the next count to expire).

We'd just need to check for underflow for the counter with the lowest value (after that number of cycles have executed). And the Mousecard's VBL can also be added to this ordered queue (but other "async" IRQ sources, like mouse button/movement & serial Tx/Rx can't be added).

We can handle "just in time" 6522 counter reads accurately too... actually this is already done by AppleWin (eg. the 6522 counter is only updated when a 6522 r/w access is done).

**Comment by tomcw** [comment]
#608 has regressed, so the priority of this one should be raised.

But to quickly answer this:
>What is the performance cost of checking 6522 underflow each opcode (in Full-speed) ?

I timed AZTEC booting to the key check. Current code (checking every 40 opcodes) takes ~706ms, whereas checking after every opcode take ~1145ms... so about 60% longer.

Time to fix this properly!

**Comment by tomcw** [comment]
After the merge of PR #841...

I re-timed AZTEC booting to the key check. Now the code (checking after _every_ opcode) takes ~692ms (mean of: 670,702,686,734,671). So about the same as the old 40-opcode way (above ~706ms), but now it's cycle-accurate at full-speed.

Another speed test is the benchmark: `Pure CPU MHz:	22.8 (video update)`
(mean of 22.8, 22.9, 22.8)

This is virtually the same as the old code (23.0 MHz) - see [here](https://github.com/AppleWin/AppleWin/pull/837#issuecomment-700254875).

NB. the NTSC video update (after every opcode) dominates the timing here - (see [here](https://github.com/AppleWin/AppleWin/issues/788#issuecomment-633092751)) - so probably expected that a small change to the CPU sub-system has a negligible **overall** effect.

Closing this issue.
