### ISSUE TITLE
Licensing information for the distributed master disk image

### ISSUE THREAD

**Issue by rzumer** [AppleWin/AppleWin#632]
I would like to know how the `MASTER.DSK` file included in release archives is licensed. I understand that there is practically no chance of legal issues related to Apple II disks at this point, but I would like to know if it is redistributable. If it is formally licensed and does not fall under the GPL, it would be helpful to have license text and/or information in the help files available.

**Comment by tomcw** [comment]
No, it's not licensed (formally or otherwise), so redistribution of this file is down to your interpretation.

**Comment by rzumer** [comment]
Was it compiled from the source code released in 2013? If not, can you share where it comes from?

**Comment by tomcw** [comment]
No... it was shipped with the original 1995(!) version of the AppleWin distro, and has never changed since:
https://github.com/AppleWin/AppleWin/issues/438#issuecomment-317171821

If you read #438, you'll see if is a slave (not a master) and `MSWAIT` has been patched, probably to speed it up under emulation. As you can see we do plan to replace this non-standard image with an official one, but just haven't gotten round to it.

**Comment by rzumer** [comment]
I see, sorry for missing that other issue and thank you for the answer. That answers my question, so I will close this one.
