### ISSUE TITLE
Some key combinations don't seem to be processed correctly

### ISSUE THREAD

**Issue by rzumer** [AppleWin/AppleWin#635]
I noticed that AppleWin is failing to process the extra man cheat keys in Lode Runner. The manual indicates that this is done with Ctrl+Shift+P, or Ctrl+Shift+2 on Apple IIe. Neither of these (when booted into the corresponding model) seem to work in AppleWin, though the level skip keys (Ctrl+Shift+6 on IIe) do.

I tested the same disk image on a [Web](https://virtualconsoles.com/online-emulators/apple-II/) emulator, and it works as intended, though I had to hold Ctrl+Shift on my physical keyboard and use the on-screen keyboard to press P in order to avoid spawning private windows, since this emulates a pre-IIe model and coincides with a key combination for the browser itself.

I use a mechanical keyboard, so there should be no concern with limited simultaneous key presses. I also tried using the OS's on-screen keyboard, to the same result.

All tested in versions 1.28 and above.

**Comment by sicklittlemonkey** [comment]
It works for me, but it might not for you depending on your keyboard layout.

Ctrl-Shift-P = Ctrl-@ = Ctrl-Shift-2 on my US keyboard. Where is @ on your
keyboard?
Ctrl-Shift-6 = Ctrl-^ = Ctrl-Shift-6 on my US keyboard.

I used this image:
ftp://ftp.apple.asimov.net/pub/apple_II/images/games/collections/san_inc_prodos/lode%20runner%20PRODOS%20(san%20inc%20pack).dsk


Cheers,
Nick.

**Comment by rzumer** [comment]
Ah, right. I don't use a US keyboard layout (Canadian French). I didn't think it would affect this in particular, sorry for the invalid issue. I wonder if it would be possible to have a setting that would override the user's layout, since it's easy to forget to switch when running AppleWin.

**Comment by sicklittlemonkey** [comment]
> Ah, right. I don't use a US keyboard layout (Canadian French). I didn't
think it would affect this in particular, sorry for the invalid issue. I
wonder if it would be possible to have a setting that would override the
user's layout, since it's easy to forget to switch when running AppleWin.

So did Ctrl-@ work on your keyboard in the game?

Cheers,
Nick.

**Comment by rzumer** [comment]
It does not, actually. `@` on a Canadian French layout is right Alt + 2.

**Comment by sicklittlemonkey** [comment]
Your issue is valid, so I'll re-open.

Tom has done some work on keyboard issues recently.
Perhaps there's a way to get it working.

**Comment by tomcw** [comment]
>@ on a Canadian French layout is right Alt + 2.

Hmm.. this sounds like #625.

If you are switching between versions of AppleWin, then between [1.27.6 and 1.28.2] inclusive I tried to improve the right-Alt (aka AltGr)+key support, ie. when AltGr is used as the Solid Apple key.

At 1.28.3 I reverted this change due to problems reported with international keyboards (but there's a switch to enable the 1.276-1.28.2 behaviour, ie. for US/UK keyboard users).

Anyway, can you try 1.28.3 (or higher) and check if "right Alt + 2" gives you an `@` symbol?

**Comment by rzumer** [comment]
It seems to work for direct input in the command line, but still nothing in Lode Runner.

**Comment by tomcw** [comment]
OK, I'm pretty sure it's this #583.

The problem is the duality of AltGr:

1. Used for Solid Apple (or button # 1)
2. Used to type a key (in this case the `@`)

Lode Runner's input loop will probably read $C062 (button # 1), do the dig left action then restart the loop. So it never gets the to the code to read the keyboard $C000.

To workaround this, tell AppleWin not to use Alt & AltGr for Open/Solid Apple keys using: `-no-hook-alt`.
Now you will have to use, eg. Joystick 1 = "Keyboard (numpad)", and use the `0` and `.` keys for Open/Solid Apple.

**Comment by tomcw** [comment]
>Lode Runner's input loop will probably read $C062 (button # 1), do the dig left action then restart the loop. So it never gets the to the code to read the keyboard $C000.

Confirmed using my UK keyboard:
- Hold down AltGr
- Then try to do CTRL+SHIFT+`@`  (for more lives)

The `more lives` cheat doesn't work.

**Comment by tomcw** [comment]
btw. I've added a note in the help doc about this: 78c9d893577eac2c0d11e976ef673668dd928706

**Comment by sicklittlemonkey** [comment]
Thanks Tom. It's great that you did that work so we can have a documented work-around.

**Comment by rzumer** [comment]
OK, seems reasonable. Thanks for documenting, closing again.
