### ISSUE TITLE
Card in slot 0 and preferences

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#645]
Hi,

I have just updated the Linux port and have a question about options to select the card in slot 0.

All other slots are initialised in void MemInitializeIO() in Memory.cpp, while Slot 0 has a different behaviour

1) it can only controlled with command line switches
2) LanguageCard and SaturnBanks are handled in AppleWin.cpp with a comment "// Don't reapply after a restart"

Why this different behaviour?

Cheers

**Comment by tomcw** [comment]
At the start of `MemInitializeIO()` slot-0 _is_ initialised with either Language Card I/O handlers or NULL handlers (for an empty slot). So it is the same behaviour as the other slots.

There are currently only command line switches to enable LC, Saturn and RamWorks simply because I've not added them to the main configuration GUI. As an aside the main configuration GUI is already very tight for space, so I want to change the layout to allow for slot-based configuration (like other Apple II emulators do).

**Comment by audetto** [comment]
I see,

I got distracted by SetExpansionMemType(), but the real initialisation is done in MemInitialiseIO().

**Comment by audetto** [comment]
What are the possibilities:

Slot 0: empty, language card or saturn (only for ][ +)
Slot Aux: empty, extended 80 cols or ramworks (only for //e)

I am getting confused by SetExpansionMemTypeDefault and SetExpansionMemType.

**Comment by tomcw** [comment]
Actually, slot 0 is for original ][ or ][+, so this:
Slot 0: empty, language card or saturn (only for original ][ or ][ +)

In `ResetDefaultMachineMemTypes()`, the default for the original ][ is: slot 0 empty, whereas for the ][+ it is slot 0 with LC. But if you specify the command line switch `-s0` (for Language Card or Saturn) then `SetExpansionMemType()` will "upgrade" the original ][ or ][+ to have this card type.

It's a little complicated because the current machine type (when you start AppleWin) could be Apple //e, but this `-s0` switch still takes effect. Now if you change the machine type to original ][ or ][+, then that machine will now have the Language Card or Saturn that your passed on the command line.

**Comment by audetto** [comment]
Understood.
