### ISSUE TITLE
Support 50Hz/PAL mode

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#648]
Arnaud (French Touch) requested this:

---

What about a 50Hz/PAL mode for AppleWin ?
I suppose that if it has not been implemented since time is that there are surely a lot of good reasons.

But let me still make some arguments ;)

- first, you're an European so what's the hell an AppleWin/60Hz! (joke)

- 50Hz/PAL mode has a longer VBL than NTSC. To program effects or demos, this increase is not negligible!

- YM/AY/PT3 music files, all use a 50Hz timing. So currently, to play a decent music on Apple II, it is necessary to use a 50Hz timing .

For example, check "latecomer" (http://www.pouet.net/prod.php?which=81035), an Apple II demo released at Revision2019 by fenarinarsa.
On an Apple II 50Hz, the demo uses the VBL detection to synchronize music and display. If the Apple II is NTSC, it uses a 6522 INT. But in this case, display is bad because no more synchronized with refresh rate. This is particularly visible in the Hires Scrolling part at the very beginning of the demo.
With AppleWin rendering is "bad" because of 60Hz.

Note: even if French Touch is credited in this demo, I had nothing to do with it. The author (fenarinarsa) just reused some little code snippets from the French Touch source file released at the time.

- There seems to be a little enthusiasm for demos/programming effects on Apple II. On Pouet, we can see that several projects have come out lately. But it also seems to interest Europeans much more than Americans. 50Hz vs 60Hz ;)

- I see you started adding features to AppleWin that brings it closer to an european Apple II (RGB display, support for PAL/European or custom 8K video ROMs).
Why not push a little further ?! ;)

- AiPC is the only Apple II emulator (to my knowledge) with a 50Hz mode . But as you've shown recently, its emulation is not always perfect for everything (ex: Mockingboard's inactive function). I think it's important to be able to test on different emulators . So we need another emulators with 50Hz mode!

- AppleWin is the best. I sincerely think so. Make it even better ;)

**Comment by Archange427** [comment]
I would like to clarify my own comment posted above and copied from an email sent directly to Tom. Because - as usual - my approximate English could be misinterpreted: fenarinarsa wrote 99.9% of the code for the demo "latecomer". French Touch was just credited because fenarinarsa reused some small pieces of source code released a few years ago. Thanks to him for crediting FT but especially congratulations for his work. We need more demos for Apple II!

Btw, thanks to Tom for opening this issue and formalizing the request for a 50Hz/PAL mode.

**Comment by fenarinarsa** [comment]
Oh wow, sorry I haven't seen that until now.

I also would be really glad if you added support for 50Hz since I had to check on my PAL Apple II everytime I modified the scrolltext effect in Latecomer XD

And I have other effects in mind, but they're more advanced so to have the amazing debug capacities of AppleWin + 50Hz support would be of a great help.
(I tested and debugged Latecomer on AppleWin, I didn't use other emulators)

And the final rotozoom is French Touch's. I just removed the LUTs and optimized the display, but I didn't have time to make an original effect, I added it just before the deadline at Revision.

So there's a lot more than 0,01% of French Touch's code in Latecomer. All the Mockingboard detection/hardware code is also from FT's source archive.

**Comment by tomcw** [comment]
Supported in AppleWin 1.28.8.0 ([here](https://github.com/AppleWin/AppleWin/releases/tag/v1.28.8.0)).

btw. @Archange427: you emailed me your OMT.dsk, but this needs fixing for the 6522 TIMER1 period+N issue, here: #652.

**Comment by Archange427** [comment]
You're right Tom! 
Here is a fixed version. [OMT_290619.zip](https://github.com/AppleWin/AppleWin/files/3341374/OMT_290619.zip)
Funny to note that no one had reported this issue for OMT (until now) so no one had tested it on a real Apple II 50Hz!

No need for a real machine or even an emulator when you release something today. 
Just make a video! ;)

Btw, I want to thank you personally for the 50Hz video option in AppleWin. 
Since it was a request that I defended ardently!
Thank you so much !

**Comment by tomcw** [comment]
Hi Arnaud - thanks for fixing & sharing.
Are you OK with me including the OMT.dsk as a test image for AppleWin regression testing?

(The .dsk will be stored in this repo: https://github.com/AppleWin/AppleWin-Test)

**Comment by Archange427** [comment]
Yes, I am!

**Comment by tomcw** [comment]
No problem - it's good to have something that now (closer) matches my real PAL Apple IIe!

Tests added here: https://github.com/AppleWin/AppleWin-Test/commit/5cbf0563e20df2da43ad4b44d7d0e833cce0b0f8

Closing this issue.

**Comment by Archange427** [comment]
And you even thought to add an option at the command line to launch AppleWin in the desired mode: 
"-50hz" or "-60hz".
Just one word: fantastic!

**Comment by tomcw** [comment]
Glad you like that! :-) It simplifies testing by setting different configuration from the command line.
