### ISSUE TITLE
WOZ: All even disk i/o read accesses will read the data latch

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#672]
From #662, @peterferrie said:
>At $8D2E, LDA $C08E,X is returning the wrong nibble (#$AD instead of #$FF, and that #$FF should be about to be dropped).

OK, I'm only updating the latch for $C0EC. So this #$AD is from the previous $C0EC latch read, ie. when it read D5AAAD. But, yes, strictly speaking all latch reads (ie. $C0En even addresses) should update the latch. I'll fix that.

**Comment by Archange427** [comment]
Not strictly related to this WOZ reading problem, but I remember that some groups of the french underground cracking scene in the 80s loved to use "exotic" addresses for their reading routine (like $C0E0 instead of $C0EC). 
When I was doing disk preservation, I had to patch a lot of these 'fresh' .DSK to work on AppleWin.
Could you also fix this issue for DSK ?
I can send you some DSK for tests if you want!

**Comment by tomcw** [comment]
I converted some of your .dsk's to .woz, and was able to test this - so I'll close this one.
And the specific fix for .dsk/nib is being tracked in another issue.
