### ISSUE TITLE
Hi-Res Color Palette Accuracy

### ISSUE THREAD

**Issue by gameshistory** [AppleWin/AppleWin#681]
I am recording some footage of _Prince of Persia_ in RGB Mode.

This game uses orange and blue for color in Hi-Res Mode.

When I take a screenshot, pixel values come out as follows:
**Orange:** 249, 86, 29
**Blue:** 7, 168, 224

Screenshot: https://i.imgur.com/Qp5ZMVH.png

Are these the correct values I should be seeing?

The below wiki page and screenshot from HardcoreGaming have these pixel values:
**Orange:** 240, 80, 0
**Blue:** 0, 128, 255

https://en.wikipedia.org/wiki/File:Apple_II_high-resolution_graphics_fringe_effects.png
http://www.hardcoregaming101.net/wp-content/uploads/2017/09/pop-app.png

**Comment by tomcw** [comment]
From PR #614:

>As for the colours: I've changed them from the original 1.25 colours. Instead I runtime-generate the colours from the NTSC code. See NTSC.cpp's GenerateBaseColors(). This shifts the same 4-bit pattern in, combining with NTSC color phase, until the colour stabilises. Then I average the next 4 RGB values to get the final colour. The reason for this is that we now have consistent colours between NTSC and this simplified rendering mode.
>
>NB. The 2 greys (in GR,DGR,DHGR) are now the same RGB value.

Basically the NTSC colors (sic) are not a fixed value, but for consistency with the RGB video mode, I've taken the average of the NTSC colors to produce a fixed RGB colour.

Read [this page](http://www.kreativekorp.com/miscpages/a2info/munafo.shtml) on Apple II display theory & colors. Here it defines the (theoretical / ideal) values as:

color | HCOLOR | R | G | B
-|-|-|-|-
purple | HCOLOR=2 | 255 | 68 | 253
orange | HCOLOR=5 | 255 | 106 | 60
green | HCOLOR=1 | 20 | 245 | 60
blue | HCOLOR=6 | 20 | 207 | 253

But messing with an RGB monitor's controls & environment (brightness, contrast, room lighting, age of monitor!) will change these values too.

Also take a look [here ](https://www.retrorgb.com/rgbmonitors.html) at the different TV / monitor outputs (ie. different colours).

Summary: there are no exact RGB values for the Apple II colors.

**Comment by i-hate-drm2** [comment]
Hi Tom,

Thanks for responding.  Just a few questions:

- Does an Apple 2 connected to an RGB Monitor send raw RGB pixel values to the screen? If so, what would the values for orange and blue be?
- Why modify the RGB values to approximate an NTSC Monitor? Shouldn't the colors be based on how they would have looked on an RGB Monitor? (Or maybe there could be two RGB modes)

Lastly, I noticed that RGB Mode adds a black line to the left-side of the screen. The line is half-a-pixel wide (because AppleWin outputs at 2x resolution). It also crops the right-side of the screen by half-a-pixel. Is there any way to fix this?

Compare:

AppleWin 1.29.10 RGB Mode: https://i.imgur.com/Qp5ZMVH.png
AppleWin 1.25.04 Color TV Emulation: https://i.imgur.com/Mf0nATZ.png

**Comment by tomcw** [comment]
>Lastly, I noticed that the RGB Monitor Mode adds a black vertical line to the left-side of the screen.

The Prince of Persia game is all orange and blue... ie, these colours are created with the high-bit set in the video bytes. This high bit set causes a half-dot-shift resulting in the visuals you are seeing. The old 1.25.0.4 mode didn't support this correctly.

**Comment by tomcw** [comment]
>Does an Apple 2 connected to an RGB Monitor send raw RGB pixel values to the screen? If so, what would the values for orange and blue be in their raw format?

The Apple II connected to an RGB Monitor needs an RGB Card (eg. Apple's, Video-7's, Applied Engineering's, Le Chat Mauve and John Brooks' recent VidHD).

Presumably they work by monitoring the video mode soft-switches and the data bus during the video phase. Then (like AppleWin) these cards will interpret the video data to produce an RGB signal per pixel.

I have never seen any spec for the RGB colours output by these cards, and I doubt they will all output the same RGB values.

>Why modify the RGB values to approximate an NTSC Monitor? Shouldn't the colors be based on how they would look on an RGB Monitor? (Or maybe there could be two RGB modes)

Good point! Since there's no exact spec (or precise RGB values) then IMO _reasonably accurate_ values are good enough. I went for consistency with the 4 HGR colors. Do you think the 1.25.0.4 HGR colors are more accurate?

btw. I don't have an RGB Monitor or RGB card.

**Comment by sicklittlemonkey** [comment]
Early RGB cards were 3-bit "TTL", so just 8 colours, and later 4-bit (R, G,
B and I for intensity) like CGA.
TTL meant that it was just logic levels choosing a colour index. It was up
to the monitor what colour was displayed.

Later systems transitioned to analog RGB where the combined levels on each
channel dictated the colour displayed.
The voltage levels were created by the card, so the card defined the
colours. E.g. heres a mod to convert a TTL card to analog:
https://www.esocop.org/docs/UsingAppleIIRGBonAnalog.pdf

Cheers,
Nick.

**Comment by i-hate-drm2** [comment]
Hi Tom,

Thanks again for responding.

Yeah, I don't have an RGB Monitor or RGB Card either. I just saw screenshots online (and the apple2 wiki page) and assumed that this was how the colors were supposed to look.

I'm totally biased in that I prefer the look of the 1.25.0.4 HGR colors. The mid-blue pixels complement  the orange a bit better than aqua does. Of course, that says nothing as to how accurate they are.

Is there any way to toggle the half-dot-shift?

**Comment by sicklittlemonkey** [comment]
Yeah, ideally the RGB mode would be rendered separately, not through the
NTSC video pipeline.
It didn't have half dot shift or any artifacting, and various cards had
different features (text colours etc).

I have the Apple //e Extended 80 Column card. In a month or two I should be
able to set it up.

**Comment by i-hate-drm2** [comment]
Awesome Nick!

Thank you for your work on this project.

**Comment by tomcw** [comment]
Closing old question.
