### ISSUE TITLE
Minimum VS version

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#696]
I wanted to simplify some of the sprintf code and I am not sure how to test the code I am writing.

The repo contains VS projects for VS2008, 2013, 2015, 2017, 2019.

Without installing them all, how is it possible to test some C++ code which might (or not) use features present or not in VS2008.
Are all these version still actively used?

**Comment by tomcw** [comment]
I recently raised an issue for moving from VS2008 to VS2019 here: #693, which I've targeted for milestone 1.30.0.

NB. I'm still building public releases with VS2008 though.

You should raise a pull-request (PR) for any changes. But in order to keep your newer C++ code _and_ maintain the compatibility with VS2008, then we'd need to wrap in CPP macros, eg:

```
#if _MSC_VER >= 1900
// VS2015 stuff
#elif _MSC_VER >= 1910
// VS2017 stuff
#endif
```

Or the PR could just wait until #693 has been done. But there is no date for this, so I'd estimate a few months' time.

**Comment by audetto** [comment]
Ok,

may I ask why moving to VS2019 requires such a big effort. The PR does not mention compiler issues.

**Comment by tomcw** [comment]
It's not the effort, but factors like:
- coordinating with other AppleWin developers to ensure they are all OK with VS2019.
- from an AppleWin user's point of view, ensuring they are OK with making WinXP the minimum supported version of Windows.

**Comment by audetto** [comment]
I wanted to clean all the sprintf, but it seems one needs VS2015 for a cpliant version of vsnprintf.

Guess I will stop here and wait for #693

**Comment by audetto** [comment]
VS version changed to 2019.
