### ISSUE TITLE
Can't add more new lines of code at a certain point 

### ISSUE THREAD

**Issue by ArthurOribe** [AppleWin/AppleWin#708]
1. Sorry for my english

I am a big fan of the TV show Lost, so i was trying to make the Dharma logo in the Apple II+, but at a certain point i coulden't add new lines of code and even cut one of the lines.

Here's the code
[DHARMA LOGO.txt](https://github.com/AppleWin/AppleWin/files/3752605/DHARMA.LOGO.txt)

**Comment by tomcw** [comment]
The BASIC code is extending into HGR memory space at $2000.

You can see this if you first do HGR, then paste the code into AppleWin - you'll see a few HGR lines with some random data.

One quick fix is to use HGR2 - so just change line 15:
`15 HGR2`

**Comment by ArthurOribe** [comment]
But HGR2 is "full screen" and i wanted that 4 spaces left of HGR to write.

**Comment by sicklittlemonkey** [comment]
Hi.

This problem is not related to AppleWin. It's normal Apple II
operation and you need to learn more about Applesoft memory
management.
I recommend reading this Q&A:
https://retrocomputing.stackexchange.com/questions/1919/apple-ii-applesoft-basic-memory-management
(If you want to put your program after HGR1, start at $4000 with POKE
104,64: POKE 16384,0.)

And if you need further help then ask in a forum such as Atari Age or
comp.sys,apple2:
https://groups.google.com/forum/#!forum/comp.sys.apple2

Cheers,
Nick.

**Comment by ArthurOribe** [comment]
Thanks.
And yes i know thats not a Applewin problem, but was the only place that i could remember give this information, i spend the hole day looking for something.

**Comment by sicklittlemonkey** [comment]
No problem. I hope the info I provided helps. I think comp.sys.apple2 is
your best bet. : - )
