### ISSUE TITLE
The role of GetFrameBufferBorderWidth()

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#727]
Finally managed to use the NTSC code in linux and initially thought of disabling the borders, but had to put them back in to avoid access violation issues.

Question is

https://github.com/AppleWin/AppleWin/blob/master/source/Frame.cpp#L191

comment says about the borders: (maybe with some preliminary/final NTSC data in the border areas)

is this intentional to avoid issues here?

https://github.com/AppleWin/AppleWin/blob/master/source/NTSC.cpp#L610

where the address (getScanlinePreviousInbetween()) can go outside the borderless frame?

**Comment by audetto** [comment]
I realise there is little background in the above statement.
Let me explain

I tried to switch off the borders and valigrind reports array access out of bounds at line 610 of NTSC.cpp. getScanlinePreviousInbetween() returns addresses outside the borderless buffer (so, no border = access violation)

With the border, there are no issues.

So I was curious to understand what the border is there for?
Is it to avoid an if statement around L610 of NTSC (as it is in a tight loop)?
Or it serves a different purpose?

**Comment by tomcw** [comment]
>So I was curious to understand what the border is there for?

The original NTSC implementation (by Sheldon) had a black border around the Apple II visible display, which was this (20 pixels on each side, 18 pixels top & bottom). It's left over from that implementation, and because of the out-of-bounds accesses has just been left in.

>Is it to avoid an if statement around L610 of NTSC (as it is in a tight loop)?
Yes, that's probably the only reason now.
NB. See also L768 (NTSC.cpp) where the comment says this does out-of-bounds writes too.

**Comment by audetto** [comment]
Perfect.

Thank you for the explanation.
