### ISSUE TITLE
The Best of MUSE WOZ image won't run

### ISSUE THREAD

**Issue by GreatHierophant** [AppleWin/AppleWin#732]
The issue is described here, but the short version is that this game refuses to boot if a language card, a firmware card or more than 48KB is detected :
https://twitter.com/txgx42/status/1197342047952355328

I think a command line option of "-s0 empty" would fix it, but would only have to apply to the Apple II and II Plus.  A language card checkbox in the GUI would be nicer :)

**Comment by tomcw** [comment]
I downloaded the version from woz-a-day, [here](https://archive.org/details/wozaday_The_Best_of_MUSE).

Using DOS 3.3 System Master's START13, this .woz works on an Enhanced //e.
So has it already been patched?

From the Info (v2) chunk in the .woz it has:
. Compatible Hardware = 0x0001 ; ie. just Apple ][
. Required RAM = 32
. Boot sector format = 2 ; ie. 13-sector

**Comment by GreatHierophant** [comment]
BOOT13 gets the disk booting.  There is a crack to let the game work as a 16-sector disk and that also eliminates any protection the original may have had.

**Comment by GreatHierophant** [comment]
All other 13-sector games in .woz format from woz-a-day work except MicroChess 2.0 with DOS 3.3 BOOT13 or START13.  That one refuses to do anything.

**Comment by tomcw** [comment]
re. "The Best of MUSE"
You said:
>this game refuses to boot if a language card, a firmware card or more than 48KB is detected

But with the .woz image I'm trying it works on an Enhanced //e (via START13)! So I'm confused why you say it refuses to boot. I'm clearly misunderstanding! :-)
NB. I can see you did a regular .dsk patch (for 16-sector & with Lang Card), but I'm not using that.

**Comment by tomcw** [comment]
>All other 13-sector games in .woz format from woz-a-day work except MicroChess 2.0 with DOS 3.3 BOOT13 or START13. That one refuses to do anything on AppleWin but boots ok on microm8.

All the details here:
https://twitter.com/a2_4am/status/1191425859514703873

In a nutshell:
>As for why it doesn't work with the BOOT13 utility (or the DOS 3.3 basics disk)... those utilities don't actually run the code at $0301 (from track 0, sector 0); they have their own interpretation of it, so they miss the jump at $0340 that decrypts the next phase of the boot.

AppleWin's Disk-II controller card only has the 16-sector firmware... I guess microm8 will autoconfigure to be 13-sector if the .woz image's Info chunk says it's 13-sector.

**Comment by txgx42** [comment]
To clarify about the language card issue... it doesn't interfere with booting but will cause some of the items in the menu to fail to run. The issue will occur if you boot using a 13-sector controller on a machine with an uninitialized language card. With BOOT13 it works ok because the DOS Master pre-loads BASIC into the LC. Not really an emulation issue since the same problem would happen on real hardware.

So the option to configure slot 0 as empty, or I suppose as a firmware card, might be useful. I notice that Integer Apple II mode doesn't currently include an LC.

**Comment by tomcw** [comment]
@txgx42 - thanks for the explanation.

>So the option to configure slot 0 as empty, or I suppose as a firmware card, might be useful

```applewin.exe -s0 empty```

>I notice that Integer Apple II mode doesn't currently include an LC.

Yes, that's right (ref. #590). But you can add one with:

```applewin.exe -s0 <languagecard|lc>```

NB. When LC is in slot-0, it will use the Apple II+'s F8 (auto-start) ROM

Or even add a Saturn LC:

```applewin.exe -s0 <saturn|saturn64|saturn128>```

NB. Since the //e doesn't have slot-0 (and has a built in LC), these `-s0` switches are just ignored if the Apple2 model is //e or Enhanced //e.

**Comment by tomcw** [comment]
I've added a DiskII card firmware auto-switch at #734 (coming in a future release of AppleWin).
This allows MicroChess 2.0 to boot (and all other .WOZ v2 images that are 13-sector).

**Comment by tomcw** [comment]
Support for WOZ v2 13-sector images in [AppleWin 1.29.11.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.11.0).
