### ISSUE TITLE
double-click issue with AppleWin 1.29.8.0

### ISSUE THREAD

**Issue by Archange427** [AppleWin/AppleWin#750]
Seems I missed the release of the new AppleWin two days ago!

Anyway, issue when I try to open it by double-clicking on a associated file (tested with .dsk and .woz),
I get this:
![screenshot](https://user-images.githubusercontent.com/10745357/72790876-a86f7a00-3c36-11ea-95cd-0c12dd2a9c2b.jpg)

The directory and file name displayed are the name and path of the file I "double-clicked"
Note that the final quote is missing...

And when I click to "OUI" (yes), AppleWin finally opens with the last used file mounted but not the new.
I never had this issue with the previous versions.
Not a dramatic problem but just a little annoying!

**Comment by tomcw** [comment]
Thanks for trying the new version and reporting this issue.
I've confirmed it, so will take a look in the coming days.

btw. I really enjoyed your latest Unreeeal Superhero 3! (And I just noticed a new Mad Effect 3... I can't keep up! :-)

**Comment by Archange427** [comment]
Thanks Tom. 
And don't worry, the pace should be much slower this year!

**Comment by tomcw** [comment]
Fixed in fcd1b2aa6856b087a48e9ce9a9386cb4e319f24c.

Some dev/triage notes:
- Initially run AppleWin.exe (debug) as "Administrator"
  - this sets up the Registry to point to this specific version of AppleWin to use when double-clicking a .dsk image
- Add an `_ASSERT(0)` as the 1st line of `WinMain()`
- Double-click a .dsk image (which will trigger the assert)
- From VS, attach to the AppleWin process
- now it's possible to debug the state for this double-click action!

This action is registered by AppleWin in `RegisterExtensions()`, using `pValueName = "DiskImage\\shell\\open\\command"`

There is a commented out attempt to use `applewin.exe -d1 %1`, instead of `applewin %1`... but no explanation why it wasn't used. Ultimately it gets handled by WM_DDE_EXECUTE, so probably it needs to look the same as ddeexec in the Registry (which is just `%1`).

**Comment by tomcw** [comment]
OK, this new [1.29.9.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.9.0) version fixes the issue.
