### ISSUE TITLE
Bejeweled issue with Phasor enabled

### ISSUE THREAD

**Issue by peterferrie** [AppleWin/AppleWin#753]
https://github.com/jeremysrand/a2bejwld/
To reproduce the effect: enable Mockingboard sounds in the Bejeweled options screen and then start a game.
The jewels will fall to fill the board, and then interrupts start firing endlessly.  ProDOS will panic after the stack overflows; TR just hangs.
The AppleWin Mockingboard option works flawlessly, so maybe an IRQ ACK issue with the Phasor?
It looks very similar to the Rescue Raiders issue with the Phasor, but (to me) not clearly identical.

**Comment by tomcw** [comment]
I've had a quick look.

The interrupt is from the speech chip (even though in the options I said no speech!). There's a write of 0xC0 to the speech chip's register 0, causing an interrupt, which (for Phasor) never gets cleared. NB. 0xC0 = IRQ (bit7:6) + phoneme 0 which is PA0 (or no sound).

For Mockingboard, the speech chip is emulated differently to the Phasor's.

Given that Phasor is compatible with Mockingboard, I don't know why I did them differently... but probably due to inspection of the Phasor disk's speech code, ie. the speech demo on the Phasor disks only worked when I emulated the speech chip like this.

NB. The Phasor has 4 DIP switches, one of which selects Mockingboard mode. Perhaps the speech chip behaves differently depending on the mode?
https://downloads.reactivemicro.com/Apple%20II%20Items/Hardware/Phasor/Phasor%20Manual.pdf

Anyway, I must revisit all of this. Ideally by trying with a real Phasor card.

**Comment by tomcw** [comment]
>It looks very similar to the Rescue Raiders issue with the Phasor

Yes, I think it is the same as #698.

**Comment by tomcw** [comment]
AppleWin 1.29.11.0, Enhanced //e, Phasor in slot-4:
- 2.3: boots & works fine (auto-detection: speech is off)
  - manually enabling speech, saving then rebooted and starting game: `RESTART SYSTEM-$01`
- 2.4: hangs during boot: `RESTART SYSTEM-$01`
- 2.5: hangs during boot: `RESTART SYSTEM-$01`
  - NB. boots fine with Mockingboard in slot4&5

**Comment by tomcw** [comment]
>Anyway, I must revisit all of this. Ideally by trying with a real Phasor card.

Bejeweled 2.5 works with a real Phasor (SW1=CLOSED, ie. Phasor mode or SW1=OPEN, ie. MB mode)
- Boots fine, correctly auto-detects Mockingboard & Speech.
- Game starts and says something (sounds like "yoal", but from the source code looks like it should be "Go"!)

**Comment by tomcw** [comment]
@peterferrie - this is now fixed in AppleWin 1.29.12.0 [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.12.0).

**Comment by tomcw** [comment]
Closing fixed issue
