### ISSUE TITLE
Improved support for 'Le Chat Mauve' RGB card

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#764]
@Archange427 emailed me on 17/2/2020:

---

Another mode which would be interesting to emulate (!!!)  is the display mode of the french APPLE IIc.
IIc in french market were sold with a Scart output containing in fact the electronics of a "Le Chat Mauve" card...

The main advantage of this mode is that in fact we have two different grays available and not only twice the same. And the colors tints are not exactly the same...

Here are two screenshots that illustrate this a bit (taken by @fenarinarsa from its Latecomer demo - thanks to him):
![1](https://user-images.githubusercontent.com/6696896/75115463-b873e280-5656-11ea-964b-be02e2a986a7.jpg)
Latecomer - AppleWin (RGB)

![2](https://user-images.githubusercontent.com/6696896/75115465-bad63c80-5656-11ea-8d04-c83dad9603d6.jpg)
Latecomer - Apple IIc with Chat Mauve RGB output

As you can see, the difference is obvious! And the rendering is the same with the "Le Chat Mauve" cards sold for Apple IIe.

**Comment by tomcw** [comment]
AppleWin does a semi OK job in emulating Le Chat Mauve (aka Apple RGB Color card). But mostly AppleWin supports it for improved DHGR support. I'm away at the moment, so can provide more details next week.

One question: what monitor is that last picture of le chat mauve taken from? Eg. A real monitor or emulator?

**Comment by tomcw** [comment]
@Archange427 replied:

---

@fenarinarsa said me that the artifacts from "Le Chat Mauve" cards (including the RGB output from french IIc) are already implemented in GrafX2
https://gitlab.com/GrafX2/grafX2
Perhaps a good start to emulate this video mode.

And the last screenshot is taken directly from a french IIc output capturing with "professional" hardware (OSSC+capture card).
You can therefore consider that it is the almost real rendering of an IIc/RGB output ("almost" because @fenarinarsa thinks the light colors are probably a little too light!)

It seems that AppleWin's RGB mode actually only displays one gray color (the two gray are the same) which is not the case for Le Chat Mauve cards (for IIe and for IIc)

**Comment by tomcw** [comment]
I checked the above GrafX2 repo.

In this [source file](https://gitlab.com/GrafX2/grafX2/-/blob/master/src/miscfileformats.c) are some comments about Le Chat Mauve.

One comment references this [Extasie Chat Mauve Reloaded](http://boutillon.free.fr/Underground/Anim_Et_Graph/Extasie_Chat_Mauve_Reloaded/Extasie_Chat_Mauve_Reloaded.html) page.

Also, last year I had some communication with some other 'Le Chat Mauve' users. See #631 and #633.

**Comment by fenarinarsa** [comment]
Hello,

I'm currently doing some research on the Le Chat Mauve cards and also on the Apple Color RGB card (which I think worked only in TTL?). I don't exactly know what's the relationship between Video-7 and Le Chat Mauve but it seems clear that there is at least some compatibility between them.

My goal is to underpin the different modes supported by:
- NTSC composite (already done, extensively)
- PAL composite
- Le Chat Mauve RVB Graph
- Le Chat Mauve EVE
- Le Chat Mauve Feline
- Le Chat Mauve IIc adapter
- AppleColor RGB

By doing code testing (how to activate the various modes) and video captures (photos are not enough).

So far here's what I know:

- **NTSC composite**: same as everyone

- **PAL composite**: seems to work exactly like NTSC composite since the converter is based on NTSC chroma. However the final colors seem to be a bit different and "Understanding the Apple IIe" points out that it's also a bit blurrier because a chroma frequency is filtered out. I will do some video captures as soon as possible. PAL IIcs don't have color composite output so I can't test it at home.

- **Le Chat Mauve RVB Graph** is a II+ card with extended modes : color TEXT (FG/BG for all screen) and extended HGR that allows to choose the 6 HGR colors out of the 16 GR colors. Also with a "dotted line" option

- **Le Chat Mauve EVE** is for Apple IIe and adds a 64k expansion with no less than 10 new video modes, some working like the AppleColor RGB card but the init sequences are different (tested on EVE with the Apple RGB demo disk). It can redefine the TEXT charset on the fly. It isn't backward-compatible with RVB Graph. It supports 140x192 color DHGR and 560x192 BW DHGR but not the mixed mode.
The color palette is a bit different than NTSC composite, grey1 and grey2 are different.
I need more time to work on this one.
https://www.fenarinarsa.com/?p=1370

- **Le Chat Mauve Feline** is a more simpler card, 64k expansion with only three DHGR modes: 140 color, 560 B&W and mixed. It's activated like the AppleColor RGB card and the DHGR modes on EVE. As for EVE the color palette is different from NTSC.

- **Le Chat Mauve IIc adapter** is a Feline without the memory expansion.

- **AppleColor RGB** has color text and duochrome HGR like EVE (but they don't seem to be activated the same way). It supports the three DHGR mode, activated like on Feline, but also supports a fourth mode, which is 8-bits based: 160x192.
From the only screenshot I could see, the color palette seems very different on this card.
All this card's modes can be tested with the "Video-7 Apple II RGB Demo (Video-7, Inc.)(1984)" disk.

What friends and I could test yet:

PAL composite
In mixed mode (for example GR+TEXT), the chroma is disabled on the TEXT part, like it should be in NTSC - but isn't because of NTSC limitations, it seems.
The colors seems to be slighlty different from NTSC. Else the NTSC artifacts shows the same way.

IIc adapter (Feline)
- Generally, there is no NTSC color artefacts at all
- The color HGR rendering is different than in NTSC. I will explain the GrafX2 algorithm later but it's quite simple - a lot simpler than NTSC rendering. It was tested against my IIc adapter.
- Lowering AN3 in HGR makes it switch to 240x192 B&W (like in AppleWin RGB)
- In DHGR color it's a plain 140x192 mode (no color artifacts)
- In DHGR mixed mode, when you switch mode in the middle of a 4 bits sequence, the change (color/BW) is taken into account only from the next 4 bits sequence. So it's always one 4-bits wide color pixel or four 1-bit wide B&W pixel.
- The DHGR modes activates with the same sequence than on AppleColor RGB or EVE, by pushing 2 bits into an internal register to define the wanted mode. I could reproduce it every time. The bit is defined by 80COL and pushed by enabling AN3.
You can find this piece of code on various slideshows/demo disks or other tools, with variations, mostly depending on the way it was coded (for example the Arlequin API uses a more generic routine):

`LDA $C050  TEXToff
LDA $C057  HRon
LDA $C052  MIXEDoff
STA $C00C or $C00D
STA $C05E
STA $C05F
STA $C00C or $C00D
STA $C05E
STA $C05F
STA $C05E   DHGRon
STA $C00D 80col`

C00C+C00C (00)  = DHGR BW (AppleColor, EVE, Feline) - AppleWin ok
C00D+C00D (11) = DHGR color (AppleColor, EVE, Feline) - AppleWin ok
C00C+C00D (01) = DHGR mixed (AppleColor, Feline) - AppleWin ok
C00D+C00C (10) = 160x192 (AppleColor)

When a non-supported mode is selected, EVE and Feline display the regular color DHGR.


I hope to give you more results very soon.

About the color palette : the one in my YouTube video capture is NOT correct. Since then, I found the correct color balance and gain settings on my converter. It's still a different than in composite NTSC.
But I'd like to make some captures on real EVE and Feline before defining an RGB "Le Chat Mauve" palette.


I must add that in some cases, games seem to activate the Feline modes by error (or more likely because they're not aware of the modes). The examples I have in mind is Wavy Navy that activates HGR BW when starting a new game, or Prince of Persia, which activates DHGR BW when showing the title screen for the second time after the first gameplay demo.
In my opinion this shouldn't be treated as an emulation bug.

**Comment by tomcw** [comment]
btw, AppleWin also (badly) supports the DHGR 160x192 mode too... see #621.
AFAIK only these 2 images support this mode, and **nothing** else!

**Comment by fenarinarsa** [comment]
Oh cool for the 160x192 mode. I think it didn't work when I tried the Video7 demo disk on AppleWin... Will check it again.
It's also explained on this page, which contains a GR>160x192 conversion routine
https://web.archive.org/web/20061012082347/http://bobsc5.home.comcast.net/aal/1986/aal8608.html#a6

According to this page, on AppleColor RGB the F/B mode (what I incorrectly call "duochrome": monochrome HGR with page 2 defining foreground/background for every byte) is enabled this way:

> F/B mode is active any time the 80 column switch is off and annunciator 3 is off. 

It looks like it replaces the bizarre HGR feature that invert color groups when AN3 is off in composite (or make monochrome HGR on Feline). It doesn't activate that way on EVE.

So as promised, here's the render algorithm for HGR in Le Chat Mauve Feline/IIc.
I can't say for other cards yet. I can only guess it's the same for EVE.

First, slice the 280 bits of a line in 140 cells of 2 bits. That defines the color of the "cell".
```
00: -
01: color 1
10: color 2
11: -
```

What's really important here is color 1 and color 2.

Now we're going to find the color for each 280 pixels, 1 pixel being 1 bit. For that, we need to check the bit with the two neighboring bits, so that's a 3-bits check. The bit before the first pixel and the bit after the last pixel are equal to 0.

The two important cases are:
```
101
010
```
=> the middle pixel takes color 1 or color 2 (as found in the previous step).

In all other cases, the pixel is black if equal to 0 and white if equal to 1.

As I said, we checked the result against all possible combinations on my IIc adapter.

GrafX2 implementation can be seen here in `Update_color_hgr_pixel`:
https://github.com/pulkomandy/grafx2/blob/master/src/graph.c

**Comment by tomcw** [comment]
@fenarinarsa - that's a great level of detail, so thanks for sharing it all.

From #631 and #633, I still have these outstanding questions about the AppleColor RGB card for //e and Le Chat Mauve for both //e and //c...

1. What are the video soft-switch(es) pre-conditions for AN3 to select the DHGR mode?
Currently if MIXED ($C053) is on, then AppleWin doesn't allow AN3 to set the DHGR mode- is this correct or not?
- This idea of a video pre-condition was from the Video7 card's documentation, but maybe for other cards (eg. Le Chat Mauve and AppleColor RGB card) there is no video pre-condition?
- NB. Video7 says that 80STORE ($C001) must be set, which is not true for some game / slideshows.


2. How does Dragon Wars ([here](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/rpg/dragon_wars/dragon_war_a.dsk)) look on Le Chat Mauve (or AppleColor RGB card)?
It sets DHGR MIX mode, but each DHGR byte has bit7 set the wrong way!
I created a special command line switch (-rgb-card-invert-bit7) specifically so that Dragon Wars would render in correctly colour!
See discussion in #633.


3. How does the "Pierre" image (head coming out of Apple II) look on Le Chat Mauve (or AppleColor RGB card)?
From the Extasie slideshow ([here](http://boutillon.free.fr/Underground/Anim_Et_Graph/Extasie_Chat_Mauve/Dsp_Img/Disks/Dsp_Img.dsk.gz)), the "Pierre" image is rendered by AppleWin in B&W.
See discussion in #631.


4. How are the AN3 soft-switches able to control things on an Apple //c?
I don't understand how AN3 can be connected to this //c adapter. Or perhaps I am wrong and the //c can access the annunciators?

**Comment by fenarinarsa** [comment]
>     1. What are the video soft-switch(es) pre-conditions for AN3 to select the DHGR mode?
>        Currently if MIXED ($C053) is on, then AppleWin doesn't allow AN3 to set the DHGR mode- is this correct or not?

It isn't correct, I can turn on DHGR mode when MIXED is on. (IIc)

>     * This idea of a video pre-condition was from the Video7 card's documentation, but maybe for other cards (eg. Le Chat Mauve and AppleColor RGB card) there is no video pre-condition?

Yes this is possible. Unfortunately I don't have an AppleColor RGB card to test it. However the Apple RGB card documentation doesn't seem to ask for any precondition (or maybe I missed something?)
 
>     * NB. Video7 says that 80STORE ($C001) must be set, which is not true for some game / slideshows.

I must do some more tests in asm because setting 80COL under the monitor automatically enables 80STORE.

>     1. How does Dragon Wars ([here](https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/games/rpg/dragon_wars/dragon_war_a.dsk)) look on Le Chat Mauve (or AppleColor RGB card)?
>        It sets DHGR MIX mode, but each DHGR byte has bit7 set the wrong way!
>        I created a special command line switch (-rgb-card-invert-bit7) specifically so that Dragon Wars would render correctly in colour!
>        See discussion in #633.

Yes, indeed, the bit7 behavior is reversed in Dragon Wars on LCM IIc adapter.

Perhaps Dragon Wars expected a different RGB card? Or maybe it wasn't really tested on an Apple RGB card after all? I saw there was many RGB cards available.

>     2. How does the "Pierre" image (head coming out of Apple II) look on Le Chat Mauve (or AppleColor RGB card)?
>        From the Extasie slideshow ([here](http://boutillon.free.fr/Underground/Anim_Et_Graph/Extasie_Chat_Mauve/Dsp_Img/Disks/Dsp_Img.dsk.gz)), the "Pierre" image is rendered by AppleWin in B&W.
>        See discussion in #631.

That's funny. It appeared in BW first, but then when I load it a second time, it's in full color.
This slideshow seems completely broken to me, I never had any issue when loading those pics in Extasie. You can see that even the first popup menu displays bugs on my IIc.
https://www.youtube.com/watch?v=m2FbrxqEHic

>     3. How are the AN3 soft-switches able to control things on an Apple //c?
>        I don't understand how AN3 can be connected to this //c adapter. Or perhaps I am wrong and the //c can access the annunciators?

AN3 is available on the IIc but you're right, I don't see how the adapter has directly access to it.
However AN3 enables DHGR and the adapter knows when DHGR is enabled: the IIc documentation states that the TEXT pin is set to the inverse of the GR pin, except in DHGR. I guess it can also detects when 80COL is enabled?
Unfortunately I'm not an Apple II hardware specialist :(

**Comment by tomcw** [comment]
re. (1) / video pre-conditions
>It isn't correct, I can turn on DHGR mode when MIXED is on. (IIc)

Thanks - I will fix AppleWin to remove all video pre-conditions.

re. (2) / Dragon Wars
>Perhaps Dragon Wars expected a different RGB card?

Yes, perhaps.
I need to find someone (Nick / @sicklittlemonkey?) with a different RGB card, eg. AppleColor RGB card or even Video7 card.

re. (3) / Pierre image on the Dsp_Img.dsk
>This slideshow seems completely broken to me...

Your results are consistent (I think) with #631.

re. (4) / AN3
I'm no expert on //c h/w either, but clearly AN3 is getting routed to the LCM adapter.

**Comment by sicklittlemonkey** [comment]
Yes, I have the   AppleColor RGB card, but not a monitor to use it with. In
Japan I had one of those great old Sony CRT monitors hooked up to it.

I also have the Video 7 "Enhancer" for the //c. This is a very simple
device though, nothing like what's being talked about.

**Comment by fenarinarsa** [comment]
> 
> Yes, I have the AppleColor RGB card, but not a monitor to use it with. In Japan I had one of
> those great old Sony CRT monitors hooked up to it. I also have the Video 7 "Enhancer"
> for the //c. This is a very simple device though, nothing like what's being talked about.

Are you talking about this adapter?
http://www.apple-iigs.info/doc/fichiers/Video-7%20Color%20Enhancer%20IIc%20-%20Manual.pdf

It looks like it's the one that works with the Video-7 Apple RGB demo disk I talked about.

By reading the manual, it seems to have the exact same features than the LCM IIc adapter and LCM Feline.

**Comment by tomcw** [comment]
There's a new release of AppleWin 1.29.15.0 containing this update: [here](https://github.com/AppleWin/AppleWin/releases/tag/v1.29.15.0). There's still #819 open which has some extra work for LCM's EVE RGB card.
