### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by fenarinarsa** [AppleWin/AppleWin#795]
Hello,

I'm currently working on extending the debugger's features and I need to be able to access the real contents of the RAM banks (main & aux) at any given time.

I checked Memory.h and Memory.cpp and I found out that there is many layers of memory buffers:
mem
memmain, memaux
memwrite
memdirty
memshadow
It seems the various buffers are refreshed by UpdatePaging() when the CPU flips memory-management soft-switches.

Currently in order to "see" the actual contents of both banks, I need to rebuild them on the fly by using mem+memdirty (which acts like a cache), memmain and memaux.

I'm wondering what was the reason behind this design choice. Maybe it's performance-related?

Because the way I see it, it can be rewritten to be simplified a lot. For instance, a memshadow_RD and a memshadow_WR that contains pointers to memmain and memaux's pages and accessed that way  (excluding IOs of course):
`value = *(memshadow_RD[addr>>8] + (addr & 0xFF))`
would work without a lot of performance loss on today's computers.

Then both memshadow could be updated in UpdatePaging(). Maybe even by copying a bunch of pointers for large memory zones like $60xx-$BFxx. It would be a maximum of 512*2 bytes to copy instead of a lot of cached data as it's done now.

I'm asking because I know AW handles a lot of things so maybe I'm missing something important there, like a feature that won't work this way?

**Comment by tomcw** [comment]
Yes, it is a little complex! The `UpdatePaging()` design was done by the original AppleWin author, and it's (more or less) remained like that since.

At a high level, the 64KiB `mem` is a consistent *virtual memory* view from a *read* perspective. It gets updated whenever the virtual mem read-view changes. Writes are done indirectly via pointers.

So it's efficient if there's little bank switching (either language card or main/aux)... but if there's lots of bank switching then your full indirect approach for both read & write is likely more efficient.

I'm reluctant to change it because: (a) it works (if it ain't broke don't fix it), and on modern PCs it's fast; (b) Apple II bank switching is complex anyway, so changing it will introduce bugs; (c) I've got plenty of other things to work on ;-)

If it's *physical memory* you want to r/w, then take a look at `CmdMemorySave()` in debug.cpp. This uses `MemGetBankPtr()` to flush the cache and get a pointer to the physical 64KiB bank.

**Comment by fenarinarsa** [comment]
Thank for the answer, so it's indeed a legacy reason.

I usually agree that it's better to leave working code as is, but refactoring is also a good option when it comes to legacy code. In that case it would make the code easier to understand and better fit for new features.

Actual case, look at the extended debugger I'm currently working on:
https://www.youtube.com/watch?v=PlSsV7w2Vbk

I implemented the heatmap that @Michaelangel007 started in "65d02" and I'm struggling with the whole `mem` cache concept because I need to know where is going every read and write. So I do a complete soft switch analysis for each read/write/execute. On the opposite, using `memshadow` and `memwrite` directly would be a lot faster. Another way would be to make a "heatmap cache" that follows "mem" but it would be like adding a new paint layer on an old wall.

As for drawing the memory data, I considered `MemGetBankPtr()` but I didn't want to flush data 60 times per second :/ hence the display bugs for now (I'm working on it). 

I'm starting to understand AW's code more and more, so I'm going to release the extended debugger first, as soon as it's okay enough to be public (ie: not changing the regular users' experience). I'm planning on making a push request upstream.
Then I'll see if I can rewrite the memory part to get rid of `mem` and use `memshadow `and `memwrite `directly. I already had a look at Saturn and AppleWorks' extensions support.

The WIP debugger is currently available in French Touch's fork (branch extended-debugger).

**Comment by fenarinarsa** [comment]
Okay I ended calling `MemGetBankPtr()` at each video refresh and it's fast enough :)
There's no more bug in the heatmap!

**Comment by tomcw** [comment]
This looks great! Nick W (@sicklittlemonkey) will be interested to see this too, see his YT video in the comments of #326 from some years ago.

>Okay I ended calling `MemGetBankPtr()` at each video refresh and it's fast enough :)

Glad to hear that.

>I'm planning on making a push request upstream.

This sounds interesting too, so looking forward to seeing it when you are ready.
NB. Big pull-requests can be quite daunting, so ideally you'd break it up into smaller pieces.

**Comment by fenarinarsa** [comment]
I think I have a version that can be pushed to upstream now.

How should I do a push request? (I never did one before)
Currently it's located in French Touch' fork, branch 'extended-debugger'. I already rebased the code on the master branch a few days ago and I've just checked, it seems there's no merge collisions right now.

I did my best to test for regressions and I'm pretty sure it doesn't impact the general user experience (the benchmark results gives 19Mhz with video update on my 3Ghz i7 and 329Mhz of pure emulation).

The only thing that I didn't disable when running in normal mode (without any debugger feature active) is the heatmap table update: any CPU read/write makes a write the 3x64k table with an active bank detection function. But if needed a test could be added.

Other than that, there's a lot of code additions because I needed to add new helper functions and global variables, some enums etc. since the debugger must now refresh during emulation. I also rewrote some bitmap refresh functions because now the Framebuffers resolution is not the same than the windows' - and I entirely dumped the old PrintGlyph() debugger function, resulting in a huge performance boost.

I hope I didn't mess too much with the code, I found out that my C skills were a bit rusty and I had to change how the debugger was called in the main loop (previously it only depended on g_nAppMode).

New debugger commands:
G - Run with debugger following PC
GD - Run with debugger NOT following PC
GC - Refresh emulator screen + debugger after each opcode
xxxxD - Shortcut to D xxxx (hex dump)

Here's a new video with more games/demos. You can see the cycle-refresh debug on Mad Effect #2.
https://www.youtube.com/watch?v=PuCs_5hwRBM

**Comment by audetto** [comment]
> At a high level, the 64KiB `mem` is a consistent _virtual memory_ view from a _read_ perspective. 
> 
> If it's _physical memory_ you want to r/w, then take a look at `CmdMemorySave()` in debug.cpp. This uses `MemGetBankPtr()` to flush the cache and get a pointer to the physical 64KiB bank.

I found this really useful.

So, just for reading: `mem` is the virtual memory and `MemGetBankPtr` all the physical banks.

What is the usage of `MemGetAuxPtr` and `MemGetMainPtr`? they seem to be used mostly for video?

**Comment by tomcw** [comment]
>What is the usage of `MemGetAuxPtr` and `MemGetMainPtr`? they seem to be used mostly for video?

Correct - almost exclusively for the video scanner's reads. (The exceptions being for some code to query the ProDOS track/sector variables.)

These two functions guarantee the byte returned is from aux/main memory regardless of how bank-switching is configured.

EG. Bank-switches (and therefore `mem`) maybe be setup so that 6502 reads are from aux memory. But in TEXT mode, the video-scanner needs access to main memory video memory ($400-$7FF).

**Comment by tomcw** [comment]
Closing old question ticket.

**Comment by audetto** [comment]
I have a question related to this old topic:

Is this correct? https://github.com/AppleWin/AppleWin/blob/cb37dd300b0c5a89bccc9466dd23ebba2286bbfc/source/Debugger/Debug.cpp#L4171
Should it not start at `nDst`?

Plus a double check of my understanding

1. `mem` is good to read from virtual memory
2. `mem` is good to write to virtual memory (but mark it as dirty)
3. `MemGetBankPtr` can be used to read / write to physical memory
4. when is a change to virtual memory copied to physical memory?
5.  when is a change to physical memory copied to virtual memory?

**Comment by Michaelangel007** [comment]
I think I was being extra conservative for the pathological case when source and dest overlaps.
i.e.
`2000<2001.2FFFM`

I don't doubt it could be tuned to be more exact.

**Comment by tomcw** [comment]
@audetto
>Plus a double check of my understanding

Firstly, there's some notes on the various memory variables here:
https://github.com/AppleWin/AppleWin/blob/93ea5b3e60e840a396bdead6e98ccd190a4f4020/source/Memory.cpp#L171-L179

Specifically:
1. Yes - but as in the notes above, not good for reading I/O memory
2. No - see above note (only OK if the write page addr == read page addr)
   - instead use `memwrite[256]` pointers
   - see the `_WRITE` macro in `cpu_general.inl`
   - see the tail of `IO_F8xx()` function in `memory.cpp`
3. It can, but then you need to ensure that `mem` remains consistent afterwards
   - eg. writing to a page that is also mapped for reading, means that you'll need to resolve things so that reads from `mem` see this newly written data
   - A heavyweight way to "resolve things" is to call `MemUpdatePaging(true)`
   - Probably the more lightweight `MemUpdatePaging(false)` is OK too
4. Virtual memory is only reflected in the read-only `mem`, so is therefore by definition never changed
5. On calls to `MemUpdatePaging()`

**Comment by audetto** [comment]
About 2: how to write to virtual memory.
I see `_WRITE`, but then how does `MEW` do it?

https://github.com/AppleWin/AppleWin/blob/cb37dd300b0c5a89bccc9466dd23ebba2286bbfc/source/Debugger/Debug.cpp#L3610

Should it use the macro instead?

**Comment by tomcw** [comment]
`MEB` and `MEW` will work for _most_ cases, but not all.

Consider if I were to setup the MMU as: read main mem (BIT $C002) / write to aux mem (BIT $C005).
(And also like the Language Card where it can read ROM / write RAM.)

If I use `MEW` to write a word to `mem` (eg. `MEW 300 1234`), then the next time `MemUpdatePaging()` is called, it will see that page-3 is dirty, and will copy it from `memmain[]` to `mem`, overwriting my value of 1234.

So maybe the way to do it is to write via the `memshadow[]` pointers, as well as `mem`.
From the notes at the top of memory.cpp:
>memshadow
>- reflects how 'mem' is setup for read operations (at a 256-byte granularity)

eg:
```
if (memshadow[nAddress >> 8])
{
	mem[nAddress] = data;
	* (memshadow[nAddress >> 8] + (nAddress & 0xFF)) = data;
}
```

NB. don't set the `memdirty[]` flag, since you are not writing via the `memwrite` pointers.

NB. `memshadow` is static in memory.cpp, so you'd need to interface via a new function added to memory.cpp (ie. don't just remove the static)

btw, `MEW` has a bug when writing more than one word, eg. `MEW 300 1122 3344`, as it only sets `300:22 11 33`
