### ISSUE TITLE
Loading Save State = Parser Error (invalid trailing UTF-8 octet)

### ISSUE THREAD

**Issue by FenrirXVIIRag** [AppleWin/AppleWin#838]
Hi Everyone!
First of all, thank you for all this help. AppleWin is a marvelous emulator! Great work!

It's a noob's problem, I'm sorry if I bother you with it, but I can't find the solution anywhere...

When I want to load a SaveStates in any game, AppleWin show me a "Parser Error" and quit the emulator...
In the Help menu, SaveStates seems realy easy to manipulate, and I can't find any other exemple of this problem on the web.

Thank you for your help!!
And have a nice day!!

**Comment by tomcw** [comment]
Can you attach your save-state file here?
EG, zip it and then attach it (or rename it to have a .txt extension).

**Comment by FenrirXVIIRag** [comment]
[beneath_apple_manor_apple_II_(16_settori).aws.zip](https://github.com/AppleWin/AppleWin/files/5276987/beneath_apple_manor_apple_II_.16_settori.aws.zip)

Thank you to give your time! :D

**Comment by tomcw** [comment]
The problem is the unicode é character in this folder (path): "C:\Jeux Vidéo\Apple II\"
This path gets persisted to the save-state file for the "Printer Filename".

A workaround is in AppleWin Configuration->Advanced tab, change the location of the "Printer dump filename" to a folder that doesn't have a unicode character.

Developer note: the YAML reader contains this string problem = "invalid trailing UTF-8 octet".
NB. If I edit the save-state file and replace the u'\xe9' character with é (AltGr+e from a UK keyboard) then AppleWin happily loads the save-state file.

I'll tag this as a bug, but I suspect it's a limitation of the YAML reader used by AppleWin.

**Comment by FenrirXVIIRag** [comment]
Awesome!
Everything works fine, because of you!
A very BIG thanks for your help and your quick and professional answer.
You made a RPG quest master happy!

**Comment by tomcw** [comment]
Glad it got things working for you.
I'll leave this issue open to better understand any limitations with accented (ANSI) characters.

**Comment by tomcw** [comment]
dev notes:
- call `yaml_check_utf8()` to check string
- if check fails (ie. ANSI) then convert the ANSI string to UTF-8:
  - `MultiByteToWideChar(CP_ACP)`, then `WideCharToMultiByte(CP_UTF8)`

See: https://devblogs.microsoft.com/oldnewthing/20100603-00/?p=13823

**Comment by tomcw** [comment]
Fixed at  09a5ac476.
Also improved YAML Parser error msg to include the problem string.
