### ISSUE TITLE
How to tradeoff video quality vs CPU usage

### ISSUE THREAD

**Issue by audetto** [AppleWin/AppleWin#858]
Hi,
Recently, I made the SDL version of the Linux port as feature complete as the Qt one.
I run on a Pi 3 and it struggles to run in real time.

Video seems to be the culprit.
Would you be able to suggest some changes so that I gain speed, even if video quality is partially reduced?

Cheers

**Comment by tomcw** [comment]
AppleWin is essentially single-threaded, so that means a RPi3 (1.2GHz Cortex A53) isn't quick enough, which seems odd as my AMD x86-64 at 3GHz can run everything (video, CPU, etc) at an emulation speed of 23MHz ([ref](https://github.com/AppleWin/AppleWin/pull/837#issuecomment-700254875)).

The old 1.25 video renderer runs quickest, currently called "Color (Composite Idealized)".

But the real trouble is that all the renderers get updated after every opcode by calling `NTSC_VideoUpdateCycles()` at the end of the 6502 & 65C02 opcode switch statements.

...except in full-speed mode when instead there is a full-screen update once every 50Hz or 60Hz (wall-clock), done in the main emulation loop in `ContinueExecution()` which calls `VideoRedrawScreenDuringFullSpeed()`.

So you could experiment with not calling `NTSC_VideoUpdateCycles()` after every opcode, or never calling it and instead periodically calling `VideoRedrawScreenDuringFullSpeed()`.

**Comment by audetto** [comment]
Short of a mistake, I do not see any impact.
In the end, it needs to process all the pixels and whether it is done after each instruction or all at once, it makes little difference.

I guess I would have to decrease the frame rate to see a benefit.

**Comment by tomcw** [comment]
It sounds like you may need to do some profiling, but I suspect if the per-opcode-NTSC-update / `NTSC_VideoUpdateCycles()` (which just writes pixels to the frame-buffer) isn't the problem, then it's the periodic video update that is your perf bottleneck.

See 13a4043, and the related #788, to get some timings for the various AppleWin sub-systems.

**Comment by audetto** [comment]
After some comparisons with other emulators (some discussion here https://github.com/audetto/AppleWin/issues/12), initial findings on a Pi3 is that "just redrawing the screen" at 60Hz takes a lot of time (even using SDL2).
Pi3 offers some hardware access, but it is not for the faint of heart.

Linapple and gsplus seem to have some "smart" adaptive redraw of the part of the screen that has changed. If the screen does not change, they use little CPU, ramping up if it moves faster.

How messy / hard / ugly would this be in AW?

**Comment by tomcw** [comment]
For the original AppleWin video (back before the NTSC support was added), the video changes where tracked by a 40x24 array of cells (each representing a 7x8 pixel cell). Then at video refresh/redraw time, only those changed cells would be updated.

This method didn't work for cycle accurate ("racing the beam") effects, as it assumed that the video mode remained constant for the entirety of the frame.

When NTSC (and cycle accurate) support was added, then the video update changed to always update the video after every opcode.

For Windows there's no need to support this old "smart" method, as it's fast enough on modern PCs & Windows. So I certainly wouldn't want it as part of the code used by the Windows build of AppleWin. But as something that existed purely as Linux-only platform-specific code, then that might be one way to go. I imagine we'd need a fair bit of AppleWin project/architecture restructuring to get to this point.

**Comment by audetto** [comment]
Profiling video rendering on a Pi3 is not a task for the faint of heart.
Current situation is that on a Pi4 using full KMS, the emulator can easily run 60 fps.

The maximum fps depends on the window size, but always above 60 fps.
Best performance achieved when running full screen (not maximised, real full screen).
