### ISSUE TITLE
Anti-M 1.8 doesn't work

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#864]
https://github.com/a2-4am/anti-m

Just switches to drive 2 and sits there. Don't know if it's a problem with the program itself or AppleWin. But it does work on older versions of AppleWin.

**Comment by tomcw** [comment]
From the instructions on that anti-m page:

>To disable auto-boot and show the prompt, even if Anti-M would normally skip it, you can press either joystick button (open-apple or closed-apple key) while launching Anti-M.

This at least is a workaround.

**Comment by tomcw** [comment]
Equally you can put the original disk you want to boot into drive-2 and just let Anti-M automatically boot it.

**Comment by tomcw** [comment]
OK, the change in behaviour of AppleWin happens at 1.29.8.0, probably due to this change:
- [Bug #748] DiskII: data latch returns a rand() value when no disk is in drive.

At 1.29.7.0 it drops to the Anti-M menu, but at 1.29.8.0 it switches to drive-2 and spins forever.
NB. It's the same with Anti-M 1.4, 1.5, 1.6, 1.7 and 1.8.

**Comment by tomcw** [comment]
#### Anti-M

@peterferrie said:
>It's intended to detect a disk in drive 2. If there's either no drive, or no disk in the drive, then the returned value should be a constant (might not even be a full nibble)

```
20E3: ; CheckDrive2
  LDA $C0E9 ; enable motor on
  LDA $C0EB ; enable drive-2
  ; delay $2683D cycles = 0.157s
  ; Loop 256 times:
  ;   A = A EOR $C0EC
  LDA $C0E8 ; enable motor off
  CMP #0
  RTS
```

I guess the delay stabilises the value in the latch.

NB. AppleWin doesn't support a DiskII card with drive-1, but no drive-2.

So possible emulation logic is:
- After motor on & new drive enable, then:
  - if less than 0.150s then latch returns a random value ; Wizardry IV / V case (meaning drive connected)
  - afterwards latch returns a fixed value ; Anti-M case (meaning drive connected, but no disk)

**Comment by sicklittlemonkey** [comment]
It's your call, but this is getting into some pretty case-specific
behaviour, further and further away from the real hardware.

The Wizardry disk check looks annoying - it seems you must have a disk in
drive 2 for it to be activated. The reason a DSK image doesn't work is
because that code doesn't return partial nibbles, right? (If that's not the
case any more then you can stop reading! : - ) One solution is for DSKs to
return a partial nibble every now and then, and keep the real-world
behaviour that if there's no disk in drive 2, never change the latch and
Wizardry won't use that drive.

I've probably mentioned that I used to do something similar to fool the DOS
(SAMESLOT) code that checks if the drive is up to speed - which is why that
delay is in the code above - to allow the drive to come up to speed so that
the latch changes.

Typical code is to just have a counter which you increase with each access,
and return an invalid nibble when it rolls over, e.g. something like:
return (spin = ((spin + 1) & 0xF)) ? latch : 0x7F;

Cheers,
Nick.

**Comment by tomcw** [comment]
Firstly my (above) "possible emulation logic" was missing the precondition of "when drive is empty...", so I've added that in.

But actually I don't think you have it quite right for Wizardry V...
Since the drive is empty, then there's no image, so it's not a case of DSK(\*) or NIB(\*) or WOZ.

Another thing is that I don't think the Wizardry V check needs to have a disk in the drive, as the check is done during boot, with no instructions to have a disk in drive 2. Although contrary to this is the question (during "Make Scenario Disks") asking if you have 1 or 2 drives! I think this should really be: "Do you want to use 1 or 2 drives?"

Put another way, _before the fix_ for #748:
- booting with drive 2 empty => check would fail
- then responding that you have 2 drives => copy would hang!

Probably a good idea to test some of this on real h/w.

(*) As an aside, $C0EC does return partial nibbles (eg. for SAMESLOT) based on the cycle count between $C0EC accesses, we discussed it a few years ago in #582. Also see here: https://github.com/AppleWin/AppleWin/blob/6f38260b10e0edc251cd216af862314d2db70628/source/Disk.cpp#L943

**Comment by tomcw** [comment]
### Summary after testing on real //e h/w:
1) No drive connected to Disk II Interface or Apple 5.25 Controller card
   * Latch returns a constant value for ~0x2EC-0x990 cycles (depending on card).
   * Latch returns a (maybe different) constant value forever afterwards.
     * typically a nibble (bit7=1), but once 0x00
   * NB. After motor-on ($C0E9), then _some cycles later_ there's some noise that shifts a new constant value into the latch.
     * The number of cycles varies from card to card. It can be ~0x2EC-0x990 cycles (or ~0x2C-0x90 iterations of the loop below, which is 0x11 cycles).

2) Drive connected (to Disk II Interface / Apple 5.25 Controller card) but drive empty
   * Latch returns a constant value for ~0x2EC-0x990 cycles (depending on card).
   * Latch returns a **random** value forever afterwards.
     * typically the random value is a nibble, but will change as the drive's MC3470 detects random noise (where 1=flux change, 0=no change)
   * NB. After motor-on ($C0E9) - same as the (1) 'No drive connected' case.

----

Nick's test code:
```
 STA C0EA
 STA C0E9
:1 LDA C0EC
:2 STA 1000
 INC :2+1
 BNE :1
 INC :2+2
 BPL :1
 STA C0E8
 LDA #$10
 STA :2+2
 RTS
```
300:8D EA C0 8D E9 C0 AD EC C0 8D 0 10 EE A 3 D0 F5 EE B 3 10 F0 8D E8 C0 A9 10 8D B 3 60

For case-1, here are my results using 3 difference Disk II Interface cards in a //e:

[NoDriveConnected.txt](https://github.com/AppleWin/AppleWin/files/5682967/NoDriveConnected.txt)

The first one (which I had tested on a previous day too), I get the consistent "magic offset" of $2C.
The second one, the magic offset moves earlier: $9B -> $91 -> $8F -> $8E, where it seems to settle.
The third one, again the offset moves earlier: $61 -> $5F, where it seems to settle.

----

For case-2: now with drive-1 connected, but no drive-2 connected... again on my //e.

I tried 4 runs of the above test code:

1) 0x60 up to $102C, then random values up to $7FFF
2) 0x0C up to $102C, then random values up to $7FFF
3) Re-coded the test for drive-2 (but not attached): 0xC0 up to $102C, then 0x10, then 0x80 up to $7FFF
4) Back to drive-1: 0x80 up to $102C, then random values up to $7FFF
   * NB, there are runs of constant values, eg. 0xA0 from [$1184 - $11D5] = a run of $52(or 82) nibbles.
   * These runs are not common. Mostly the value is changing every read of $C0EC.

For the Wizardry V case, (as I understand it!) it is looking for a connected drive if 9 pairs of $C0EC reads are different. It retries 0xD30 times.

For reference here's the Wizardry V code: https://github.com/AppleWin/AppleWin/issues/748#issuecomment-573465078

So from my quick experiments, then with a drive connected, the random values will ensure that the Wizardry code finds my drive-1; and also for the constant values it won't find a drive-2 connected.

**Comment by tomcw** [comment]
And Nick's results using 2 different [Apple 5.25 Controller cards](https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Disk%20Drive%20Controllers/Apple%205.25%20Controller%20Card/Photos/) (basically a Disk II Controller but with only one cable) in a //e:

For one in slot 6 with a drive (D1) attached, here are the first $100 bytes:
```
00: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
10: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
20: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
30: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
40: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
50: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
60: 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60 60
70: 60 C1 18 02 20 80 02 40 81 10 80 04 84 84 09 94
80: 04 41 00 20 81 02 23 8C 8C 0A AA AA AA AA 07 70
90: E0 10 80 21 84 10 80 08 89 04 45 8A 04 40 02 40
A0: 80 02 28 A0 A0 A0 A0 08 8C 8C 8C 8C 8C 8C 8C 04
B0: 80 08 84 84 84 84 0A 52 04 48 90 90 90 0D D0 D0
C0: D0 04 42 84 84 20 80 80 14 A5 08 82 82 22 02 48
D0: 04 4A 94 94 94 94 94 08 82 82 82 82 82 82 82 08
E0: 84 18 C2 C2 08 80 80 80 80 80 80 04 42 00 22 88
F0: 20 82 11 8A 06 60 C0 C0 C0 C0 C0 C0 04 81 81 81
```

You can see that $70 is the magic offset. I tried a few runs with similar results.

Now for D2 with no drive daisy chained:
```
00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 00 02 20 80 80 80 80 80 80 80 80 80 80 80 80 80
80: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
90: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
A0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
B0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
C0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
D0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
E0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
F0: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
```

80 went all the way to $7FFF, but notice the same magic offset, $70.

Now for the another 5.25 controller installed in the same //e in slot 2, with no drives attached, so D1 empty:

```
00: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
10: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
20: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
30: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
40: 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80
50: 80 80 80 80 80 80 06 60 C0 C0 C0 C0 C0 C0 C0 C0
60: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
70: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
80: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
90: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
A0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
B0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
C0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
D0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
E0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
F0: C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0 C0
```

Similar, but this card has a different magic offset of $5C.

I conclude that we're probably seeing some analogue behaviour from components - possibly because the DRIVE ON signal gates power via a transistor to turn on the LS174 and sequencer ROM. The LS323 shift register is always powered, but it looks like the power up time of the sequencer circuit varies - maybe in a fixed way per card, similar to the power-on DRAM pattern being per machine.

In the IIgs I observed no such magic offset behaviour. In the //c last weekend I think I saw something similar. I will set it up again and type in the program since I failed to get a good disk working.

**Comment by tomcw** [comment]
Status:
- 469f9ba8070b646f8cc1fe2d4dcd501b66403765 adds some cmd line interface (to disconnect drives1/2 in slot-6) and simple GUI support (eg. error if you try to insert a disk when the drive isn't connected)
- awaiting any feedback from the Anti-M issue, but otherwise this AppleWin issue can be closed

**Comment by tomcw** [comment]
FYI, released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)):
- Improved Disk II card's data latch value when: (a) drive disconnected or (b) connected, but empty.
- New command line switches -d1-disconnected and -d2-disconnected to disconnect drives from slot-6 card.

See status in the previous comment.

**Comment by peterferrie** [comment]
Thanks, this will be good for testing Anti-M.
Related to that, at least in 1.29.15, if a disk was inserted and a
sector header was read, then if I remove the disk and start reading
nibbles again, eventually a complete sector header is read again, as
though the found sector was cached in AppleWin memory.
I'll see if 1.30 behaves the same way.

**Comment by tomcw** [comment]
> if a disk was inserted and a sector header was read, then if I remove the disk and start reading nibbles again, eventually a complete sector header is read again

I tried to give this a quick test using a .woz and from the built-in debugger:
- breaking after reading the first $D5 nibble ($C667 in the Disk II firmware)
- ejecting the disk
- now subsequent $C0EC reads just read random values

I know the above isn't exactly what you said, but if you have a different repo then let me know, and I'll take a look.

**Comment by peterferrie** [comment]
Try this in the debugger:
insert disk
BP C683
Boot disk.
...$C683 is hit.  Remove disk.
G
...$C683 is eventually hit again, implying D5 AA 96 was seen in sequence.
I haven't checked if hardware does the same.  Maybe it's nothing.

**Comment by peterferrie** [comment]
I accept that.
Thanks.

**Comment by sicklittlemonkey** [comment]
We could make this "safer" by restricting the set of random nybbles returned. (A retrocomputing.stackexchange.com conversation has convinced me to revert to Woz's spelling). Probably the easiest and most efficient way is to set or clear a bit - e.g. clear bit 0 with & 0xFE - such that D5 (and in fact half of all possible values) would never occur.

**Comment by tomcw** [comment]
>...$C683 is eventually hit again, implying D5 AA 96 was seen in sequence.

What's the chance?
(1/256)^3 = 1 in 0x1000000

Using Visual Studio, I counted the calls to rand() for the drive-empty $C0EC accesses, and get this number of calls until the sequence 0xD5 0xAA 0x96 (ie. when $C683 is hit):
1. 0x0308291 calls the first time (ie. starting from a fresh AppleWin process start)
2. 0x0939ccd calls the 2nd time (ie. just continuing emulation without restarting the AppleWin process)
3. 0x06c6333 calls the 3rd time (continuing emulation...)
4. 0x0939ccd calls the 4th time (rand has looped?)
5. 0x06c6333 calls the 5th time (yes, definitely looped!)

...and 0x0939ccd + 0x06c6333 = 0x1000000!

So there's a 2 in 0x1000000 (to get this D5/AA/96 sequence) using this rand() pseudo-random number generator function.
Real h/w won't be so predictable! :-)

**Comment by tomcw** [comment]
Descending further down the rabbit hole...

The $C600 firmware is such that it retries if the latch contains a partial nibble (bit7 is not high). So the chance is for a sequence of 0xD5, \<partial nibbles\>, 0xAA, \<partial nibbles\>, 0x96.

I captured the sequence of rand() values fed into the data latch until it hit $C683, and it alternates between:
- `d5/aa/54/07/48/27/96` - a run of 4 partial nibbles
- `d5/78/3b/1a/77/28/aa/96` - a run of 5 partial nibbles

Allowing partial nibbles increases the chance of this D5/AA/96 sequence randomly being emitted as you have to add the infinite probabilities of all the other possible sequences (which tend to zero), eg:

Prob(D5/AA/96) +
Prob(D5/pp/AA/96) + Prob(D5/pp/pp/AA/96) + ... + Prob(D5/pp/.../pp/AA/96) + [row2]
Prob(D5/AA/pp/96) + Prob(D5/AA/pp/pp/96) + ... + Prob(D5/AA/pp/.../pp/96)    [row3]

where: pp = partial nibble (ie. values 0x00..0x7F).
NB. row2 & row3 are the same - so we can just double the result for row2.

Prob(D5/pp/AA/96) = (1/256)^3 + 128/256 = (1/256)^3 x 0.5 = 1 in 0x2000000

Hand waving (because my statistics isn't very good!), then we can ignore smaller terms and just consider:

Prob(D5/AA/96) +
Prob(D5/pp/AA/96) +
Prob(D5/AA/pp/96)

= Prob(D5/AA/96) + 2 x Prob(D5/pp/AA/96)
= 2 in 0x1000000 which is what I empirically got in the previous comment.

**Comment by peterferrie** [comment]
Since this is a bug in Anti-M, it should probably be closed here.
In any case, it's fixed in the repo now.  I'm reading T00S00 from drive 2 to know if there's actually a disk there.  It has to succeed in order to boot, obviously.

**Comment by tomcw** [comment]
>Since this is a bug in Anti-M, it should probably be closed here.

Agreed... and closing this issue.
