### ISSUE TITLE
Update CodingConventions.txt

### ISSUE THREAD

**Issue by tomcw** [AppleWin/AppleWin#868]
Hi @Michaelangel007,

[CodingConventions.txt](https://github.com/AppleWin/AppleWin/blob/master/docs/CodingConventions.txt) could do with an update!

My AppleWin style has deviated from this old Hungarian-heavy convention, and is more "lower camel case" now, generally without any Hungarian prefixes. See this [recent cpp file](https://github.com/AppleWin/AppleWin/blob/master/source/SynchronousEventManager.cpp), where I just use prefixes 'p' (pointer) and 'm_' (member) and not much else!

Obviously the whole codebase is very mature with a range of styles/conventions accrued over the years. I'm not suggesting we change any of the existing code. Just that we update this CodingConventions.txt document to reflect the current convention.

I'm proposing changing it to just be:
```
Prefixes:
g_	: global
m_	: member
p	: pointer
```

And then move everything else to the `Legacy` sub-section.

Also remove the part about "Don't go Hungarian-mad..."

We should also add a note to say to adopt the coding convention of any module (or function) you are modifying.

What do you think?

**Comment by Michaelangel007** [comment]
@tomcw Hey Tom, sorry for the late reply.

If you want to remove the underscore `_` from the prefixes that is perfectly fine.

In my day-to-day graphics / shader job I have a more personal stringent adherence. For example since I deal with math types all the time I usually also have these prefixes:

```
m matrix
v vector
q quaternion
t non-POD
```

Now since AppleWin is NOT math heavy I originally left them out as the Coding Convention back then as the proposed standard was already a bit of a "burden".

Personally, after ~14 years since joining AppleWin, I'm now an even bigger believer in keeping the mini-Hungarian notation "as-is." One of the things I see polluting modern "Crap++" is the abuse of `auto` where the reader can no longer _eassily_ tell the types -- having the burden pushed onto the compiler by the writer -- the reader now has to waste even more time decoding types. I strongly believe a _minimal_ character prefix helps the reader. Either extreme, none, or the other -- the insane verbosity of "pure" Hungarian -- is a hindrance.

Here is the updated listed without the underscores:

```
a	: array
b	: bool
e	: enum variable
g 	: global
h	: handle
i	: iterator (eg. UINT, STL-iterator)
m	: STL map
m	: member
n	: int
p	: pointer
r	: reference
s	: string
sgp	: singleton
u	: unsigned int
v	: STL vector

Tags:
_e	: named enum definitions
_t	: struct/typedef
```

The second reason I'd rather _not_ make any subtraction the existing Coding Conventions -- is that we already have a hodge-podge of conflicting standards as you mention. _Ideally,_ we should be moving towards an unified standard.  Does that mean that we can't change? No, but I feel we would be giving up some clarity be abandoning the existing standard.

One of the reasons I _haven't_ cleaned up the existing code is that busy-work for the sake of busy-work is partially a waste of time. i.e. Don't fix what isn't broken.  

The bigger issue is probably the mixing of spaces and tabs -- it would be nice to specify one rule:

* Tabs for indentation, space for alignment

Speaking of whitespace we probably should clarify this the following in the standard.

a) We should standardize on whitespaces between `if` and the leading parenthesis `(`

b) Keep "column" alignment in existing code
i.e.

```
	ZeroMemory(memmain, 0x10000);
	ZeroMemory(memaux , 0x10000);
```

Obviously I feel very strongly about this topic but I'd be willing to listen to how I can better compromise if you can show code snippets.

**Comment by tomcw** [comment]
>Obviously I feel very strongly about this topic...

Yes, I see that! :-)

>In my day-to-day graphics / shader job...

I don't know too much about shader code and how useful prefixed variable naming is (so I'll take your word for it), but there is no shader code in AppleWin, and for the code in AppleWin differenciating locals vs members, pointers (or not) and globals is really all we deal with. For anything else, the prefix just adds noise.

Here are examples of recent classes I've written, which stick to the very light convention that I outlined in the initial comment:
https://github.com/AppleWin/AppleWin/blob/master/source/CardManager.cpp
https://github.com/AppleWin/AppleWin/blob/master/source/SynchronousEventManager.cpp

My point is that this is the code style that I'm writing in now. I'm definitely not going to revert to a heavy-Hungarian style. So therefore it would be disingenuous to prescribe it in the CodingConventions.txt. The only time it's relevant is for legacy/mature code in the AppleWin codebase or for existing .cpp's which are already heavily using this style.

**Comment by sicklittlemonkey** [comment]
I'm really liking the new light convention, as it's how I've always coded
C++. I've never been into hungarian (not even for pointers).

BTW, together with all the great work being done to properly separate out
and objectize the code, it will make it much easier to read - and
understand.

Cheers,
Nick.

**Comment by Michaelangel007** [comment]
I still feel this is mistake but since both of you feel that we should drop the Hungarian notation then OK, let's adapt the "light conventions".  We can write new code with the "light style" and slowly refactor existing code -- just don't expect me to have any motivation to update the debugger's code anytime soon it pretty much uses all of the list given above . :-)

**Comment by tomcw** [comment]
Thanks Michael 👍 

>just don't expect me to have any motivation to update the debugger's code anytime soon it pretty much uses all of the list given above . :-)

Well that's fine, and falls into this category:

- _For consistency, adopt the coding convention of any module (or function) you are modifying._

So unless someone refactors the entire C++ debugger file, then they should be sticking to your style in the debugger.

**Comment by tomcw** [comment]
Closing, as Michael has merged the PR into master.
