### ISSUE TITLE
Computer Foosball - No Boot with any .woz

### ISSUE THREAD

**Issue by GreatHierophant** [AppleWin/AppleWin#925]
I hesitate to report Computer Foosball, but I converted every .a2r image I could find and not one of them spit out an error with Applesauce but not one of the .woz images works in Applewin or wDrive.  The visualization of the disks are very unusual even by the free-wheeling nature of Apple II disks, so I am not sure if this is a limitation of emulation or imaging.  At best the image will clear the screen, count up to track 10 and then either hang or reboot with a curious tone.  However, 4am's anti-M program states it does work with Computer Foosball, so presumably he or she had an original working disk.

You [can ](https://archive.org/details/a2r_4am) [find ](https://archive.org/details/MoreApplesauceFluxImages3_Sep18) [images](https://archive.org/details/A2CAN_0-E) in [four ](https://archive.org/details/sdancer_a2rs) places.

**Comment by tomcw** [comment]
I am unable to convert from .a2r to woz, so the only .woz image available from those 4 places is a2r_4am, [here](https://archive.org/download/a2r_4am/Computer%20Foosball%20%28Sirius%20Software%29/Computer%20Foosball%20-%20Disk%201%2C%20Side%20A.woz).

woz image info:
- woz v2
- creator = "Applesauce v1.30.3"
- bootsSectorFormat = 3 (dual 13/16)

I tried II+ and unenhanced //e: and they are behave the same, ie. seek to T$10 and hang.
For enhanced //e it doesn't get past T$00 (but as you note, it plays a curious tone).

NB, because of the dual 13/16 sector format, I tried forcing AppleWin to use the 13-sector firmware, but this didn't make any difference.

**Comment by sicklittlemonkey** [comment]
No time to look, sorry, but remember that there are many reasons protected
disks can fail. Like detecting unexpected cards / RAM etc.

Cheers,
Nick.

**Comment by GreatHierophant** [comment]
I have tested it with AppleWin emulating an Apple II+ with no sound cards, hard disk controller, mouse interface or Z80 SoftCard.  I have also tried it with the Apple II emulation with all of the above (and only 48K), but as stripped down as I can get AppleWin (it seems to always have a printer card installed),

**Comment by GreatHierophant** [comment]
The good folk at Apple2Infinitum indicated that the .a2rs needed to be converted in a special way, half tracks needed to be included and they were not.  I obtained a .woz that was properly converted and the game loaded just fine in AppleWin (with a II or II+ or anti-M), so this can be closed.

**Comment by tomcw** [comment]
Thanks for asking in that Slack channel. I grabbed the .woz that 4am shared and confirm it works for an unenhanced //e, but fails to boot for an enhanced //e (unless you use anti-M).

**Comment by tomcw** [comment]
btw, Peter Ferrie commented (about the non-working Foosball.woz):
>Computer Foosball requires half-tracks to be included.
> :
>Foosball is hanging while reading track 1.5 because content is missing.
