### ISSUE TITLE
Characters doubled in BASIC.SYSTEM when using -speech switch

### ISSUE THREAD

**Issue by blindphoneman** [AppleWin/AppleWin#934]
Using the -speech switch, AppleWin speaks simple output in Basic using DOS 3.3 or just plain Applesoft.

However, in PRODOS BASIC.SYSTEM, output from AppleSoft speaks using Double characters.  For example, Syntax error becomes SSyynnttaaxx eerrrroorr.

A funny thing about this is that, if I issue a command in BASIC.SYSTEM that gives output from PRODOS, that output is spoken correctly. For example, if I issue a CAT command, this is spoken correctly, but, anything coming from AppleSoft when BASIC.SYSTEM is running seems to speak with double characters.

Thanks!

**Comment by tomcw** [comment]
Hi @blindphoneman - so far I have been able to confirm the same bad behaviour as you describe.

In terms of technical implementation, I trap calls to COUT (in the Apple II Rom), and can see the double character calls. I don't have enough knowledge about ProDOS to explain this though. I think I will ask on the news-groups, as there are some experts that hang out there that surely will be able to help.

**Comment by blindphoneman** [comment]
Hi:

I bet its something that happens so fast you’d never notice it normally.

Probably some kind of fancy thing their doing for the display.

For comparison, if you run Davex, it doesn’t do this double character thing.

It’ll be interesting if you find out why they might want to do things this way.

Thanks!

Sent from Mail for Windows 10

**Comment by tomcw** [comment]
FYI, I've asked on comp.sys.apple2.programmer, [here.](https://groups.google.com/u/1/g/comp.sys.apple2.programmer/c/ri1RtZ7mv6w)

**Comment by tomcw** [comment]
Kent replied with this:

---

I believe this is due to ProDOS capturing output so that it can find ctrl-D's.
To handle further redirection, it restores $36/$37 to $fdf0 and then calls
$fded again. This is so that if PR#1 is done, $36/$37 would indicate $c100 so
that it can be redirected properly (the $c100 handler will update $36/$37 to a
different vector for the next character, since in#1/pr#1 both call $c100, so
code there has to figure out what's really being requested by looking at
$36/37). And after this $fded call returns, ProDOS restores the $36/37
vector back to point to ProDOS and then returns.

DOS 3.3 does the same thing, but doesn't actually call $fded again,
it just JSR's to a DOS routine which just does JMP (0036). DOS 3.3 could save
3 whole bytes if it JSR'ed to $fded instead.

My suggestion is to capture $fdf0 calls instead, since that will not be
repeated. And capture "pr#3" output as well (I think that will be $c307).

**Comment by blindphoneman** [comment]
Hi: It’s also interesting that, if you do a cat or catalog, or anything else that gives you output from ProDOS, the double-character thing doesn’t happen.

**Comment by tomcw** [comment]
>It’s also interesting that, if you do a cat or catalog, or anything else that gives you output from ProDOS, the double-character thing doesn’t happen.

Yes, I noticed that too.

Anyway, with Kent's suggestion it's now working for DOS, ProDOS and 80COL (PR#3).

This fix will be in the next release.

**Comment by tomcw** [comment]
@blindphoneman: I've released [AppleWin 1.30.0.0](https://github.com/AppleWin/AppleWin/releases/tag/v1.30.0.0(try2)), which has better support for -speech (under ProDOS). Please try it and confirm.

**Comment by blindphoneman** [comment]
Hi:

Looks like you got the double character speech problem licked.

Thanks much!

**Comment by tomcw** [comment]
No problem... and thanks for confirming.
