### ISSUE TITLE
Not remembering "Enhanced disk access speed all drives" setting.

### ISSUE THREAD

**Issue by Keatah** [AppleWin/AppleWin#979]
Just as the title says. Applewin isn't remembering the  "Enhanced disk access speed all drives" setting. It's always turned on with every restart.

**Comment by Keatah** [comment]
I may still have the drive mechanism. If I do it would be in storage with most of my Apple II material. With the damage to the inner tracks and two heads (IIRC) nothing's really recoverable. There may be services that can do a rebuild at high cost. And they would need to be familiar with Apple II formats.

**Comment by H82lose** [comment]
Nah no sweat.  It is what it is.   What’s your fb or email ?
Thanks ,
Patrick



Sent from Yahoo for iPhone


On Wednesday, September 1, 2021, 8:18 PM, Keatah ***@***.***> wrote:




I may still have the drive mechanism. If I do it would be in storage with most of my Apple II material. With the damage to the inner tracks and two heads (IIRC) nothing's really recoverable. There may be services that can do a rebuild at high cost. And they would need to be familiar with Apple II formats.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Keatah** [comment]
Don't generally post email and don't do facebook. But pm me on Applefritter.

**Comment by Keatah** [comment]
Closed. Non-relevant conversation.
