### ISSUE TITLE
Visual Studio 2019 Failed build

### ISSUE THREAD

**Issue by jvernet** [AppleWin/AppleWin#994]
Hi,

From a totally fressh clone of th erepo, I have an error when trying to build with Visual Studio 2019:
_crc32 already defined in zlib.lib(zlib1.dll)
One or more duplicate symbols

Any help ?
Config: Release/Win32

**Comment by jvernet** [comment]
I'm starting from a totally fresh clone of the repo.

```
L'opération de génération a démarré...
1>------ Début de la génération : Projet : AppleWin, Configuration : Release Win32 ------
1>Performing unit-test: TestCPU6502
1>Performing unit-test: TestCPU6502
1>zlib.lib(crc32.obj) : error LNK2005: _crc32 déjà défini(e) dans zlib.lib(zlib1.dll)
1>C:\Users\Jerome\Documents\GitHub\AppleWin\Release\AppleWin.exe : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés
1>Génération du projet "AppleWinExpress2019.vcxproj" terminée -- ÉCHEC.
========== Génération : 0 a réussi, 1 a échoué, 4 à jour, 0 a été ignoré ==========

```

**Comment by sicklittlemonkey** [comment]
Hi guys.

I can't repro either.
VS versions?

Mine is:
Microsoft Visual Studio Professional 2019
Version 16.10.4

Cheers,
Nick.

**Comment by tomcw** [comment]
I did a new (fresh) clone of AppleWin, and using VS2019 16.9.4 to build "Release/Win32" it still works fine.

This reference to "zlib1.dll" is weird...
>1>zlib.lib(crc32.obj) : error LNK2005: _crc32 déjà défini(e) dans zlib.lib(zlib1.dll)

...since we don't build or use any dll's in AppleWin.

**Comment by sicklittlemonkey** [comment]
I notice the SDK dirs are included by default. A long shot though.

This kind of thing (and more templates, really) is why I always said C++
needs a compile-time debugger.
The next best thing is debug logging.

Here's my logging for a build on 1 CPU.

Rebuild started...
1>------ Rebuild All started: Project: zip_lib, Configuration: Release
Win32 ------
2>------ Rebuild All started: Project: zlib, Configuration: Release Win32
------
3>------ Rebuild All started: Project: yaml, Configuration: Release Win32
------
4>------ Rebuild All started: Project: TestCPU6502, Configuration: Release
Win32 ------
1>ioapi.c
2>adler32.c
2>compress.c
2>crc32.c
2>deflate.c
2>gzclose.c
2>gzlib.c
3>api.c
2>gzread.c
3>dumper.c
2>gzwrite.c
2>infback.c
3>emitter.c
2>inffast.c
2>inflate.c
2>inftrees.c
1>iowin32.c
1>mztools.c
1>unzip.c
1>zip.c
3>loader.c
4>SynchronousEventManager.cpp
2>trees.c
3>parser.c
2>uncompr.c
2>zutil.c
3>reader.c
3>scanner.c
1>zip_lib2019.vcxproj ->
C:\Users\nickw\Documents\GitHub\AppleWin\Release\zip_lib.lib
3>writer.c
2>zlib-Express2019.vcxproj ->
C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.lib
4>stdafx.cpp
3>yaml2019.vcxproj ->
C:\Users\nickw\Documents\GitHub\AppleWin\Release\yaml.lib
4>TestCPU6502.cpp
4>Generating code
4>Previous IPDB not found, fall back to full compilation.
4>All 47 functions were compiled because no usable IPDB/IOBJ from previous
compilation was found.
4>Finished generating code
4>TestCPU6502-vs2019.vcxproj ->
C:\Users\nickw\Documents\GitHub\AppleWin\Release\TestCPU6502.exe
5>------ Rebuild All started: Project: AppleWin, Configuration: Release
Win32 ------
5>Performing unit-test: TestCPU6502
5>Performing unit-test: TestCPU6502
5>StdAfx.cpp
5>6821.cpp
5>AY8910.cpp
5>CardManager.cpp
5>CmdLine.cpp
5>About.cpp
5>PageAdvanced.cpp
5>PageConfig.cpp
5>PageConfigTfe.cpp
5>PageDisk.cpp
5>PageInput.cpp
5>PageSound.cpp
5>PropertySheet.cpp
5>PropertySheetHelper.cpp
5>Core.cpp
5>CPU.cpp
5>Debugger_Disassembler.cpp
5>Debugger_Win32.cpp
5>Disk2CardManager.cpp
5>FourPlay.cpp
5>FrameBase.cpp
5>Generating Code...
5>Compiling...
5>RGBMonitor.cpp
5>SAM.cpp
5>Debug.cpp
5>Debugger_Assembler.cpp
5>Debugger_Color.cpp
5>Debugger_Commands.cpp
5>Debugger_Console.cpp
5>Debugger_DisassemblerData.cpp
5>Debugger_Display.cpp
5>Debugger_Help.cpp
5>Debugger_Parser.cpp
5>Debugger_Range.cpp
5>Debugger_Symbols.cpp
5>Util_MemoryTextFile.cpp
5>Disk.cpp
5>DiskFormatTrack.cpp
5>DiskImage.cpp
5>DiskImageHelper.cpp
5>Harddisk.cpp
5>Joystick.cpp
5>Generating Code...
5>Compiling...
5>Keyboard.cpp
5>LanguageCard.cpp
5>Log.cpp
5>Memory.cpp
5>Mockingboard.cpp
5>MouseInterface.cpp
5>NoSlotClock.cpp
5>NTSC.cpp
5>NTSC_CharSet.cpp
5>ParallelPrinter.cpp
5>Pravets.cpp
5>Registry.cpp
5>Riff.cpp
5>SaveState.cpp
5>SerialComms.cpp
5>SNESMAX.cpp
5>SoundCore.cpp
5>Speaker.cpp
5>Speech.cpp
5>SSI263.cpp
5>Generating Code...
5>Compiling...
5>SynchronousEventManager.cpp
5>Tape.cpp
5>Utilities.cpp
5>Video.cpp
5>AppleWin.cpp
5>DirectInput.cpp
5>HookFilter.cpp
5>Win32Frame.cpp
5>WinFrame.cpp
5>YamlHelper.cpp
5>z80emu.cpp
5>Generating Code...
5>tfe.cpp
5>tfearch.cpp
5>tfesupp.cpp
5>Uilib.cpp
5>daa.cpp
5>z80.cpp
5>z80mem.cpp
5>Generating Code...
5>Generating code
5>Finished generating code
5>zip_lib.lib(zip.obj) : warning LNK4099: PDB 'zip_lib.pdb' was not found
with 'zip_lib.lib(zip.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zip_lib.pdb'; linking
object as if no debug info
5>zip_lib.lib(unzip.obj) : warning LNK4099: PDB 'zip_lib.pdb' was not found
with 'zip_lib.lib(unzip.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zip_lib.pdb'; linking
object as if no debug info
5>zip_lib.lib(ioapi.obj) : warning LNK4099: PDB 'zip_lib.pdb' was not found
with 'zip_lib.lib(ioapi.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zip_lib.pdb'; linking
object as if no debug info
5>zlib.lib(gzread.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with
'zlib.lib(gzread.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(gzwrite.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(gzwrite.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(gzclose.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(gzclose.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(crc32.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with
'zlib.lib(crc32.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(gzlib.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with
'zlib.lib(gzlib.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(deflate.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(deflate.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(inflate.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(inflate.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(trees.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with
'zlib.lib(trees.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(zutil.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with
'zlib.lib(zutil.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(adler32.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(adler32.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(inftrees.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(inftrees.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>zlib.lib(inffast.obj) : warning LNK4099: PDB 'zlib.pdb' was not found
with 'zlib.lib(inffast.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\zlib.pdb'; linking object
as if no debug info
5>yaml.lib(api.obj) : warning LNK4099: PDB 'yaml.pdb' was not found with
'yaml.lib(api.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\yaml.pdb'; linking object
as if no debug info
5>yaml.lib(parser.obj) : warning LNK4099: PDB 'yaml.pdb' was not found with
'yaml.lib(parser.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\yaml.pdb'; linking object
as if no debug info
5>yaml.lib(scanner.obj) : warning LNK4099: PDB 'yaml.pdb' was not found
with 'yaml.lib(scanner.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\yaml.pdb'; linking object
as if no debug info
5>yaml.lib(reader.obj) : warning LNK4099: PDB 'yaml.pdb' was not found with
'yaml.lib(reader.obj)' or at
'C:\Users\nickw\Documents\GitHub\AppleWin\Release\yaml.pdb'; linking object
as if no debug info
5>AppleWinExpress2019.vcxproj ->
C:\Users\nickw\Documents\GitHub\AppleWin\Release\AppleWin.exe
5>Done building project "AppleWinExpress2019.vcxproj".
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========

**Comment by tomcw** [comment]
@jvernet - just returning to this ~4 month old issue.
Did you ever get this working?

**Comment by tomcw** [comment]
Closing old issue - invalid.
